<?php
/**
 * SEO campaign edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.2
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Makabe\Controllers\SeoCampaignsController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->mms . '/seo-campaigns';
$keywords_url = ($this->di->getConfig())->urls->mms . '/keywords';
$page_url = ($this->di->getConfig())->urls->mms . '/page-scanner';

//$search_results = (new SeoCampaignsController())->createCloudSearchDatasource($data);

echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>

<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>" enctype="multipart/form-data">
    <div class="row mb-3">
        <div class="col-3">
            <div class="card bg-info">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                        <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                        <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <?= DateHelper::prettyFull($data->search_engine_last_scanned, false, false, 'Never'); ?>
					</div>
                    <div class="text-white">
                        Last scanned
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-primary">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                        <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->stats['total']; ?></strong> visit<?= $data->stats['total'] == 1 ? '' : 's'; ?>
                    </div>
                    <div class="text-white">
                        Visits with this campaign
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <a
                        href="<?= UrlHelper::backend($url); ?>"
                        class="btn btn-blank mr-2 text-center"
                        title="Go back to the campaigns list"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                        </svg><br/>
                        back
                    </a>
                    <?php
                    if (empty($data->job)) {
                        ?>
                        <button
                            id="btn-save"
                            class="btn btn-blank float-right"
                            type="button"
                            title="Save the campaign"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                            </svg><br/>
                            save
                        </button>
                        <a
                            href="<?= UrlHelper::backend($url . '/re-scan/' . $data->id); ?>"
                            class="btn btn-blank float-right"
                            title="Re-scan the search term"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M1.161 8a6.84 6.84 0 1 0 6.842-6.84.58.58 0 1 1 0-1.16 8 8 0 1 1-6.556 3.412l-.663-.577a.58.58 0 0 1 .227-.997l2.52-.69a.58.58 0 0 1 .728.633l-.332 2.592a.58.58 0 0 1-.956.364l-.643-.56A6.812 6.812 0 0 0 1.16 8z"/>
                                <path d="M6.641 11.671V8.843h1.57l1.498 2.828h1.314L9.377 8.665c.897-.3 1.427-1.106 1.427-2.1 0-1.37-.943-2.246-2.456-2.246H5.5v7.352h1.141zm0-3.75V5.277h1.57c.881 0 1.416.499 1.416 1.32 0 .84-.504 1.324-1.386 1.324h-1.6z"/>
                            </svg><br/>
                            re-scan
                        </a>
                        <?php
                        if ($data->deleted_at) {
                            ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Recover the campaign from the trash">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                    </svg><br/>
                                    recover
                                </div>
                            </button>
                            <?php
                        } else {
                        ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Throw the campaign into the trash">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg><br/>
                                    delete
                                </div>
                            </button>
                            <?php
                        }
                    }
                    ?>
                    <a
                        href="<?= $data->search_engine_url; ?>"
                        target="_blank"
                        class="btn btn-blank float-right"
                        title="View the search live"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2.5 13.5A.5.5 0 0 1 3 13h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zM13.991 3l.024.001a1.46 1.46 0 0 1 .538.143.757.757 0 0 1 .302.254c.067.1.145.277.145.602v5.991l-.001.024a1.464 1.464 0 0 1-.143.538.758.758 0 0 1-.254.302c-.1.067-.277.145-.602.145H2.009l-.024-.001a1.464 1.464 0 0 1-.538-.143.758.758 0 0 1-.302-.254C1.078 10.502 1 10.325 1 10V4.009l.001-.024a1.46 1.46 0 0 1 .143-.538.758.758 0 0 1 .254-.302C1.498 3.078 1.675 3 2 3h11.991zM14 2H2C0 2 0 4 0 4v6c0 2 2 2 2 2h12c2 0 2-2 2-2V4c0-2-2-2-2-2z"/>
                        </svg><br/>
                        view
                    </a>
                    <a
                        href="<?= UrlHelper::backend($url . '/build'); ?>"
                        class="btn btn-blank float-right"
                        title="Build a new campaign"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                        </svg><br/>
                        new
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
		<div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <?php
                            if ($data->deleted_at) {
                                $label = "I'm in a deleted state";
                                $bg_colour = 'bg-danger';
                            } else {
                                $label = "I'm live!";
                                $bg_colour = 'bg-success';
                            }
                        ?>
                        <div class="mr-4 mb-4">
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div title="<?= $label; ?>" class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="name">
                                    Name
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="search_engine_id">
                                    Search engine
                                    <span class="required">*</span>
                                </label>
                                <select
                                    id="search_engine_id"
                                    name="search_engine_id"
                                    class="form-control mt-2"
                                    aria-describedby="search_engine_id"
                                    required>
									<?php
									$selected = FormController::getFormData('search_engine_id', $data);
									foreach ($search_engines as $engine) {
										?>
										<option
											value="<?= $engine['id']; ?>"
											<?= $selected == $engine['id'] ? 'selected' : '';?>>
											<?= $engine['name']; ?>
										</option>
										<?php
									}
									?>
								</select>
                            </div>
                            <div class="form-group mb-4">
                                <label for="search_terms">
                                    Search terms
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="search_terms"
                                    name="search_terms"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="search_terms"
                                    value="<?= FormController::getFormData('search_terms', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="upload_html">
                                    Upload HTML
                                </label>
                                <input
                                    id="upload_html"
                                    name="upload_html"
                                    type="file"
                                    accept="text/html"
                                    class="form-control mt-2">
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab"
                                aria-controls="overview-tab"
                                aria-selected="<?= UrlHelper::activeTab('overview-tab', 'overview-tab', true); ?>">
                                Search engine results
                                <?php
								if ($results_count = count($overview)) {
									?>
									<span class="badge badge-primary"><?= $results_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('pages-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#pages-tab"
                                aria-controls="pages-tab"
                                aria-selected="<?= UrlHelper::activeTab('pages-tab', 'overview-tab', true); ?>">
                                Scanned pages
                                <?php
								if ($scanned_count = $data->scan_pages->count()) {
									?>
									<span class="badge badge-primary"><?= $scanned_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#stats-tab">
                                Stats
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="card">
                        <div class="card-body p-3 pt-0">
                            <div class="row">
                                <div class="col-12 mb-4">
                                <?php
                                if (!empty($overview)) {
                                    ?>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th width="150px">
                                                    <div class="form-group form-check">
                                                        <div class="checkbox switcher">
                                                            <label>
                                                                <input id="site-select-all" type="checkbox" name="all" value="">
                                                                <span>
                                                                    <small class="switcher-on">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                        </svg>
                                                                    </small>
                                                                    <small class="switcher-off">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                        </svg>
                                                                    </small>
                                                                </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </th>
                                                <th width="40px">&#35;</th>
                                                <th>Title</th>
                                                <th>Description</th>
                                                <th>URL</th>
                                                <th width="80px">&nbsp</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($overview as $key => $result) {
                                            if ($result['url'] == 'DELETED') {
                                                continue;
                                            }
                                            ?>  
                                            <tr>
                                                <td>
                                                    <div class="form-group form-check">
                                                        <div class="checkbox switcher">
                                                            <label>
                                                                <input
                                                                    type="checkbox"
                                                                    name="site_url[]"
                                                                    value="<?= $result['url'] . '|' . ($key + 1) . '|' . $result['title']; ?>"
                                                                    <?= $result['selected'] ? 'checked' : ''; ?>>
                                                                <span>
                                                                    <small class="switcher-on">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                        </svg>
                                                                    </small>
                                                                    <small class="switcher-off">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                        </svg>
                                                                    </small>
                                                                </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <?= $key + 1; ?>
                                                </td>
                                                <td>
                                                    <?= $result['title']; ?>
                                                </td>
                                                <td>
                                                    <?= $result['description']; ?>
                                                </td>
                                                <td>
                                                    <a
                                                        href="<?= $result['url']; ?>"
                                                        target="_blank">
                                                        <?= $result['url']; ?>
                                                    </a>
                                                </td>
                                                <td>
                                                    <a
                                                        href="<?= UrlHelper::backend($url . '/delete/' . $data->id . '/result/' . urlencode($result['url'])); ?>"
                                                        class="btn btn-blank float-right"
                                                        title="Delete the page"
                                                        data-toggle="tooltip"
                                                        data-trigger="hover"
                                                        data-dismiss="click"
                                                        data-placement="top">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                        </svg>
                                                    </a>
                                                </td>
                                            </tr>                                                                            
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                    <?php
                                } else {
                                    ?>
                                    <p class="h6 pb-0 m-0">No search overview</p>
                                    <?php
                                }
                                ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('pages-tab', 'overview-tab'); ?>"
                    id="pages-tab"
                    role="tabpanel"
                    aria-labelledby="pages-tab">
                    <div class="row">
                        <?php
                        if (!empty($data->job)) {
                            ?>
                            <div class="col-12">
                                <div class="alert alert-info d-flex align-items-center">
                                    <div class="d-flex flex-column">
                                        <p>Awaiting page scan job to be complete</p>
                                    </div>
                                </div>
                            </div>
                            <?php
                        } else {
                            ?>
                            <div class="col-12">
                            <?= $this->partial(
                                'makabe/words/widget',
                                [
                                    'words' => $data->words,
                                    'campaign_id' => $data->id,
                                    'tab' => 'pages-tab',
                                    'url' => $url . '/edit/' . $data->id
                                ]
                            ); ?>
                            </div>
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-header mb-2">
                                        Search pages
                                    </div>
                                    <div class="card-body p-3 pt-0">
                                        <input
                                            type="text"
                                            name="search_keyword"
                                            class="form-control input-search float-left"
                                            placeholder="Search"
                                            data-url="<?= UrlHelper::backend($url . '/edit/' . $data->id); ?>"
                                            value="<?= !empty($_GET['search_keyword']) ? $_GET['search_keyword'] : ''; ?>">
                                        <?php
                                        if (!empty($_GET['search_keyword'])) {
                                            ?>
                                            <a
                                                href="<?= UrlHelper::backend($url . '/edit/' . $data->id . '?tab=pages-tab'); ?>"
                                                title="Clear the search"
                                                class="btn-clear-search float-left">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </a>
                                            <a
                                                href="<?= UrlHelper::backend($keywords_url  . '/add?keyword=' . urlencode($_GET['search_keyword'])); ?>"
                                                target="_blank"
                                                title="Save the keyword"
                                                class="btn btn-blank float-right"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
                                                    <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                                    <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                                </svg><br/>
                                                save
                                            </a>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <?php
                            if (!empty($search_results)) {
                                ?>
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-body p-3 pt-0">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th width="40px">&#35;</th>
                                                        <th>Text</th>
                                                        <th width="90px">Tag</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                foreach ($search_results as $result) {
                                                    ?>  
                                                    <tr>
                                                        <td colspan="2" class="pt-4 pb-4">
                                                            <?php
                                                                $text = htmlentities($result['text']);
                                                                preg_match_all(
                                                                    '/' . $_GET['search_keyword'] . '/i',
                                                                    $text,
                                                                    $matches
                                                                );
                                                                if ($matches) {
                                                                    foreach ($matches as $match) {
                                                                        $text = str_replace(
                                                                            $match[0],
                                                                            '<span class="search-hightlight">' . $match[0] . '</span>',
                                                                            $text
                                                                        );
                                                                    }
                                                                }
                                                                echo $text;
                                                            ?>
                                                        </td>
                                                        <td>
                                                            <?= $result['tag']; ?>
                                                        </td>
                                                    </tr>
                                                    <tr style="background-color: var(--bg-grey-lighter);">
                                                        <td>
                                                            <strong>&#35;<?= $result['rank']; ?></strong>
                                                        </td>
                                                        <td>
                                                            <strong><?= $result['source'];?></strong>
                                                        </td>
                                                        <td>
                                                            <a
                                                                href="<?= UrlHelper::backend($page_url . '/edit/' . $result['id']); ?>"
                                                                class="btn btn-blank float-right"
                                                                title="Edit the page to scan"
                                                                data-toggle="tooltip"
                                                                data-trigger="hover"
                                                                data-dismiss="click"
                                                                data-placement="top">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                                </svg>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <?php
                            } elseif (!empty($_GET['search_keyword'])) {
                                ?>
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-body p-3 pt-0">
                                            <strong class="h5">No results</strong>
                                        </div>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body pt-0 mb-4">
                                        <?php
                                        if ($data->scan_pages->count()) {
                                            ?>
                                            <table class="table tablesorter">
                                                <thead>
                                                    <tr>
                                                        <th>&#35;</th>
                                                        <th>Name</th>
                                                        <th>URL</th>
                                                        <th>Status</th>
                                                        <th width="200px">&nbsp;</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    foreach ($data->scan_pages as $row) {
                                                        switch ($row->scan_status) {
                                                            case 'scanned':
                                                                $bg_colour = 'badge-success';
                                                                break;
                                                            case 'not scanned':
                                                                $bg_colour = 'badge-warning';
                                                                break;
                                                            case 'failed':
                                                                $bg_colour = 'badge-danger';
                                                                break;
                                                            default:
                                                                break;
                                                        }
                                                        ?>
                                                        <tr>
                                                            <td><?= $row->rank; ?></td>
                                                            <td>
                                                                <a href="<?= UrlHelper::backend($page_url . '/edit/' . $row->id); ?>">
                                                                    <?= $row->name; ?>
                                                                </a>
                                                            </td>
                                                            <td>
                                                                <a href="<?= UrlHelper::backend($page_url . '/edit/' . $row->id); ?>">
                                                                    <?= $row->url ?>
                                                                </a>
                                                            </td>
                                                            <td>
                                                                <a href="<?= UrlHelper::backend($page_url . '/edit/' . $row->id); ?>">
                                                                    <span class="badge <?= $bg_colour; ?>">
                                                                        <?= $row->scan_status ?>
                                                                    </span>
                                                                </a>
                                                            </td>
                                                            <td>
                                                                <a
                                                                    href="<?= UrlHelper::backend($page_url . '/edit/' . $row->id); ?>"
                                                                    class="btn btn-blank float-right p-0"
                                                                    title="Edit the page to scan"
                                                                    data-toggle="tooltip"
                                                                    data-trigger="hover"
                                                                    data-dismiss="click"
                                                                    data-placement="top">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                        <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                                    </svg>
                                                                </a>
                                                                <a
                                                                    href="<?= UrlHelper::backend($page_url . '/re-scan/' . $row->id . '?from=' . urlencode(UrlHelper::append(UrlHelper::get(), 'tab=pages-tab'))); ?>"
                                                                    class="btn btn-blank float-right p-0 mr-2 show-processing"
                                                                    title="Re-scan the page"
                                                                    data-toggle="tooltip"
                                                                    data-trigger="hover"
                                                                    data-dismiss="click"
                                                                    data-placement="top">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M1.161 8a6.84 6.84 0 1 0 6.842-6.84.58.58 0 1 1 0-1.16 8 8 0 1 1-6.556 3.412l-.663-.577a.58.58 0 0 1 .227-.997l2.52-.69a.58.58 0 0 1 .728.633l-.332 2.592a.58.58 0 0 1-.956.364l-.643-.56A6.812 6.812 0 0 0 1.16 8z"/>
                                                                        <path d="M6.641 11.671V8.843h1.57l1.498 2.828h1.314L9.377 8.665c.897-.3 1.427-1.106 1.427-2.1 0-1.37-.943-2.246-2.456-2.246H5.5v7.352h1.141zm0-3.75V5.277h1.57c.881 0 1.416.499 1.416 1.32 0 .84-.504 1.324-1.386 1.324h-1.6z"/>
                                                                    </svg>
                                                                </a>
                                                                <button
                                                                    type="button"
                                                                    class="btn btn-blank float-right p-0 mr-2"
                                                                    data-original-title="Are you sure?"
                                                                    data-trigger="focus"
                                                                    data-html="true"
                                                                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($page_url . '/delete/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id . '?tab=pages-tab'); ?>">Yes</a>'
                                                                    data-toggle="popover">
                                                                    <span
                                                                        title="Delete the page"
                                                                        data-toggle="tooltip"
                                                                        data-trigger="hover"
                                                                        data-dismiss="click"
                                                                        data-placement="top">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                                        </svg>
                                                                    </span>
                                                                </button>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                    }
                                                    ?>
                                                </tbody>
                                            </table>
                                            <?php
                                        } else {
                                            ?>
                                            <p class="h6 pb-0 m-0">No pages</p>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <?php
                        if (!empty($data->job)) {
                            ?>
                            <div class="col-12">
                                <div class="alert alert-info d-flex align-items-center">
                                    <div class="d-flex flex-column">
                                        <p>Awaiting page scan job to be complete</p>
                                    </div>
                                </div>
                            </div>
                            <?php
                        } else {
                            ?>
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="card shadow-none">
                                            <div class="card-header m-0">
                                                <span class="card-title">Notes</span>
                                            </div>
                                            <div class="card-body">
                                                <?= $this->partial(
                                                    'common/notes/list',
                                                    [
                                                        'notes' => $data->notes,
                                                        'url' => $url . '/edit/' . $data->id . '?clear=true#notes-tab'
                                                    ]
                                                ); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                    id="stats-tab"
                    role="tabpanel"
                    aria-labelledby="stats-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("website/pages/sections/stats", ['data' => $data]); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(function () {
        $("#site-select-all").change((event) => {
            if ($(event.target).is(':checked')) {
                $("input[name^=site_url]").prop("checked", true);
            } else {
                $("input[name^=site_url]").prop("checked", false);
            }
        });

        $("input[name=search_keyword]").keyup((event) => {
            if (event.key == "Enter") {
                window.location.href = $(event.target).data('url') +
                    "?tab=pages-tab&search_keyword=" + $(event.target).val();
                //+ "&search_type=" + $("input[name=search_type]").val()
            }
        });

        $(".word-cloud").click((event) => {
            $("input[name=search_keyword]").val(
                //($("input[name=search_keyword]").val() + " " + $(event.target).html()).trim()
                ($("input[name=search_keyword]").val() + " " + $(event.currentTarget).data("word")).trim()
            );
        });
    });
</script>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
