<?php
/**
 * Page category add template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$path = parse_url($_SERVER['REQUEST_URI']);
$url = ltrim(rtrim($path['path'], '/add'), UrlHelper::backend('/'));
echo $this->partial("common/form/messages");
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/save?from=' . urlencode($url)); ?>" enctype="multipart/form-data">
    <div class="row mb-3">
        <div class="col-12">
			<div class="card p-0">
				<div class="card-body">
					<button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save the category"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
		            <button
		                type="button"
		                title="Are you sure?"
		                data-html="true"
		                data-trigger="focus"
		                data-toggle="popover"
		                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/add'); ?>">Yes</a>'
		                class="btn btn-blank float-right m-0 mr-2">
		                <div
		                    title="Start over with a fresh category"
		                    data-toggle="tooltip"
		                    data-trigger="hover"
		                    data-dismiss="click"
		                    data-placement="top">
							<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
  								<path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
  								<path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
							</svg><br/>
		                    reset
		                </div>
		            </button>
					<a
						href="<?= UrlHelper::backend($url); ?>"
						class="btn btn-blank mr-2 text-center"
						title="Go back to the categories list"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="bottom">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
							<path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
						</svg><br/>
						back
					</a>
		        </div>
		    </div>
		</div>
	</div>
    <div class="row">
        <div class="col-12 mb-3">
            Required fields <span class="required">*</span>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4 pb-0">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
							<div
								class="preview-img"
								title="I'm inactive"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="bottom">
	                            <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/new-item.png'); ?>" 
                                        alt="Add an entry">
								</div>
	                            <div class="circle border border-white bg-warning"></div>
							</div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group form-check mt-0 mb-4">
                                <label for="status">Go live</label>
                                <div class="checkbox switcher mt-2">
                                    <label>
                                        <input
                                            id="status"
                                            type="checkbox"
                                            name="status"
                                            value="<?= FormController::getFormData('status', null, 'active'); ?>"
                                            <?= FormController::getFormData('status', null, 'active') == 'active' ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group mb-4">
                                <label for="name">
									Title
                                    <span class="required">*</span>
								</label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name'); ?>"
									required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="summary">Summary</label>
                                <input
                                    id="summary"
                                    name="summary"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="summary"
                                    value="<?= FormController::getFormData('summary'); ?>">
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Overview
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('template-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#template-tab">
                                Look &amp; feel <span class="required">*</span>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('seo-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#seo-tab">
                                SEO
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags"); ?>
                        </div>
                        <div class="col-12">
                            <?= $this->partial('website/pages/sections/content'); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('template-tab', 'overview-tab'); ?>"
                    id="template-tab"
                    role="tabpanel"
                    aria-labelledby="template-tab">
                    <?= $this->partial("website/templates/widget", ['data' => null]); ?>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('seo-tab', 'overview-tab'); ?>"
                    id="seo-tab"
                    role="tabpanel"
                    aria-labelledby="seo-tab">
                    <?= $this->partial(
						"website/pages/sections/seo",
						[
							'data' => null,
							'add' => true
						]
					); ?>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
