<?php
/**
 * Page category edit template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$path = parse_url($_SERVER['REQUEST_URI']);
$url = ltrim(rtrim($path['path'], '/edit/' . $data->id), UrlHelper::backend('/'));

$back_url = $url;
$save_url = $url . '/update/' . $data->id . '?from=' . urlencode($path['path']);

if (!empty($_GET['back-url'])) {
    $back_url = urldecode($_GET['back-url']);
    $save_url .= '&back-url=' . urlencode($back_url);
}

echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-primary">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->quantity; ?></strong>
                </div>
                <div class="text-white">
                    Quantity
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1H1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->total; ?></strong>
                </div>
                <div class="text-white">
                    Total
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <?php
                    if ($data->status == 'dispatch') {
                        ?>
                        <path d="M11.5 4a.5.5 0 0 1 .5.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-4 0 1 1 0 0 1-1-1v-1h11V4.5a.5.5 0 0 1 .5-.5zM3 11a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm1.732 0h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4a2 2 0 0 1 1.732 1z"/>
                        <?php
                    } elseif ($data->status == 'shipped') {
                        ?>
                        <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                        <?php
                    } elseif ($data->status == 'deleted') {
                        ?>
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        <?php
                    }
                    ?>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->status; ?></strong>
                </div>
                <div class="text-white">
                    Status
				</div>
            </div>
        </div>
    </div>
</div>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($save_url); ?>" enctype="multipart/form-data">
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <a
                        href="<?= UrlHelper::backend($back_url); ?>"
                        class="btn btn-blank mr-2 text-center"
                        title="Go back to the categories list"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                        </svg><br/>
                        back
                    </a>
                    <button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save the order"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
                    <a
                        href="<?= UrlHelper::backend($url . '/clone/' . $data->id); ?>"
                        class="btn btn-blank float-right"
                        title="Clone the order"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                        </svg><br/>
                        clone
                    </a>
                    <?php
                    if (!$data->dispatched_at) {
                        if ($data->status == 'deleted') {
                            ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Recover the order">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                    </svg><br/>
                                    recover
                                </div>
                            </button>
                            <?php
                        } else {
                        ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Delete the order">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg><br/>
                                    delete
                                </div>
                            </button>
                            <?php
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-3">
            Required fields <span class="required">*</span>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Billing address
                </div>
                <div class="card-body p-0 pt-4 pb-0">
                    <div class="form-group mb-4">
                        <label for="billing_first_name">
                            First name<span class="required">*</span>
                        </label>
                        <input
                            id="billing_first_name"
                            name="billing_first_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_first_name"
                            value="<?= FormController::getFormData('billing.first_name', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_last_name">
                            Last name<span class="required">*</span>
                        </label>
                        <input
                            id="billing_last_name"
                            name="billing_last_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_last_name"
                            value="<?= FormController::getFormData('billing.last_name', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_email">
                            Email<span class="required">*</span>
                        </label>
                        <input
                            id="billing_email"
                            name="billing_email"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_email"
                            value="<?= FormController::getFormData('billing.email_address', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_phone">
                            Phone
                        </label>
                        <input
                            id="billing_phone"
                            name="billing_phone"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_phone"
                            value="<?= FormController::getFormData('billing.phone_number', $data); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_address_line_1">
                            Address line 1<span class="required">*</span>
                        </label>
                        <input
                            id="billing_address_line_1"
                            name="billing_address_line_1"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_address_line_1"
                            value="<?= FormController::getFormData('billing.address_line_1', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_address_line_2">
                            Address line 2
                        </label>
                        <input
                            id="billing_address_line_2"
                            name="billing_address_line_2"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_address_line_2"
                            value="<?= FormController::getFormData('billing.address_line_2', $data); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_town">
                            Town<span class="required">*</span>
                        </label>
                        <input
                            id="billing_town"
                            name="billing_town"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_town"
                            value="<?= FormController::getFormData('billing.town', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_county">
                            County<span class="required">*</span>
                        </label>
                        <input
                            id="billing_county"
                            name="billing_county"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_county"
                            value="<?= FormController::getFormData('billing.county', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_postcode">
                            Postcode<span class="required">*</span>
                        </label>
                        <input
                            id="billing_postcode"
                            name="billing_postcode"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_postcode"
                            value="<?= FormController::getFormData('billing.postcode', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_country">
                            Country<span class="required">*</span>
                        </label>
                        <input
                            id="billing_country"
                            name="billing_country"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_country"
                            value="<?= FormController::getFormData('billing.country', $data); ?>"
                            required>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Shipping address
                </div>
                <div class="card-body p-0 pt-4 pb-0">
                    <div class="form-group mb-4">
                        <label for="delivery_first_name">
                            First name<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_first_name"
                            name="delivery_first_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_first_name"
                            value="<?= FormController::getFormData('delivery.first_name', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_last_name">
                            Last name<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_last_name"
                            name="delivery_last_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_last_name"
                            value="<?= FormController::getFormData('delivery.last_name', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_email">
                            Email<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_email"
                            name="delivery_email"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_email"
                            value="<?= FormController::getFormData('delivery.email_address', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_phone">
                            Phone
                        </label>
                        <input
                            id="delivery_phone"
                            name="delivery_phone"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_phone"
                            value="<?= FormController::getFormData('delivery.phone_number', $data); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_address_line_1">
                            Address line 1<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_address_line_1"
                            name="delivery_address_line_1"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_address_line_1"
                            value="<?= FormController::getFormData('delivery.address_line_1', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_address_line_2">
                            Address line 2
                        </label>
                        <input
                            id="delivery_address_line_2"
                            name="delivery_address_line_2"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_address_line_2"
                            value="<?= FormController::getFormData('delivery.address_line_2', $data); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_town">
                            Town<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_town"
                            name="delivery_town"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_town"
                            value="<?= FormController::getFormData('delivery.town', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_county">
                            County<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_county"
                            name="delivery_county"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_county"
                            value="<?= FormController::getFormData('delivery.county', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_postcode">
                            Postcode<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_postcode"
                            name="delivery_postcode"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_postcode"
                            value="<?= FormController::getFormData('delivery.postcode', $data); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="delivery_country">
                            Country<span class="required">*</span>
                        </label>
                        <input
                            id="delivery_country"
                            name="delivery_country"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="delivery_country"
                            value="<?= FormController::getFormData('delivery.country', $data); ?>"
                            required>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4 pb-0">
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Overview
                            </a>
                        </li>
						<li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#stats-tab">
                                Stats
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <?php
                                    if ($data->items) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Product</th>
                                                    <th width="120">In stock</th>
                                                    <th width="120">Quantity</th>
                                                    <th width="120">Fulfilled</th>
                                                    <th width="140">Sub-total</th>
                                                    <th width="140">VAT</th>
                                                    <th width="140">Total</th>
                                                    <th width="70">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                foreach ($data->items as $item) {
                                                    ?>
                                                    <tr>
                                                        <td>
                                                            <a href="<?= UrlHelper::backend(($this->di->getConfig())->urls->sales . '/products/edit/' . $item->product->page_id); ?>">
                                                                <?= $item->product->page->name; ?>
                                                            </a>
                                                        </td>
                                                        <td><?= $item->product->stock; ?></td>
                                                        <td><?= $item->quantity; ?></td>
                                                        <td><?= $item->fulfilled; ?></td>
                                                        <td><?= $item->sub_total; ?></td>
                                                        <td><?= $item->vat; ?></td>
                                                        <td><?= $item->total; ?></td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th colspan="4" class="border-0">&nbsp;</th>
                                                    <th class="text-right">Sub-total</th>
                                                    <td><?= $data->sub_total; ?></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <th colspan="4" class="border-0">&nbsp;</th>
                                                    <th class="text-right">VAT</th>
                                                    <td><?= $data->vat; ?></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <th colspan="4" class="border-0">&nbsp;</th>
                                                    <th class="text-right">Total</th>
                                                    <td><?= $data->total; ?></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                        <?php
                                    } else {
                                        ?>
                                        <h3>Nothing in the basket</h3>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mt-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?php
                                            echo $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true&tab=notes-tab'
                                                ]
                                            );
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				<div
                    class="tab-pane <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                    id="stats-tab"
                    role="tabpanel"
                    aria-labelledby="stats-tab">
                    
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        
                        <div class="col-6">
                            <?= $this->partial('common/logs', ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
