<?php
/**
 * Orders widget.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 */
?>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header mb-2">
				<span class="card-title">Orders</span>
            </div>
            <div class="card-body p-3 pt-0">
            </div>
        </div>
    </div>
</div>