<?php
/**
 * Media template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$controller = new FormController();
if (empty($image)) {
    $image = new stdClass();
    $image->id = null;
    $image->url = '';
    $image->label = '';
    $image->thumb_url = '';
    $image->name = '';
    $image->tags = [];
}
if (empty($image->id)) {
    echo '<div id="tile-template" class="template">';
}
?>
<div class="tile-item">
    <div class="card p-2" style="margin-bottom: 6px !important;">
        <div class="card-body pb-0">
            <div class="row m-0">
                <div class="col-12 card-header">
                    <?php
                    if ($delete) {
                        ?>
                        <button
                            class="btn btn-blank m-0 p-0 float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend('/files/delete/' . $image->id); ?>?from=<?= urlencode($url . '?tab=media-tab'); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Throw the file into the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </div>
                        </button>
                        <?php
                    }
                    ?>
                    <span
                        class="float-right btn btn-blank p-0 mr-2 clipboard-copy"
                        data-clipboard="<?= $image->url; ?>"
                        data-toggle="tooltip"
                        data-dismiss="hover"
                        data-placement="top"
                        title="Copy to clipboard">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                        </svg>
                    </span>
                </div>
                <div class="col-12 p-0">
                    <img class="media-img" src="<?= $image->thumb_url; ?>" alt="<?= $image->name; ?>">
                </div>
                <div class="col-12 p-0">
                    <div class="form-group mt-3 mb-4">
                        <a
                            href="#"
                            title="Label used to describe the image on the front end"
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            data-label="<?= $image->label; ?>"
                            data-tags="<?= $controller->tagsToString($image->tags); ?>" 
                            data-id="<?= $image->id; ?>" 
                            class="btn-edit-media-label">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>&nbsp;&nbsp;&nbsp;<span class="media-label"><?= $image->label; ?></span>
                        </a>
                    </div>
                </div>
                <div id="tag-template" class="template">
                    <span class="float-left badge badge-primary mr-2 mt-2">&nbsp;</span>
                </div>
                <div class="media-tags col-12 p-0 mb-4">
                <?php
                if (!empty($image->tags)) {
                    foreach ($image->tags as $tag) {
                        ?>
                        <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                        <?php
                    }
                }
                ?>
                </div>
            </div>
            <?php
            if ($selects) {
                ?>
                <div class="row m-0">
                    <div class="col-4 p-0 pb-3">
                        <div class="radio switcher">
                            <label>Banner</label>
                            <div class="checkbox switcher mt-2">
                                <label
                                    title="Set to be the banner image"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <input
                                        type="radio"
                                        name="banner_image"
                                        value="<?= $image->id; ?>"
                                        <?= $image->id == $data->banner_image_id ? ' checked="checked"' : ''; ?>>
                                    <span>
                                        <small class="switcher-on">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                            </svg>
                                        </small>
                                        <small class="switcher-off">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                            </svg>
                                        </small>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 p-0 pb-3">
                        <div class="radio switcher">
                            <label>Cover</label>
                            <div class="checkbox switcher mt-2">
                                <label
                                    title="Set to be the cover image"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <input
                                        type="radio"
                                        name="cover_image"
                                        value="<?= $image->id; ?>"
                                        <?= $image->id == $data->cover_image_id ? ' checked="checked"' : ''; ?>>
                                    <span>
                                        <small class="switcher-on">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                            </svg>
                                        </small>
                                        <small class="switcher-off">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                            </svg>
                                        </small>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
</div>
<?php
if (empty($image->id)) {
    echo '</div>';
}