<?php
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$controller = new FormController();

if (empty($images)) {
	return;
}

$limits = [30,100,250];
$limit = !empty($images->limit) ? intval($images->limit) : 30;
if (!empty($_GET['limit']) && in_array(intval($_GET['limit']), $limits)) {
    $limit = intval($_GET['limit']);
}

$start = intval($images->current / 5) * 5;
if ($start <= 0) {
    $start = 1;
}

$result_start = (($start - 1) * $limit) + 1;

$end = $start + 4;
$result_end = (($end - 1) * $limit) + 1;

if ($end > $images->last) {
    $end = $images->last;
    $result_end = $images->total_items;
}

if ($result_end == 0) {
	$result_start = 0;
}
?>
<div id="tiles">
<?php
if ($selects) {
    ?>
    <div class="tile-item">
        <div class="card p-2" style="margin-bottom: 6px !important;">
            <div class="card-body pb-0">
                <div class="row m-0">
                    <div class="col-12 p-0 pb-3">
                        <p class="pt-3">Set no image</p>
                    </div>
                </div>
                <div class="row m-0">
                    <div class="col-4 p-0 pb-3">
                        <div class="radio switcher">
                            <label>Banner</label>
                            <div class="checkbox switcher mt-2">
                                <label
                                    title="Remove the banner image"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <input type="radio" name="banner_image" value="">
                                    <span>
                                        <small class="switcher-on">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                            </svg>
                                        </small>
                                        <small class="switcher-off">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                            </svg>
                                        </small>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 p-0 pb-3">
                        <div class="radio switcher">
                            <label>Cover</label>
                            <div class="checkbox switcher mt-2">
                                <label
                                    title="Remove the cover image"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <input type="radio" name="cover_image" value="">
                                    <span>
                                        <small class="switcher-on">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                            </svg>
                                        </small>
                                        <small class="switcher-off">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                            </svg>
                                        </small>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 p-0 pb-3">
                        <div class="form-check switcher m-0">
                            <label>Carousel</label>
                            <div class="checkbox switcher mt-2">
                                <label
                                    title="Remove from the carousel"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <input type="checkbox" name="carousel_image[]" value="">
                                    <span>
                                        <small class="switcher-on">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                            </svg>
                                        </small>
                                        <small class="switcher-off">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                            </svg>
                                        </small>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
foreach ($images->getItems() as $image) {
    ?>
    <div class="tile-item">
        <div class="card p-2" style="margin-bottom: 6px !important;">
            <div class="card-body pb-0">
                <div class="row m-0">
                    <div class="col-12 card-header">
                        <?php
                        if ($delete) {
                            ?>
                            <button
                                class="btn btn-blank m-0 p-0 float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend('/files/delete/' . $image->id); ?>?from=<?= urlencode($url . '?tab=media-tab'); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Throw the file into the trash">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </div>
                            </button>
                            <?php
                        }
                        ?>
                        <span
                            class="float-right btn btn-blank p-0 mr-2 clipboard-copy"
                            data-clipboard="<?= $image->url; ?>"
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Copy to clipboard">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                            </svg>
                        </span>
                    </div>
                    <div class="col-12 p-0">
                        <img src="<?= $image->thumb_url; ?>" alt="<?= $image->name; ?>">
                    </div>
                    <div class="col-12 p-0">
                        <div class="form-group mt-3 mb-4">
                            <a
                                href="#"
                                title="Label used to describe the image on the front end"
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                data-label="<?= $image->label; ?>"
                                data-tags="<?= $controller->tagsToString($image->tags); ?>" 
                                data-id="<?= $image->id; ?>" 
                                class="btn-edit-media-label">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>&nbsp;&nbsp;&nbsp;<?= $image->label; ?>
                            </a>
                        </div>
                    </div>
                    <?php
                    if (!empty($image->tags)) {
                        ?>
                        <div class="col-12 p-0 mb-4">
                        <?php
                        foreach ($image->tags as $tag) {
                            ?>
                            <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                            <?php
                        }
                        ?>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <?php
                if ($selects) {
                    ?>
                    <div class="row m-0">
                        <div class="col-4 p-0 pb-3">
                            <div class="radio switcher">
                                <label>Banner</label>
                                <div class="checkbox switcher mt-2">
                                    <label
                                        title="Set to be the banner image"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="bottom">
                                        <input
                                            type="radio"
                                            name="banner_image"
                                            value="<?= $image->id; ?>"
                                            <?= $image->id == $data->banner_image_id ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-4 p-0 pb-3">
                            <div class="radio switcher">
                                <label>Cover</label>
                                <div class="checkbox switcher mt-2">
                                    <label
                                        title="Set to be the cover image"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="bottom">
                                        <input
                                            type="radio"
                                            name="cover_image"
                                            value="<?= $image->id; ?>"
                                            <?= $image->id == $data->cover_image_id ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-4 p-0 pb-3">
                            <div class="form-check switcher m-0">
                                <label>Carousel</label>
                                <div class="checkbox switcher mt-2">
                                    <label
                                        title="Add to be the carousel"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="bottom">
                                        <input
                                            type="checkbox"
                                            name="carousel_image[]"
                                            value="<?= $image->id; ?>"
                                            <?= $data->inCarousel($image->id) ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
    <?php
}
?>
</div>
<?php
if ($result_start) {
    ?>
    <div class="row">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <div class="row mt-2 mb-2">
                        <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
                            <div>
                                Showing <?= $result_start; ?> to <?= $result_end; ?> of <?= $images->total_items; ?> entries
                            </div>
                        </div>
                        <?php
                        if ($result_start) {
                            ?>
                            <div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end">
                                <div class="d-flex mr-2">
                                    <select id="media-page-limit" name="per_page" class="form-control form-control-solid">
                                    <?php
                                    foreach ($limits as $value) {
                                        ?>
                                        <option value="<?= $value; ?>" <?= $limit == $value ? 'selected' :''; ?>>
                                            <?= $value; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                    </select>
                                </div>
                                <div class="d-flex">
                                    <ul class="pagination">
                                        <li 
                                            class="media-page-item previous <?= $images->current == $images->first ? ' disabled' : ''; ?>"
                                            data-id="<?= $data->id; ?>"
                                            data-page="<?= $images->current - 1 > $images->first ? $images->current - 1 : $images->first; ?>">
                                            <span class="page-link">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                                                </svg>
                                            </span>
                                        </li>
                                        <?php
                                        for ($iLoop = $start; $iLoop <= $end; $iLoop++) {
                                            ?>
                                            <li
                                                class="media-page-item <?= $images->current == $iLoop ? 'active' :''; ?><?= $start == $end ? ' disabled text-muted' : ''; ?>"
                                                data-id="<?= $data->id; ?>"
                                                data-page="<?= $iloop; ?>">
                                                <span class="page-link"><?= $iLoop; ?></span>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                        <li 
                                            class="media-page-item next <?= $images->current == $images->last ? ' disabled text-muted' : ''; ?>"
                                            data-id="<?= $data->id; ?>"
                                            data-page="<?= $images->current + 1 < $images->last ? $images->current + 1 : $images->last; ?>">
                                            <span class="page-link">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>