<?php
/**
 * Media template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$images = (new FormController())->getImages();

if (!isset($selects)) {
	$selects = true;
}

if (!isset($upload)) {
	$upload = true;
}

if (!isset($delete)) {
	$delete = true;
}

$start = 1;
$end = intval($images->total_items / 30);
if ($images->total_items % 30) {
	$end++;
}

if ($upload) {
	?>
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header mb-2">
					<span class="card-title">Upload image</span>
				</div>
				<div class="card-body">
					<div class="form-group mb-4">
						<label>Image</label>
						<input
							name="image"
							type="file"
							accept="image/*;capture=camera"
							class="form-control form-control-file mt-2"
							aria-describedby="image">
					</div>
					<div class="form-group mb-4">
						<label for="image_label">Label</label>
						<input
							id="image_label"
							name="image_label"
							type="text"
							class="form-control mt-2"
							aria-describedby="image_label">
						<small>If you'd like to label the image to help easily identify it</small>
					</div>
					<div class="form-group mb-4">
						<label for="image_tags">Tags</label>
						<input
							id="image_tags"
							name="image_tags"
							type="text"
							class="tags mt-2"
							aria-describedby="image_tags">
						<small>If you'd like to tag the file</small>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php
}
?>
<div class="row">
	<div class="col-12 mt-4 mb-4">
		<div class="template">';
    		<span id="template-banner-id"><?= $data->banner_image_id; ?></span>
    		<span id="template-cover-id"><?= $data->cover_image_id; ?></span>
		</div>
		<div id="media-widget" class="tiles">
			<?php
			if ($selects) {
				?>
				<div class="tile-item">
					<div class="card p-2" style="margin-bottom: 6px !important;">
						<div class="card-body pb-0">
							<div class="row m-0">
								<div class="col-12 p-0 pb-3">
									<p class="pt-3">Set no image</p>
								</div>
							</div>
							<div class="row m-0">
								<div class="col-4 p-0 pb-3">
									<div class="radio switcher">
										<label>Banner</label>
										<div class="checkbox switcher mt-2">
											<label
												title="Remove the banner image"
												data-toggle="tooltip"
												data-trigger="hover"
												data-dismiss="click"
												data-placement="bottom">
												<input type="radio" name="banner_image" value="">
												<span>
													<small class="switcher-on">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
														</svg>
													</small>
													<small class="switcher-off">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
														</svg>
													</small>
												</span>
											</label>
										</div>
									</div>
								</div>
								<div class="col-4 p-0 pb-3">
									<div class="radio switcher">
										<label>Cover</label>
										<div class="checkbox switcher mt-2">
											<label
												title="Remove the cover image"
												data-toggle="tooltip"
												data-trigger="hover"
												data-dismiss="click"
												data-placement="bottom">
												<input type="radio" name="cover_image" value="">
												<span>
													<small class="switcher-on">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
														</svg>
													</small>
													<small class="switcher-off">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
														</svg>
													</small>
												</span>
											</label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php
				echo $this->partial(
					'common/files/tile',
					[
						'delete' => $delete,
						'selects' => $selects,
						'image' => null
					]
				);
			}
			?>
			<div id="media-tiles-available">
				<?php
				$banner_id = null;
				if ($data->banner_image) {
					$banner_id = $data->banner_image->id;
				}

				$cover_id = null;
				if ($data->cover_image) {
					$cover_id = $data->cover_image->id;
				}
				
				if ($banner_id && $cover_id && $banner_id == $cover_id) {
					echo $this->partial(
						'common/files/tile',
						[
							'delete' => $delete,
							'selects' => $selects,
							'image' => $data->banner_image
						]
					);
				} else {
					if ($banner_id) {
						echo $this->partial(
							'common/files/tile',
							[
								'delete' => $delete,
								'selects' => $selects,
								'image' => $data->banner_image
							]
						);
					}
					if ($cover_id) {
						echo $this->partial(
							'common/files/tile',
							[
								'delete' => $delete,
								'selects' => $selects,
								'image' => $data->cover_image
							]
						);
					}
				}
				if ($images->total_items) {
					foreach ($images->getItems() as $image) {
						if ($banner_id != $image->id && $cover_id != $image->id) {
							echo $this->partial('common/files/tile');
						}
					}
				} else {
					?>
					<div class="card">
						<div class="card-body p-3 pt-0">
							<strong class="h5">No results</strong>
						</div>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
</div>
<?php
if ($start) {
    ?>
    <div class="row">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <div class="row mt-2 mb-2">
                        <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
                            &nbsp;
                        </div>
						<div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end">
							<div class="d-flex">
								<ul id="media-pagination" class="pagination">
									<?php
									for ($iLoop = $start; $iLoop <= $end; $iLoop++) {
										?>
										<li
											class="media-page-item <?= $images->current == $iLoop ? 'active' :''; ?><?= $start == $end ? ' disabled text-muted' : ''; ?>"
											data-id="<?= $data->id; ?>"
											data-page="<?= $iLoop; ?>">
											<span class="page-link"><?= $iLoop; ?></span>
										</li>
										<?php
									}
									?>
								</ul>
							</div>
						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
<div class="modal" tabindex="-1" id="modal-media-label">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit the label</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
			<div class="modal-body">
				<div class="form-group mb-4">
					Required fields <span class="required">*</span>
				</div>
				<div class="form-group mb-4">
					<label for="label" class="form-label">
						Label
						<span class="required">*</span>
					</label>
					<input
						name="media_label"
						type="text"
						class="form-control mt-2"
						value=""
						placeholder="Please enter a label"
						required/>
				</div>
				<div class="form-group mb-4">
					<label for="media_tags" class="form-label">
						Tags
					</label>
					<input
						name="media_tags"
						type="text"
						class="tags mt-2"
						value=""/>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-12 p-0 m-0">
					<button type="submit" class="btn btn-primary btn-save float-right" data-dismiss="modal">Save</button>
					<button type="button" class="btn btn-secondary float-right mr-2" data-dismiss="modal">Cancel</button>
				</div>
			</div>
			<input type="hidden" name="media_label_id" value=""/>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {
    $(".btn-edit-media-label").click(function(event) {
        $("#modal-media-label input[name=media_label]").val($(event.currentTarget).data("label"));
		$("#modal-media-label input[name=media_tags]").val($(event.currentTarget).data("tags"));
        $("#modal-media-label input[name=media_label_id]").val($(event.currentTarget).data("id"));

        $("#modal-media-label").modal("show");
    });
});
</script>
