<?php
/**
 * Media template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$images = (new FormController())->getImages();

if (!isset($selects)) {
	$selects = true;
}

if (!isset($upload)) {
	$upload = true;
}

if (!isset($delete)) {
	$delete = true;
}

if ($upload) {
	?>
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header mb-2">
					<span class="card-title">Upload image</span>
				</div>
				<div class="card-body">
					<div class="form-group mb-4">
						<label>Image</label>
						<input
							name="image"
							type="file"
							accept="image/*;capture=camera"
							class="form-control form-control-file mt-2"
							aria-describedby="image">
					</div>
					<div class="form-group mb-4">
						<label for="image_label">Label</label>
						<input
							id="image_label"
							name="image_label"
							type="text"
							class="form-control mt-2"
							aria-describedby="image_label">
						<small>If you'd like to label the image to help easily identify it</small>
					</div>
					<div class="form-group mb-4">
						<label for="image_tags">Tags</label>
						<input
							id="image_tags"
							name="image_tags"
							type="text"
							class="tags mt-2"
							aria-describedby="image_tags">
						<small>If you'd like to tag the file</small>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php
}
?>
<div class="row">
	<div class="col-12 mt-4 mb-4">
	<?php
	if ($images->total_items) {
		echo $this->partial('common/files/tiles');
	} else {
		?>
		<div class="card">
            <div class="card-body p-3 pt-0">
                <strong class="h5">No results</strong>
            </div>
        </div>
		<?php
	}
	?>
    </div>
</div>

<div class="modal" tabindex="-1" id="modal-media-label">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit the label</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
			<div class="modal-body">
				<div class="form-group mb-4">
					Required fields <span class="required">*</span>
				</div>
				<div class="form-group mb-4">
					<label for="label" class="form-label">
						Label
						<span class="required">*</span>
					</label>
					<input
						name="media_label"
						type="text"
						class="form-control mt-2"
						value=""
						placeholder="Please enter a label"
						required/>
				</div>
				<div class="form-group mb-4">
					<label for="media_tags" class="form-label">
						Tags
					</label>
					<input
						name="media_tags"
						type="text"
						class="tags mt-2"
						value=""/>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-12 p-0 m-0">
					<button type="submit" class="btn btn-primary btn-save float-right" data-dismiss="modal">Save</button>
					<button type="button" class="btn btn-secondary float-right mr-2" data-dismiss="modal">Cancel</button>
				</div>
			</div>
			<input type="hidden" name="media_label_id" value=""/>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {
    $(".btn-edit-media-label").click(function(event) {
        $("#modal-media-label input[name=media_label]").val($(event.currentTarget).data("label"));
		$("#modal-media-label input[name=media_tags]").val($(event.currentTarget).data("tags"));
        $("#modal-media-label input[name=media_label_id]").val($(event.currentTarget).data("id"));

        $("#modal-media-label").modal("show");
    });
});
</script>
