<?php
/**
 * Index template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Phoenix\Controllers\BasketController;
use Kytschi\Tengu\Controllers\Website\MenuController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
use Phalcon\Tag;

$title = Tag::getTitle();
$basket = (new BasketController())->get();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="referrer" content="origin">
		<meta name="robots" content="<?= Tag::getValue('robots'); ?>">
        <meta name="description" content="<?= Tag::getValue('meta_description'); ?>">
        <meta name="keywords" content="<?= Tag::getValue('meta_keywords'); ?>">
        <meta name="author" content="<?= Tag::getValue('meta_author'); ?>">
		<meta name="revised" content="<?= DateHelper::meta(Tag::getValue('page_updated')); ?>" />

        <title><?= (!empty($title) ? $title . ' - ' : '')  . $this->tengu->settings->name;?></title>

        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('bootstrap.min.css'); ?>">
        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('theme.css'); ?>">
        <link rel="icon" href="<?= $this->tengu->theme->getAsset('imgs/favicon.ico'); ?>" sizes="64x64">

        <link rel="canonical" href="<?= $this->tengu->canonicalUrl(); ?>">

        <script src="<?= $this->tengu->theme->getAsset('js/plugins/jquery.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/plugins/popper.min.js');?>"></script>
		<script src="<?= $this->tengu->theme->getAsset('js/plugins/bootstrap.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/app.js');?>"></script>
    </head>
    <body>
        <header class="container-fluid p-0 m-0">
            <div class="row m-0 p-0">
                <div id="header-logo" class="col-12 p-3">
                    <table class="w-100 table-borderless">
                        <tbody>
                            <tr>
                                <td id="logo" class="logo">
                                    <h1>
                                        <span><?= $this->tengu->settings->name; ?></span>
                                    </h1>
                                </td>
                                <td>
                                    <div class="container pt-2">
                                        <div class="row p-0">
                                            <nav class="col-12">
                                                <ul>
                                                    <?php
                                                    $menu = MenuController::get('main');
                                                    foreach ($menu as $item) {
                                                        $link = $item->link;
                                                        ?>
                                                        <li>
                                                            <a
                                                                href="<?= $link; ?>"
                                                                class="<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                                                                <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>>
                                                                <span><?= $item->name; ?></span>
                                                            </a>
                                                        </li>
                                                        <?php
                                                    }
                                                    ?>
                                                </ul>    
                                            </nav>
                                        </div>
                                    </div>
                                </td>
                                <td id="contact-info" class="contact-info">
                                    <a
                                        class="nav-link"
                                        href="/basket">
                                        <?php
                                        if ($basket) {
                                            if ($basket->quantity) {
                                                ?>
                                                <div class="basket-count"><?= $basket->quantity; ?></div>
                                                <?php
                                            }
                                        }
                                        ?>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </header>
        <main class="container-fluid">
            <div class="row m-0">
                <div class="col-12 p-0">
                    <?= $this->getContent(); ?>
                </div>
            </div>
        </main>
        <footer class="container-fluid p-4">
            <table class="w-100 table-borderless">
                <tbody>
                    <tr>
                        <td class="logo">
                            <img 
                                src="<?= $this->tengu->theme->getAsset('imgs/logov2.png'); ?>"
                                title="kytschi"
                                alt="kytschi"
                                width="100%"/>
                        </td>
                        <td>
                            <div class="container pt-0">
                                <div class="row p-0 m-0">
                                    <div class="col-12 pl-4">
                                        <ul>
                                            <?php
                                            $menu = MenuController::get('footer');
                                            foreach ($menu as $item) {
                                                $link = $item->link;
                                                ?>
                                                <li>
                                                    <a
                                                        href="<?= $link; ?>"
                                                        class="<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                                                        <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>>
                                                        <span><?= $item->name; ?></span>
                                                    </a>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td class="contact-info">
                            <p class="mobile">
                                <span class="required">e</span> <a href="mailto:<?= $this->tengu->settings->contact_email; ?>"><?= $this->tengu->settings->contact_email; ?></a>
                            </p>
                            <p>
                                Company no. 12626204. Registered in England &amp; Wales
                            </p>
                            <p>
                                <small>
                                    &copy;<?= date('Y'); ?> Kytschi. Powered by Tengu
                                    <br/>Made in Britian
                                </small>
                            </p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </footer>
	</body>
</html>
