<?php
/**
 * Page edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
?>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header mb-2">
				<span class="card-title">Info</span>
            </div>
            <div class="card-body p-3 pt-0">
                <div class="form-group mb-4">
                    <label for="code">
                        Code<span class="required">*</span>
                    </label>
                    <input
                        id="code"
                        name="code"
                        type="text"
                        class="form-control mt-2"
                        aria-describedby="code"
                        value="<?= FormController::getFormData('code', $data); ?>"
                        required>
                </div>
                <div class="form-group form-check mt-0 mb-4">
                    <label for="requires_shipping">Requires shipping</label>
                    <div class="checkbox switcher mt-2">
                        <label>
                            <input
                                id="requires_shipping"
                                type="checkbox"
                                name="requires_shipping"
                                value="1"
                                <?= FormController::getFormData('requires_shipping', (!empty($data->product) ? $data->product : null)) ? ' checked="checked"' : ''; ?>>
                            <span>
                                <small class="switcher-on">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                    </svg>
                                </small>
                                <small class="switcher-off">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                    </svg>
                                </small>
                            </span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header mb-2">
                <span class="card-title">Stock levels</span>
            </div>
            <div class="card-body p-3 pt-0">
                <div class="form-group mb-4">
                    <label for="stock">
                        Stock
                        <span class="required">*</span>
                    </label>
                    <input
                        id="stock"
                        name="stock"
                        type="text"
                        class="form-control mt-2"
                        aria-describedby="stock"
                        value="<?= FormController::getFormData('stock', $data); ?>"
                        required>
                </div>
                <div class="form-group mb-4">
                    <label for="stock">
                        Low stock
                    </label>
                    <input
                        id="low_stock"
                        name="low_stock"
                        type="text"
                        class="form-control mt-2"
                        aria-describedby="low_stock"
                        value="<?= FormController::getFormData('low_stock', $data); ?>">
                </div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header mb-2">
				<span class="card-title">Pricing</span>
            </div>
            <div class="card-body p-3 pt-0">
                <div class="form-group mb-4">
                    <label for="price">
                        Price
                        <span class="required">*</span>
                    </label>
                    <input
                        id="price"
                        name="price"
                        type="text"
                        class="form-control mt-2"
                        aria-describedby="price"
                        value="<?= FormController::getFormData('price', $data); ?>"
                        required>
                </div>
                <div class="form-group mb-4">
                    <label for="vat">
                        VAT (&#37;)
                    </label>
                    <input
                        id="vat"
                        name="vat"
                        type="text"
                        class="form-control mt-2"
                        aria-describedby="vat"
                        value="<?= FormController::getFormData('vat', $data); ?>">
                </div>
            </div>
        </div>
    </div>
</div>