<?php
/**
 * Statement edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->fms . '/statements';
$project_url = ($this->di->getConfig())->urls->pms . '/projects';
$dividend_url = ($this->di->getConfig())->urls->fms . '/dividends';
echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<div class="row mb-3">
    <?php
    if ($data->tax_year) {
        ?>
        <div class="col-3">
            <div class="card bg-info">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                    </svg>
                    <div class="h4 text-white mt-3 mb-1" style="height: 30px">
                        <?php
                            echo DateHelper::pretty($data->tax_year->tax_year_start, false) . ' to ' . DateHelper::pretty($data->tax_year->tax_year_end, false) ;
                        ?>
                    </div>
                    <div class="text-white">
                        Tax year (<?= $data->tax_year->code; ?>)
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
    ?>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v2h6a.5.5 0 0 1 .5.5c0 .253.08.644.306.958.207.288.557.542 1.194.542.637 0 .987-.254 1.194-.542.226-.314.306-.705.306-.958a.5.5 0 0 1 .5-.5h6v-2A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M16 6.5h-5.551a2.678 2.678 0 0 1-.443 1.042C9.613 8.088 8.963 8.5 8 8.5c-.963 0-1.613-.412-2.006-.958A2.679 2.679 0 0 1 5.551 6.5H0v6A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-6z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <?= NumberHelper::toCurrency($data->in, $data->currency); ?>
				</div>
                <div class="text-white">
					Incoming
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499L12.136.326zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484L5.562 3zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
					<?= NumberHelper::toCurrency($data->out, $data->currency); ?>
				</div>
                <div class="text-white">
					Outgoing
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card p-0">
            <div class="card-body">
                <a
                    href="<?= UrlHelper::generate(UrlHelper::backend($url)); ?>"
                    class="btn btn-blank mr-2 text-center"
                    title="Go back to the statements list"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                        <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                    </svg><br/>
                    back
                </a>
                <button
                    id="btn-save"
                    class="btn btn-blank float-right"
                    type="button"
                    title="Save the statement"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg><br/>
                    save
                </button>
                <a
                    href="<?= UrlHelper::backend($url . '/add'); ?>"
                    class="btn btn-blank float-right"
                    title="Add a new statement"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                    </svg><br/>
                    new
                </a>
                <?php
                if (!empty($data->file)) {
                    ?>
                    <a
                        href="<?= UrlHelper::backend($data->file->download_url); ?>"
                        class="btn btn-blank float-right"
                        title="Download the attached file"
                        target="_blank"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                        </svg><br/>
                        download
                    </a>
                    <?php
                }
                if ($data->status == 'deleted') {
                    ?>
                    <button
                        class="btn btn-blank float-right"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Recover the statement from the trash">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                            </svg><br/>
                            recover
                        </div>
                    </button>
                    <?php
                } else {
                ?>
                    <button
                        class="btn btn-blank float-right"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Throw the statement into the trash">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg><br/>
                            delete
                        </div>
                    </button>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
<form
    id="form-edit"
    method="post"
    action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>"
    enctype="multipart/form-data">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <?php
                            switch ($data->status) {
                                case 'active':
                                    $label = "I'm live!";
                                    $bg_colour = 'bg-success';
                                    break;
                                case 'inactive':
                                    $label = "I'm inactive";
                                    $bg_colour = 'bg-warning';
                                    break;
                                case 'deleted':
                                    $label = "I'm in a deleted state";
                                    $bg_colour = 'bg-danger';
                                    break;
                                default:
                                    break;
                            }
                            ?>
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="name">
                                    Label
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="in">
									In (<?= NumberHelper::currencySymbol(); ?>)
								</label>
                                <input
                                    id="in"
                                    name="in"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="in"
                                    value="<?= FormController::getFormData('in', $data); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="out">
									Out (<?= NumberHelper::currencySymbol(); ?>)
								</label>
                                <input
                                    id="out"
                                    name="out"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="out"
                                    value="<?= FormController::getFormData('out', $data); ?>">
                            </div>
							<div class="form-group mb-4">
                                <label for="period_from">
                                    Period from
                                </label>
                                <input
                                    id="period_from"
                                    name="period_from"
                                    type="text"
                                    class="form-control mt-2 datepicker"
                                    aria-describedby="period_from"
                                    value="<?= DateHelper::pretty(FormController::getFormData('period_from', $data), false); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="period_to">
                                    Period to
                                </label>
                                <input
                                    id="period_to"
                                    name="period_to"
                                    type="text"
                                    class="form-control mt-2 datepicker"
                                    aria-describedby="period_to"
                                    value="<?= DateHelper::pretty(FormController::getFormData('period_to', $data), false); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="upload_statement">Upload</label>
                                <input
									id="upload_statement"
									name="upload_statement"
									type="file"
									accept="application/pdf"
									class="form-control mt-2">
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Overview
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('preview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#preview-tab">
                                Preview
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                        <div class="col-12">
                            <div class="card mb-5">
                                <div class="card-body">
                                    <a
                                        href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/add'); ?>"
                                        class="btn btn-blank float-right"
                                        title="Add a new statement item"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                                        </svg><br/>
                                        new
                                    </a>
                                    <a
                                        href="<?= UrlHelper::backend($url . '/parse/' . $data->id); ?>"
                                        class="btn btn-blank float-right"
                                        title="Refresh the list"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
                                            <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
                                        </svg><br/>
                                        re-parse
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if ($data->items->count()) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="align-bottom">Tax year</th>
                                                    <th class="align-bottom" width="160px">Processed at</th>
                                                    <th class="align-bottom">Description</th>
                                                    <th class="align-bottom" width="200px">In (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th class="align-bottom" width="200px">Out (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th class="align-bottom" width="200px">Balance (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th class="text-center align-bottom" width="120px">Taxable</th>
                                                    <th class="text-center align-bottom" width="80px">Receipt</th>
                                                    <th class="text-center align-bottom" width="80px">Invoice</th>
                                                    <th width="160px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            foreach ($data->items as $row) {
                                                ?>
                                                <tr <?= $row->deleted_at ? ' class="text-danager text-strikethrough"' : '';?>>
                                                    <td class="align-top">
                                                        <?php
                                                        if (!empty($row->tax_year)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                                                <span class="badge badge-primary">
                                                                    <?= $row->tax_year->code; ?>
                                                                </span>
                                                            </a>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <span class="badge badge-danger">
                                                                none
                                                            </span>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <?php
                                                        if ($row->processed_at) {
                                                            ?>
                                                            <span class="badge badge-warning">
                                                                <?= DateHelper::pretty($row->processed_at, false); ?>
                                                            </span>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <span class="badge badge-danger">
                                                                Unknown
                                                            </span>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <p><?= nl2br($row->description); ?></p>
                                                        <?php
                                                        if (!empty($row->tags)) {
                                                            foreach ($row->tags as $tag) {
                                                                ?>
                                                                <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                                                                <?php
                                                            }
                                                        }
                                                        if (!empty($row->shareholder)) {
                                                            ?>
                                                            <span class="float-left badge badge-info mr-2 mt-2">shareholder payment to <?= $row->shareholder->full_name; ?></span>
                                                            <?php                                                            
                                                        }
                                                        if (!empty($row->employee)) {
                                                            ?>
                                                            <span class="float-left badge badge-info mr-2 mt-2">employee payment to <?= $row->employee->full_name; ?></span>                                                            
                                                            <?php                                                            
                                                        }
                                                        if (!empty($row->project)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend($project_url . '/edit/' . $row->project->id); ?>" class="float-left badge badge-info mr-2 mt-2">Project: <?= $row->project->name; ?></a>
                                                            <?php
                                                        }
                                                        if (!empty($row->dividend)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend($dividend_url . '/edit/' . $row->dividend->id); ?>" class="float-left badge badge-info mr-2 mt-2">Dividend issued</a>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <span class="badge badge-success">
                                                            <?= NumberHelper::toCurrency($row->in); ?>
                                                        </span>
                                                    </td>
                                                    <td class="align-top">
                                                        <span class="badge badge-danger">
                                                            <?= NumberHelper::toCurrency($row->out); ?>
                                                        </span>
                                                    </td>
                                                    <td class="align-top">
                                                        <span class="badge badge-primary">
                                                            <?= NumberHelper::toCurrency($row->balance); ?>
                                                        </span>
                                                    </td>
                                                    <td class="align-top text-center">
                                                        <div class="form-group form-check mt-0 mb-4">
                                                            <div class="checkbox switcher">
                                                                <label>
                                                                    <input
                                                                        type="checkbox"
                                                                        name="taxable[<?= $row->id; ?>]"
                                                                        value="1"
                                                                        <?= FormController::getFormData('taxable', $row) ? ' checked="checked"' : ''; ?>>
                                                                    <span>
                                                                        <small class="switcher-on">
                                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                            </svg>
                                                                        </small>
                                                                        <small class="switcher-off">
                                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                            </svg>
                                                                        </small>
                                                                    </span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td class="align-top text-center">
                                                        <span class="badge badge-<?= $row->receipts->count() ? 'success' : 'danger'; ?>">
                                                            <?= $row->receipts->count() ? 'Yes' : 'No'; ?>
                                                        </span>
                                                    </td>
                                                    <td class="align-top text-center">
                                                        <span class="badge badge-<?= $row->invoices->count() ? 'success' : 'danger'; ?>">
                                                            <?= $row->invoices->count() ? 'Yes' : 'No'; ?>
                                                        </span>
                                                    </td>
                                                    <td class="align-top">
                                                        <a
                                                            href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/edit/' . $row->id); ?>"
                                                            class="btn btn-blank float-right"
                                                            title="Edit the item"
                                                            data-toggle="tooltip"
                                                            data-trigger="hover"
                                                            data-dismiss="click"
                                                            data-placement="top">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                            </svg>
                                                        </a>
                                                        <?php
                                                        if (!$row->deleted_at) {
                                                            ?>
                                                            <button
                                                                type="button"
                                                                class="btn btn-blank float-right"
                                                                data-original-title="Are you sure?"
                                                                data-trigger="focus"
                                                                data-html="true"
                                                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/delete/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id); ?>">Yes</a>'
                                                                data-toggle="popover">
                                                                <span
                                                                    title="Delete the item"
                                                                    data-toggle="tooltip"
                                                                    data-trigger="hover"
                                                                    data-dismiss="click"
                                                                    data-placement="top">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                                    </svg>
                                                                </span>
                                                            </button>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <button
                                                                type="button"
                                                                class="btn btn-blank float-right"
                                                                data-original-title="Are you sure?"
                                                                data-trigger="focus"
                                                                data-html="true"
                                                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/recover/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id); ?>">Yes</a>'
                                                                data-toggle="popover">
                                                                <span
                                                                    title="Recover the item"
                                                                    data-toggle="tooltip"
                                                                    data-trigger="hover"
                                                                    data-dismiss="click"
                                                                    data-placement="top">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                                                    </svg>
                                                                </span>
                                                            </button>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                            <?php
                                    } else {
                                        ?>
                                        <strong class="h4">No items</strong>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('preview-tab', 'overview-tab'); ?>"
                    id="preview-tab"
                    role="tabpanel"
                    aria-labelledby="preview-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if (!empty($data->file)) {
                                        switch ($data->file->mime_type) {
                                            case 'application/pdf':
                                                ?>
                                                <div class="pdf-render"
                                                    data-url="<?= UrlHelper::backend($data->file->output_url); ?>"></div>
                                                <?php
                                                break;
                                            default:
                                            ?>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <span class="h4">Nothing to preview</span>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?= $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true#notes-tab'
                                                ]
                                            ); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                        <?php
                        if (!empty($data->file)) {
                            ?>
                            <div class="col-6">
                                <?= $this->partial(
                                    'common/logs',
                                    [
                                        'data' => $data->file->download_history,
                                        'label' => 'Download history'
                                    ]
                                ); ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>