<?php
/**
 * Statements index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->fms . '/statements';

$filter_status = $this->tengu->getFilters('status');
$filter_year = $this->tengu->getFilters('year');
$filter_taxable = $this->tengu->getFilters('taxable');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1" style="height: 30px">
                    <?php
                        echo DateHelper::pretty($tax_year->tax_year_start, false) . ' to ' . DateHelper::pretty($tax_year->tax_year_end, false);
                    ?>
                </div>
                <div class="text-white">
                    Tax year (<?= $tax_year->code; ?>)
                </div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v2h6a.5.5 0 0 1 .5.5c0 .253.08.644.306.958.207.288.557.542 1.194.542.637 0 .987-.254 1.194-.542.226-.314.306-.705.306-.958a.5.5 0 0 1 .5-.5h6v-2A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M16 6.5h-5.551a2.678 2.678 0 0 1-.443 1.042C9.613 8.088 8.963 8.5 8 8.5c-.963 0-1.613-.412-2.006-.958A2.679 2.679 0 0 1 5.551 6.5H0v6A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-6z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['incoming']); ?>
				</div>
                <div class="text-white">
					Incoming
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499L12.136.326zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484L5.562 3zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['outgoing']); ?>
				</div>
                <div class="text-white">
					Outgoing
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
        <div class="card p-0">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
				<a href="<?= UrlHelper::backend($url . '/add'); ?>" class="btn btn-primary float-right">
		            Add
		        </a>
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
                            <?php
                                $this->partial('common/lists/sorting', ['url' => $url]);
                            ?>
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
		                        <option value="active"<?= $filter_status == 'active' ? ' selected="selected"' : ''; ?>>Active</option>
		                        <option value="deleted"<?= $filter_status == 'deleted' ? ' selected="selected"' : ''; ?>>Deleted</option>
		                    </select>
                            <label class="form-label fw-bold">Tax year:</label>
		                    <select
		                        name="filters[year]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($years as $year) {
                                    ?>
                                    <option value="<?= $year->id; ?>"<?= $filter_year == $year->id ? ' selected="selected"' : ''; ?>>
                                        <?= $year->code; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
                            <label class="form-label fw-bold">Taxable:</label>
		                    <select
		                        name="filters[taxable]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <option value="yes"<?= $filter_taxable == 'yes' ? ' selected="selected"' : ''; ?>>yes</option>
                                <option value="no"<?= $filter_taxable == 'no' ? ' selected="selected"' : ''; ?>>no</option>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>				
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body p-3">
            <?php
            if (empty($_GET['search'])) {
                if ($data->total_items) {
                    ?>
                    <table class="table tablesorter">
                        <thead>
                            <tr>
                                <th>Tax year</th>
                                <th>Name</th>
                                <th width="150px">In</th>
                                <th width="150px">Out</th>
                                <th width="150px">Period from</th>
                                <th width="150px">Period to</th>
                                <th width="130px" class="text-center">Taxable</th>
                                <th width="250px">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($data->getItems() as $row) {
                                switch ($row->status) {
                                    case 'active':
                                        $bg_colour = 'badge-success';
                                        break;
                                    case 'inactive':
                                        $bg_colour = 'badge-warning';
                                        break;
                                    case 'deleted':
                                        $bg_colour = 'badge-danger';
                                        break;
                                    default:
                                        break;
                                }
                                ?>
                                <tr>
                                    <td class="align-top">
                                        <?php
                                        if (!empty($row->tax_year)) {
                                            ?>
                                            <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                                <span class="badge badge-primary">
                                                    <?= $row->tax_year->code; ?>
                                                </span>
                                            </a>
                                            <?php
                                        } else {
                                            ?>
                                            <span class="badge badge-danger">
                                                none
                                            </span>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                    <td class="align-top">
                                        <a class="float-left w-100" href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <?= $row->name; ?>
                                        </a>
                                        <?php
                                        if ($row->tags->count()) {
                                            foreach ($row->tags as $tag) {
                                            ?>
                                            <a href="<?= UrlHelper::backend($url . '?search=' . $tag->tag); ?>" class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></a>
                                            <?php
                                            }
                                        }
                                        ?>
                                    </td>
                                    <td class="align-top">
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge badge-success">
                                                <?= NumberHelper::toCurrency($row->in); ?>
                                            </span>
                                        </a>
                                    </td>
                                    <td class="align-top">
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge badge-danger">
                                                <?= NumberHelper::toCurrency($row->out); ?>
                                            </span>
                                        </a>
                                    </td>
                                    <td class="align-top">
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge badge-warning">
                                                <?= DateHelper::pretty($row->period_from, false); ?>
                                            </span>
                                        </a>
                                    </td>
                                    <td class="align-top">
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge badge-warning">
                                                <?= DateHelper::pretty($row->period_to, false); ?>
                                            </span>
                                        </a>
                                    </td>
                                    <td class="align-top text-center">
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge <?= $row->taxable ? 'badge-success' : 'badge-danger'; ?>">
                                                <?= StringHelper::toYesNo($row->taxable); ?>
                                            </span>
                                        </a>
                                    </td>
                                    <td class="align-top">
                                        <a
                                            href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
                                            class="btn btn-blank float-right"
                                            title="Edit the statement"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                            </svg>
                                        </a>
                                        <?php
                                        if (!empty($row->file)) {
                                            ?>
                                            <a
                                                href="<?= UrlHelper::backend($row->file->download_url); ?>"
                                                class="btn btn-blank float-right"
                                                title="Download the file"
                                                target="_blank"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                                                </svg>
                                            </a>
                                            <?php
                                        }
                                        if (!$row->deleted_at) {
                                            ?>
                                            <button
                                                type="button"
                                                class="btn btn-blank float-right"
                                                data-original-title="Are you sure?"
                                                data-trigger="focus"
                                                data-html="true"
                                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                                data-toggle="popover">
                                                <span
                                                    title="Delete the statement"
                                                    data-toggle="tooltip"
                                                    data-trigger="hover"
                                                    data-dismiss="click"
                                                    data-placement="top">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </span>
                                            </button>
                                            <?php
                                        } else {
                                            ?>
                                            <button
                                                type="button"
                                                class="btn btn-blank float-right"
                                                data-original-title="Are you sure?"
                                                data-trigger="focus"
                                                data-html="true"
                                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                                data-toggle="popover">
                                                <span
                                                    title="Recover the statement"
                                                    data-toggle="tooltip"
                                                    data-trigger="hover"
                                                    data-dismiss="click"
                                                    data-placement="top">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                                    </svg>
                                                </span>
                                            </button>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                    <?php
                }  else {
                    ?>
                    <strong class="h5">No results</strong>
                    <?php
                }
            } else {
                ?>
                <?php
                if ($data->total_items) {
                    ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="160px">Processed at</th>
                                <th>Description</th>
                                <th width="200px">In (<?= NumberHelper::currencySymbol(); ?>)</th>
                                <th width="200px">Out (<?= NumberHelper::currencySymbol(); ?>)</th>
                                <th width="200px">Balance (<?= NumberHelper::currencySymbol(); ?>)</th>
                                <th class="text-center" width="120px">Taxable</th>
                                <th class="text-center" width="80px">Receipt</th>
                                <th class="text-center" width="80px">Invoice</th>
                                <th width="160px">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        $statement_id = null;
                        foreach ($data->getItems() as $row) {
                            if ($statement_id != $row->statement_id) {
                                $statement_id = $row->statement_id;
                                ?>
                                <tr>
                                    <td class='row-header' colspan="8">
                                        <strong><?= $row->statement->name; ?></strong>
                                    </td>
                                    <td class='row-header' width="160px">
                                        <a
                                            href="<?= UrlHelper::from($url . '/edit/' . $row->statement_id); ?>"
                                            class="btn btn-blank float-right"
                                            title="Edit the statement"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                            </svg>
                                        </a>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                            <tr <?= $row->deleted_at ? ' class="text-danager text-strikethrough"' : '';?>>
                                <td class="align-top">
                                    <span class="badge badge-warning">
                                        <?= DateHelper::pretty($row->processed_at, false); ?>
                                    </span>
                                </td>
                                <td class="align-top">
                                    <p><?= nl2br($row->description); ?></p>
                                    <?php
                                    if (!empty($row->tags)) {
                                        foreach ($row->tags as $tag) {
                                            ?>
                                            <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                                            <?php
                                        }
                                    }
                                    if (!empty($row->shareholder)) {
                                        ?>
                                        <span class="float-left badge badge-info mr-2 mt-2">shareholder payment to <?= $row->shareholder->full_name; ?></span>
                                        <?php                                                            
                                    }
                                    if (!empty($row->employee)) {
                                        ?>
                                        <span class="float-left badge badge-info mr-2 mt-2">employee payment to <?= $row->employee->full_name; ?></span>                                                            
                                        <?php                                                            
                                    }
                                    if (!empty($row->project)) {
                                        ?>
                                        <a href="<?= UrlHelper::backend($project_url . '/edit/' . $row->project->id); ?>" class="float-left badge badge-info mr-2 mt-2">Project: <?= $row->project->name; ?></a>
                                        <?php
                                    }
                                    ?>
                                </td>
                                <td class="align-top"><?= NumberHelper::toCurrency($row->in); ?></td>
                                <td class="align-top"><?= NumberHelper::toCurrency($row->out); ?></td>
                                <td class="align-top"><?= NumberHelper::toCurrency($row->balance); ?></td>
                                <td class="align-top text-center">
                                    <div class="form-group form-check mt-0 mb-4">
                                        <div class="checkbox switcher">
                                            <label>
                                                <input
                                                    type="checkbox"
                                                    name="taxable[<?= $row->id; ?>]"
                                                    value="1"
                                                    <?= FormController::getFormData('taxable', $row) ? ' checked="checked"' : ''; ?>>
                                                <span>
                                                    <small class="switcher-on">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                        </svg>
                                                    </small>
                                                    <small class="switcher-off">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                        </svg>
                                                    </small>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-top text-center">
                                    <span class="badge badge-<?= !empty($row->receipt) ? 'success' : 'danger'; ?>">
                                        <?= !empty($row->receipt) ? 'Yes' : 'No'; ?>
                                    </span>
                                </td>
                                <td class="align-top text-center">
                                    <span class="badge badge-<?= !empty($row->invoice) ? 'success' : 'danger'; ?>">
                                        <?= !empty($row->invoice) ? 'Yes' : 'No'; ?>
                                    </span>
                                </td>
                                <td class="align-top">
                                    <a
                                        href="<?= UrlHelper::backend($url . '/' . $row->statement_id . '/items/edit/' . $row->id); ?>"
                                        class="btn btn-blank float-right"
                                        title="Edit the item"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                        </svg>
                                    </a>
                                    <?php
                                    if (!$row->deleted_at) {
                                        ?>
                                        <button
                                            type="button"
                                            class="btn btn-blank float-right"
                                            data-original-title="Are you sure?"
                                            data-trigger="focus"
                                            data-html="true"
                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/delete/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id); ?>">Yes</a>'
                                            data-toggle="popover">
                                            <span
                                                title="Delete the item"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                            </span>
                                        </button>
                                        <?php
                                    } else {
                                        ?>
                                        <button
                                            type="button"
                                            class="btn btn-blank float-right"
                                            data-original-title="Are you sure?"
                                            data-trigger="focus"
                                            data-html="true"
                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/' . $data->id . '/items/recover/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id); ?>">Yes</a>'
                                            data-toggle="popover">
                                            <span
                                                title="Recover the item"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                                </svg>
                                            </span>
                                        </button>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                        <?php
                } else {
                    ?>
                    <strong class="h4">No results</strong>
                    <?php
                }
                ?>
                <?php
            }
            ?>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
