<?php
/**
 * Spinner add template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

switch ($page_type) {
	case 'blog-posts':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts';
		$parent = 'Blog posts';
		$child = 'Blog post';
		break;
    case 'blog-post-category':
        $url = ($this->di->getConfig())->urls->cms . '/blog-posts/categories/';
        $parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/categories';
        $parent = 'Blog post categories';
        $child = 'Blog post category';
        break;
	case 'portfolio':
		$url = ($this->di->getConfig())->urls->cms . '/portfolio/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/portfolio';
		$parent = 'Portfolio';
		$child = 'Portfolio piece';
		break;
    default:
        $url = ($this->di->getConfig())->urls->cms . '/pages/';
        $parentUrl = ($this->di->getConfig())->urls->cms . '/pages';
        $parent = 'Pages';
        $child = 'Page';
        break;
}

$url .= $page_id . '/spinner';

echo $this->partial("common/form/messages");
echo $this->partial("makabe/spinner/shared");
?>
<link href="<?= $this->tengu->theme->getCSS('plugins/summernote/summernote-bs4.min.css');?>" rel="stylesheet">
<script src="<?= $this->tengu->theme->getAsset('plugins/summernote/summernote-bs4.min.js');?>"></script>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js');?>"></script>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js');?>"></script>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/save'); ?>">
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <a
                        href="<?= UrlHelper::backend($url); ?>"
                        class="btn btn-blank mr-2 text-center"
                        title="Go back"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                        </svg><br/>
                        back
                    </a>
                    <button
                        id="btn-save"
                        class="btn btn-blank float-right"
                        type="button"
                        title="Save the spin content"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
                        save
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div
								class="preview-img"
								title="I'm inactive"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="bottom">
	                            <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/new-item.png'); ?>" 
                                        alt="Add an entry">
								</div>
	                            <div class="circle border border-white bg-warning"></div>
							</div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="label">
									Label <span class="required">*</span>
								</label>
                                <input
                                    id="label"
                                    name="label"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="label"
                                    value="<?= FormController::getFormData('label'); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="campaign_id">SEO Campaign</label>
                                <select
                                    name="campaign_id"
                                    class="form-control mt-2">
                                    <?php
                                    $selected = FormController::getFormData('campaign_id');
                                        ?>
                                        <option value="">No campaign</option>
                                        <?php
                                    foreach ($campaigns as $campaign) {
                                        ?>
                                        <option
                                            value="<?= $campaign->id; ?>"
                                            <?= $selected == $campaign->id ? ' selected' : ''; ?>><?= $campaign->name; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Content <span class="required">*</span>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('media-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#media-tab">
                                Media
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">
                                        Content for spinning <span class="required">*</span>
                                    </span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <table class="table table-borderless">
                                        <tr>
                                            <td class="p-0 border-0 pr-3">
                                                <div class="form-group pb-4">
                                                    <?= $this->partial('website/pages/sections/content', ['full' => false]); ?>
                                                </div>
                                                <div class="form-group pb-4">
                                                    <label for="name">
                                                        Title
                                                    </label>
                                                    <input
                                                        id="name"
                                                        name="name"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        aria-describedby="name"
                                                        value="<?= FormController::getFormData('name'); ?>">
                                                </div>
                                                <div class="form-group pb-4">
                                                    <label for="url">
                                                        URL
                                                    </label>
                                                    <input
                                                        id="url"
                                                        name="url"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        aria-describedby="url"
                                                        value="<?= FormController::getFormData('url'); ?>">
                                                </div>
                                                <div class="form-group pb-4">
                                                    <label for="meta_keywords">
                                                        Meta keywords
                                                    </label>
                                                    <input
                                                        id="meta_keywords"
                                                        name="meta_keywords"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        aria-describedby="meta_keywords"
                                                        value="<?= FormController::getFormData('meta_keywords'); ?>">
                                                </div>
                                                <div class="form-group pb-4">
                                                    <label for="meta_description">
                                                        Meta description
                                                    </label>
                                                    <input
                                                        id="meta_description"
                                                        name="meta_description"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        aria-describedby="meta_description"
                                                        value="<?= FormController::getFormData('meta_description'); ?>">
                                                </div>
                                            </td>
                                            <td width="350px" class="align-top p-0 pl-3 border-0">
                                                <div class="card-header m-0">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                                                    </svg>
                                                    <span class="card-title">Keyword list</span>
                                                </div>
                                                <ul id="keywords-list" class="border">
                                                    <li id="no-keywords" class="border-0">Add keywords below</li>
                                                </ul>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <?php
                                $this->partial(
                                    'makabe/keywords/widget',
                                    [
                                        'url' => $url
                                    ]
                                );
                            ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('media-tab', 'overview-tab'); ?>"
                    id="media-tab"
                    role="tabpanel"
                    aria-labelledby="media-tab">
                    <?= $this->partial(
						"common/files/widget",
						[
                            'upload' => false,
                            'selects' => false,
                            'delete' => false,
							'url' => $url . '/add'
						]
					); ?>
                </div>
            </div>
        </div>
    </div>
</form>