<?php
/**
 * Spinner edit template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

switch ($data->resource) {
	case 'blog-post':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts';
		$parent = 'Blog posts';
		$child = 'Blog post';
		break;
    case 'blog-post-category':
        $url = ($this->di->getConfig())->urls->cms . '/blog-posts/categories/';
        $parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/categories';
        $parent = 'Blog post categories';
        $child = 'Blog post category';
        break;
	case 'page':
		$url = ($this->di->getConfig())->urls->cms . '/pages/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/pages';
		$parent = 'Pages';
		$child = 'Page';
		break;
	case 'portfolio':
		$url = ($this->di->getConfig())->urls->cms . '/portfolio/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/portfolio';
		$parent = 'Portfolio';
		$child = 'Portfolio piece';
		break;
}

$url .= $data->resource_id . '/spinner';

$collapse = !empty($_GET['collapse']) ? $_GET['collapse'] : '';

echo $this->partial("common/form/messages");
echo $this->partial("makabe/spinner/shared");
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>

<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>">
    <input type="hidden" name="collapse" value="<?= $collapse; ?>">
    <div class="row mb-3">
        <div class="col-3">
            <div class="card bg-primary">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                        <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->stats['total']; ?></strong> visit<?= $data->stats['total'] == 1 ? '' : 's'; ?>
                    </div>
                    <div class="text-white">
                        Visits with this content
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div
				class="card <?= $data->page->spinnable ? 'bg-info' : 'bg-warning'; ?>"
				data-toggle="tooltip"
				data-dismiss="hover"
				data-placement="top"
				title="Spin support <?= $data->page->spinnable ? 'enabled' : 'disabled'; ?>">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 9.5a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                        <path d="M9.5 2c-.9 0-1.75.216-2.501.6A5 5 0 0 1 13 7.5a6.5 6.5 0 1 1-13 0 .5.5 0 0 1 1 0 5.5 5.5 0 0 0 8.001 4.9A5 5 0 0 1 3 7.5a6.5 6.5 0 0 1 13 0 .5.5 0 0 1-1 0A5.5 5.5 0 0 0 9.5 2zM8 3.5a4 4 0 1 0 0 8 4 4 0 0 0 0-8z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <?php
                        if ($data->spins) {
                            ?>
                            <strong><?= $data->spins; ?></strong> time<?= $data->spins == 1 ? '' : 's'; ?>
                            <?php
                        } else {
                            ?>
                            <strong>Never</strong>
                            <?php
                        }
                        ?>
					</div>
                    <div class="text-white">
                        Spun content has been used
                    </div>
                </div>
            </div>
        </div>
		<div class="col-3">
            <div class="card bg-danger">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                        <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong>
                            <?php
                            if ($data->spun_count) {
                                if ($data->spun_used_at) {
                                    echo DateHelper::pretty($data->spun_used_at, false, false, 'Never');
                                } else {
                                    echo 'Never';
                                }
                            } else {
                                echo 'Never';
                            }
                            ?>
                        </strong>
					</div>
                    <div class="text-white">
                        Last used
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-success">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 4a4 4 0 0 0-4 4 .5.5 0 0 1-1 0 5 5 0 0 1 5-5 .5.5 0 0 1 0 1zm4.5 3.5a.5.5 0 0 1 .5.5 5 5 0 0 1-5 5 .5.5 0 0 1 0-1 4 4 0 0 0 4-4 .5.5 0 0 1 .5-.5z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->spun_count; ?></strong> spun
                    </div>
                    <div class="text-white">
                        Available for use
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <a
                        href="<?= UrlHelper::backend($url); ?>"
                        class="btn btn-blank mr-2 text-center"
                        title="Go back"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                        </svg><br/>
                        back
                    </a>
                    <?php
                    if (empty($data->job)) {
                        ?>
                        <button
                            id="btn-save"
                            class="btn btn-blank float-right"
                            type="button"
                            title="Save the spin content"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                            </svg><br/>
                            save
                        </button>
                        <a
                            href="<?= UrlHelper::backend($url . '/spin/' . $data->id); ?>"
                            class="btn btn-blank float-right"
                            title="Trigger the spin"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="bottom">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M6.999 2.6A5.5 5.5 0 0 1 15 7.5a.5.5 0 0 0 1 0 6.5 6.5 0 1 0-13 0 5 5 0 0 0 6.001 4.9A5.5 5.5 0 0 1 1 7.5a.5.5 0 0 0-1 0 6.5 6.5 0 1 0 13 0 5 5 0 0 0-6.001-4.9zM10 7.5a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
                            </svg><br/>
                            spin
                        </a>
                        <a
                            href="<?= UrlHelper::backend($url . '/' . $data->id . '/spun'); ?>"
                            class="btn btn-blank float-right"
                            title="View the spun content"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="bottom">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 4a4 4 0 0 0-4 4 .5.5 0 0 1-1 0 5 5 0 0 1 5-5 .5.5 0 0 1 0 1zm4.5 3.5a.5.5 0 0 1 .5.5 5 5 0 0 1-5 5 .5.5 0 0 1 0-1 4 4 0 0 0 4-4 .5.5 0 0 1 .5-.5z"/>
                            </svg><br/>
                            spun
                        </a>
                        <?php
                        if ($data->deleted_at) {
                            ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Recover the spun content from the trash">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                    </svg><br/>
                                    recover
                                </div>
                            </button>
                            <?php
                        } else {
                            ?>
                            <button
                                class="btn btn-blank float-right"
                                type="button"
                                data-original-title="Are you sure?"
                                data-html="true"
                                data-trigger="focus"
                                data-toggle="popover"
                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                                <div
                                    data-toggle="tooltip"
                                    data-dismiss="hover"
                                    data-placement="top"
                                    title="Throw the spun content into the trash">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg><br/>
                                    delete
                                </div>
                            </button>
                            <?php
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
        <?php
        if (empty($data->job)) {
            ?>
            <div class="col-12 mt-5 mb-0 pb-0">
                <div class="alert alert-danger d-flex align-items-center mb-0">
                    <div class="d-flex flex-column">
                        <p>Spinning content can take some time please be patient</p>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <?php
                        $label = "I'm inactive";
                        $bg_colour = 'bg-warning';

                        if ($data->deleted_at) {
                            $label = "I'm in a deleted state";
                            $bg_colour = 'bg-danger';
                        } else {
                            $label = "I'm live!";
                            $bg_colour = 'bg-success';
                        }
                        ?>
                        <div class="mr-4 mb-4">
                            <div
								class="preview-img"
								title="<?= $label; ?>"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="bottom">
	                            <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
								</div>
	                            <div class="circle border border-white <?= $bg_colour; ?>"></div>
							</div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="label">
									Label <span class="required">*</span>
								</label>
                                <input
                                    id="label"
                                    name="label"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="label"
                                    value="<?= FormController::getFormData('label', $data); ?>"
                                    <?= !empty($data->job) ? 'disabled' : ''; ?>>
                            </div>
                            <div class="form-group mb-4">
                                <label for="campaign_id">SEO Campaign</label>
                                <select
                                    name="campaign_id"
                                    class="form-control mt-2">
                                    <?php
                                    $selected = FormController::getFormData('campaign_id', $data);
                                        ?>
                                        <option value="">No campaign</option>
                                        <?php
                                    foreach ($campaigns as $campaign) {
                                        ?>
                                        <option
                                            value="<?= $campaign->id; ?>"
                                            <?= $selected == $campaign->id ? ' selected' : ''; ?>><?= $campaign->name; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Content <span class="required">*</span>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('media-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#media-tab">
                                Media
                            </a>
                        </li>
						<li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#stats-tab">
                                Stats
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card p-0">
                                <div class="card-body">
                                    <a
                                        href="<?= UrlHelper::backend($url . '/clean/' . $data->id); ?>"
                                        class="btn btn-blank float-right"
                                        title="Remove all tags and just have paragraphs"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="bottom">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294l4-13zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0zm6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0z"/>
                                        </svg><br/>
                                        clean
                                    </a>
                                </div>
                            </div>
                        </div>
                        <?php
                        if ($predicted_spins) {
                            ?>
                            <div class="col-12">
                                <div class="alert alert-primary d-flex align-items-center">
                                    <div class="d-flex flex-column">
                                        <p>
                                            Predicting <?= NumberHelper::pretty($predicted_spins);?> unique pieces of content of the maximum <?= NumberHelper::pretty(($this->di->getConfig())->makabe->max_spins); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        if (!empty($data->job)) {
                            ?>
                            <div class="col-12">
                                <div class="alert alert-info d-flex align-items-center">
                                    <div class="d-flex flex-column">
                                        <p>Awaiting spinning content job to be complete</p>
                                    </div>
                                </div>
                            </div>
                            <?php
                        } else {
                            ?>
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-header mb-2">
                                        <span class="card-title">
                                            Content for spinning <span class="required">*</span>
                                        </span>
                                    </div>
                                    <div class="card-body p-3 pt-0">
                                        <table class="table table-borderless">
                                            <tr>
                                                <td class="align-top p-0 border-0 pr-3">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <div class="form-group pb-1">
                                                                <?= $this->partial(
                                                                    'website/pages/sections/content',
                                                                    [
                                                                        'data' => $data,
                                                                        'full' => false
                                                                    ]
                                                                ); ?>
                                                            </div>
                                                            <div class="card mb-5 p-3 pt-0 pb-0">
                                                                <div class="card-header">
                                                                    <button
                                                                        type="button"
                                                                        class="btn btn-blank w-100"
                                                                        data-toggle="collapse"
                                                                        data-target="#extra-spin">
                                                                        <span class="text-primary">
                                                                            Extra
                                                                        </span>
                                                                    </button>
                                                                </div>
                                                                <div id="extra-spin" class="card-body pt-0 mb-4 collapse">
                                                                    <div class="form-group pb-4">
                                                                        <label for="name">
                                                                            Title
                                                                        </label>
                                                                        <input
                                                                            id="name"
                                                                            name="name"
                                                                            type="text"
                                                                            class="form-control mt-2"
                                                                            aria-describedby="name"
                                                                            value="<?= FormController::getFormData('name', $data); ?>">
                                                                    </div>
                                                                    <div class="form-group pb-4">
                                                                        <label for="url">
                                                                            URL
                                                                        </label>
                                                                        <input
                                                                            id="url"
                                                                            name="url"
                                                                            type="text"
                                                                            class="form-control mt-2"
                                                                            aria-describedby="url"
                                                                            value="<?= FormController::getFormData('url', $data); ?>">
                                                                    </div>
                                                                    <div class="form-group pb-4">
                                                                        <label for="meta_keywords">
                                                                            Meta keywords
                                                                        </label>
                                                                        <input
                                                                            id="meta_keywords"
                                                                            name="meta_keywords"
                                                                            type="text"
                                                                            class="form-control mt-2"
                                                                            aria-describedby="meta_keywords"
                                                                            value="<?= FormController::getFormData('meta_keywords', $data); ?>">
                                                                    </div>
                                                                    <div class="form-group pb-4">
                                                                        <label for="meta_description">
                                                                            Meta description
                                                                        </label>
                                                                        <input
                                                                            id="meta_description"
                                                                            name="meta_description"
                                                                            type="text"
                                                                            class="form-control mt-2"
                                                                            aria-describedby="meta_description"
                                                                            value="<?= FormController::getFormData('meta_description', $data); ?>">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-12">
                                                            <div class="card">
                                                                <div class="card-header">
                                                                    SEO campaign pages
                                                                </div>
                                                                <div class="card-body pt-0 mb-4">
                                                                    <?php
                                                                    if ($data->campaign->scan_pages->count()) {
                                                                        ?>
                                                                        <table class="table tablesorter">
                                                                            <thead>
                                                                                <tr>
                                                                                    <th>&#35;</th>
                                                                                    <th>Name</th>
                                                                                    <th>URL</th>
                                                                                    <th>Status</th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tbody>
                                                                                <?php
                                                                                foreach ($data->campaign->scan_pages as $row) {
                                                                                    switch ($row->scan_status) {
                                                                                        case 'scanned':
                                                                                            $bg_colour = 'badge-success';
                                                                                            break;
                                                                                        case 'not scanned':
                                                                                            $bg_colour = 'badge-warning';
                                                                                            break;
                                                                                        case 'failed':
                                                                                            $bg_colour = 'badge-danger';
                                                                                            break;
                                                                                        default:
                                                                                            break;
                                                                                    }
                                                                                    ?>
                                                                                    <tr>
                                                                                        <td><?= $row->rank; ?></td>
                                                                                        <td>
                                                                                            <?= $row->name; ?>
                                                                                        </td>
                                                                                        <td>
                                                                                            <a href="<?= $row->url ?>" target="_blank"><?= $row->url ?></a>
                                                                                        </td>
                                                                                        <td>
                                                                                            <span class="badge <?= $bg_colour; ?>">
                                                                                                <?= $row->scan_status ?>
                                                                                            </span>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td colspan="4" class="row-header text-center">
                                                                                            <button
                                                                                                id="btn-row-<?= $row->id; ?>"
                                                                                                type="button"
                                                                                                class="page-preview-btn btn btn-blank w-100"
                                                                                                data-toggle="collapse"
                                                                                                data-target="#row-<?= $row->id; ?>"
                                                                                                data-url="<?= $row->url; ?>">
                                                                                                <span class="icon-down text-primary">
                                                                                                    preview
                                                                                                </span>
                                                                                            </button>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <tr id="row-<?= $row->id; ?>" class="collapse<?= 'row-' . $row->id == $collapse ? 'show' : ''; ?>">
                                                                                        <td colspan="4" class="border">
                                                                                            <div class="page-preview">
                                                                                                <?php
                                                                                                if ('row-' . $row->id == $collapse) {
                                                                                                    ?>
                                                                                                    <iframe src="<?= $row->url; ?>"></iframe>
                                                                                                    <?php
                                                                                                }
                                                                                                ?>
                                                                                            </div>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                            </tbody>
                                                                        </table>
                                                                        <?php
                                                                    } else {
                                                                        ?>
                                                                        <p class="h6 pb-0 m-0">No pages</p>
                                                                        <?php
                                                                    }
                                                                    ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td width="350px" class="align-top p-0 pl-3 border-0">
                                                    <div class="card-header m-0">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                                                        </svg>
                                                        <span class="card-title">Keyword list</span>
                                                    </div>
                                                    <ul id="keywords-list" class="border">
                                                        <?php
                                                        if (!empty($data->campaign)) {
                                                            if ($data->campaign->words) {
                                                                foreach ($data->campaign->words as $keyword) {
                                                                    if ($keyword->word_count < 10) {
                                                                        $bg_colour = 'badge-danger';
                                                                    } elseif ($keyword->word_count < 20) {
                                                                        $bg_colour = 'badge-warning';
                                                                    } elseif ($keyword->word_count < 30) {
                                                                        $bg_colour = 'badge-info';
                                                                    } elseif ($keyword->word_count < 40) {
                                                                        $bg_colour = 'badge-primary';
                                                                    } else {
                                                                        $bg_colour = 'badge-success';
                                                                    }
                                                                    $keyword_count = StringHelper::count($data->content, $keyword->word);
                                                                    ?>
                                                                    <li id="keyword-list-<?= $keyword->id;?>">
                                                                        <span
                                                                            class="badge <?= $bg_colour; ?>"
                                                                            data-toggle="tooltip"
                                                                            data-dismiss="hover"
                                                                            data-placement="top"
                                                                            title="<?= $keyword->popularity ?>, appears in search content <?= $keyword->word_count; ?> time<?= $keyword->word_count == 1 ? '' : 's'; ?>"><?= $keyword->word; ?></span>
                                                                        <span
                                                                            class="badge bg-primary text-white ml-4"
                                                                            data-toggle="tooltip"
                                                                            data-dismiss="hover"
                                                                            data-placement="top"
                                                                            title="Keyword is used <?= $keyword_count; ?> time<?= $keyword_count == 1 ? '' : 's'; ?> in the content"><?= $keyword_count; ?></span>
                                                                        <span class="float-right btn btn-blank p-0 mr-2 clipboard-copy" data-clipboard="<?= $keyword->word; ?>" data-toggle="tooltip" data-dismiss="hover" data-placement="top" title="Copy to clipboard">
                                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                                                                                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                                                                            </svg>
                                                                        </span>
                                                                        <input type="hidden" name="keywords[]" value="<?= $keyword->id;?>"/>
                                                                    </li>
                                                                    <?php
                                                                }
                                                            }
                                                        } else {
                                                            ?>
                                                            <li id="no-keywords">Please select an SEO campaign</li>
                                                            <?php
                                                        }
                                                        ?>
                                                    </ul>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('media-tab', 'overview-tab'); ?>"
                    id="media-tab"
                    role="tabpanel"
                    aria-labelledby="media-tab">
                    <?= $this->partial(
						"common/files/widget",
						[
                            'upload' => false,
                            'selects' => false,
                            'delete' => false,
							'url' => $url . '/edit/' . $data->id
						]
					); ?>
                </div>
				<div
                    class="tab-pane <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                    id="stats-tab"
                    role="tabpanel"
                    aria-labelledby="stats-tab">
                    <?= $this->partial("website/pages/sections/stats", ['data' => $data]); ?>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
