<style>

</style>

<script type="text/javascript">
    $(function () {
        $(".keyword-list-delete").click((event) => {
            $(event.currentTarget).parent().remove();
        });

        $(".add-keyword").click((event) => {
            $("#keywords-list #no-keywords").remove();

            let id = $(event.currentTarget).data("id");
            $("#keywords-list #keyword-list-" + id).remove();

            let html = '<li id="keyword-list-' + id + '">';
            html += '<span class="float-left">' + $("#keyword-index-" + id + " .keyword-index-keyword").html() + '</span>';
            html += '<span class="btn btn-blank p-0 float-right keyword-list-delete" data-toggle="tooltip" data-dismiss="hover" data-placement="top" title="Delete from list">';
            html += '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">';
            html += '<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>';
            html += '<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>';
            html += '</svg></span>';
            html += '<span class="btn btn-blank float-right p-0 mr-2" data-toggle="tooltip" data-dismiss="hover" data-placement="top" title="Copy to clipboard">';
            html += '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">';
            html += '<path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>';
            html += '<path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>';
            html += '</svg></span>';
            html += '<input type="hidden" name="keywords[]" value="' + id + '"/>';
            html += '</li>';

            $("#keywords-list").append(html);

            $(".keyword-list-delete").unbind("click").bind("click", (event) => {
                $(event.currentTarget).parent().remove();
            });

            $('[data-toggle="tooltip"]').tooltip();
        });
    });
</script>