<?php
/**
 * Basket index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->sales . '/basket';

echo $this->partial("common/form/messages");
if (!empty($data->quantity)) {
    ?>
    <div class="row mb-3">
        <div class="col-3">
            <div class="card bg-primary">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->quantity; ?></strong>
                    </div>
                    <div class="text-white">
                        Quantity
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-info">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                        <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->sub_total; ?></strong>
                    </div>
                    <div class="text-white">
                        Sub-total
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-warning">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                        <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->vat; ?></strong>
                    </div>
                    <div class="text-white">
                        VAT
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-success">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1H1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                        <path d="M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2H3z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <strong><?= $data->total; ?></strong>
                    </div>
                    <div class="text-white">
                        Total
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>">
<?php
if (!empty($data->quantity)) {
    ?>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <button
                        class="btn btn-blank"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/clear'); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Throw the basket into the trash">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg><br/>
                            delete
                        </div>
                    </button>
                    <?php
                    if (!empty($data->items) && $data->items->count()) {
                        ?>
                        <button
                            class="btn btn-blank"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/archive'); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Save the basket for later">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                </svg><br/>
                                archive
                            </div>
                        </button>
                        <button
                            class="btn btn-blank btn-save float-right"
                            type="submit"
                            name="checkout"
                            data-title="Go to the checkout"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top"
                            value="checkout">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                            </svg><br/>
                            checkout
                        </button>
                        <button
                            class="btn btn-blank btn-save float-right"
                            type="submit"
                            name="update"
                            data-title="Update the basket"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top"
                            value="update">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                            </svg><br/>
                            update
                        </button>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <?php
                    if (!empty($data->items) && $data->items->count()) {
                        ?>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th width="120">In stock</th>
                                    <th width="120">Quantity</th>
                                    <th width="140">Sub-total</th>
                                    <th width="140">VAT</th>
                                    <th width="140">Total</th>
                                    <th width="70">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($data->items as $item) {
                                    ?>
                                    <tr>
                                        <td>
                                            <a href="<?= UrlHelper::backend(($this->di->getConfig())->urls->sales . '/products/edit/' . $item->product->page_id); ?>">
                                                <?= $item->product->page->name; ?>
                                            </a>
                                        </td>
                                        <td><?= $item->product->stock; ?></td>
                                        <td>
                                            <input
                                                name="quantity[<?= $item->id; ?>]"
                                                type="text"
                                                class="form-control"
                                                value="<?= $item->quantity; ?>">
                                        </td>
                                        <td><?= $item->sub_total; ?></td>
                                        <td><?= $item->vat; ?></td>
                                        <td><?= $item->total; ?></td>
                                        <td>
                                            <button
                                                class="btn btn-blank float-right"
                                                type="button"
                                                data-original-title="Are you sure?"
                                                data-html="true"
                                                data-trigger="focus"
                                                data-toggle="popover"
                                                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $item->product_id); ?>">Yes</a>'>
                                                <div
                                                    data-toggle="tooltip"
                                                    data-dismiss="hover"
                                                    data-placement="top"
                                                    title="Remove the item from the basket">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </div>
                                            </button>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                <tr>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="3" class="border-0">&nbsp;</th>
                                    <th class="text-right">Sub-total</th>
                                    <td><?= $data->sub_total; ?></td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <th colspan="3" class="border-0">&nbsp;</th>
                                    <th class="text-right">VAT</th>
                                    <td><?= $data->vat; ?></td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <th colspan="3" class="border-0">&nbsp;</th>
                                    <th class="text-right">Total</th>
                                    <td><?= $data->total; ?></td>
                                    <td>&nbsp;</td>
                                </tr>
                            </tfoot>
                        </table>
                        <?php
                    } else {
                        ?>
                        <h3 class="m-4">Nothing in the basket</h3>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <?php
        if (!empty($data->quantity)) {
            ?>
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-body">
                        <div class="card shadow-none">
                            <div class="card-header m-0">
                                <span class="card-title">Notes</span>
                            </div>
                            <div class="card-body">
                                <?php
                                echo $this->partial(
                                    'common/notes/list',
                                    [
                                        'notes' => $data->notes,
                                        'url' => $url . '/edit/' . $data->id . '?clear=true&tab=notes-tab'
                                    ]
                                );
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</form>

<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
