<div id="page" class="col-12">
    <div class="container-fluid">
        <div class="container">
            <section class="mt-3">
                <div class="page-content">
                    <div class="card page-not-found">
                        <div class="card-header">
                            <h2>
                                <span>Page not found</span>
                            </h2>
                        </div>
                        <div class="card-body text-center mb-5">
                            <img src="<?= $this->tengu->theme->getAsset('imgs/monkey-sad.png'); ?>" alt="Sad monkey"/><br/>
                            <span class="h3 sub-heading text-white">
                            <?php
                            if ($this->tengu->theme->getSlug()== "may-fourth") {
                                ?>
                                I sense a disturbance in the force!
                                <?php
                            } else {
                                ?>
                                I'm so sorry but I can not find that page
                                <?php
                            }
                            ?>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="page-background-image">
                    <img src="<?= $this->tengu->theme->getAsset('imgs/page-not-found.jpg'); ?>" alt="Page not found">
                </div>
                <?= $this->partial('common/theme_animation'); ?>
            </section>
        </div>
        <div class="category-pages col-12">
            <?= $this->partial('common/featured'); ?>
            <?= $this->partial("common/maybe_of_interest"); ?>
        </div>
    </div>
</div>