<?php
/**
 * Keyword edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->mms . '/keywords';

$back_url = $url;
if (!empty($_GET['from'])) {
    $back_url = urldecode($_GET['from']);
}

echo $this->partial("common/form/messages");
if ($data->rank < 10) {
    $bg_colour = 'bg-danger';
} elseif ($data->rank < 20) {
    $bg_colour = 'bg-warning';
} elseif ($data->rank < 30) {
    $bg_colour = 'bg-info';
} else {
    $bg_colour = 'bg-success';
}
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>">
    <div class="row mb-3">
        <div class="col-3">
            <div class="card <?= $bg_colour; ?>">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg>
                    <div class="h3 text-white mt-3 mb-1">
                        <?= $data->popularity; ?>
					</div>
                    <div class="text-white">
                        Popularity
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <a
                        href="<?= UrlHelper::backend($back_url); ?>"
                        class="btn btn-blank mr-2 text-center"
                        title="Go back"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                        </svg><br/>
                        back
                    </a>
                    <button
                        id="btn-save"
                        class="btn btn-blank float-right"
                        type="button"
                        title="Save the keyword"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
                        save
                    </button>
                    <a
                        href="<?= UrlHelper::backend($url . '/add'); ?>"
                        class="btn btn-blank float-right"
                        title="Add a new keyword"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="top">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                        </svg><br/>
                        new
                    </a>
                    <?php
                    if ($data->deleted_at) {
                        ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Recover the keyword from the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                </svg><br/>
                                recover
                            </div>
                        </button>
                        <?php
                    } else {
                    ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Throw the keyword into the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg><br/>
                                delete
                            </div>
                        </button>
                        <?php
                    }
                    if (!empty($data->campaign_id)) {
                        $campaign_url = ($this->di->getConfig())->urls->mms . '/seo-campaigns/edit/';
                        ?>
                        <a
                            href="<?= UrlHelper::backend($campaign_url . $data->campaign_id); ?>"
                            class="btn btn-blank float-right"
                            title="View the campaign"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="top">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                                <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383zm.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z"/>
                            </svg><br/>
                            campaign
                        </a>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
		<div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <?php
                            if ($data->deleted_at) {
                                $label = "I'm in a deleted state";
                                $bg_colour = 'bg-danger';
                            } else {
                                $label = "I'm live!";
                                $bg_colour = 'bg-success';
                            }
                        ?>
                        <div class="mr-4 mb-4">
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div title="<?= $label; ?>" class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="keyword">
                                    Keyword
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="keyword"
                                    name="keyword"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="keyword"
                                    value="<?= FormController::getFormData('keyword', $data); ?>"
                                    required>
                            </div>
                        </div>
                        <input name="campaign_id" type="hidden" value="<?= FormController::getFormData('campaign_id', $data); ?>">
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('used-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#used-tab">
                                Used in
                                <?php
								if ($used_count = count($data->used_in)) {
									?>
									<span class="badge badge-primary"><?= $used_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#stats-tab">
                                Stats
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('used-tab', 'overview-tab'); ?>"
                    id="used-tab"
                    role="tabpanel"
                    aria-labelledby="used-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-body">
                                            <?php
                                            $resources = $data->used_in;
                                            if ($resources) {
                                                ?>
                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th>Type</th>
                                                            <th>Name</th>
                                                            <th>&nbsp;</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php
                                                        foreach ($resources as $resource) {
                                                            ?>
                                                            <tr>
                                                                <td>
                                                                    <?= str_replace('-', ' ', $resource['type']); ?>
                                                                    <?= $resource['sub_type'] ? '<br/><small>' . str_replace('-', ' ', $resource['sub_type']) . '</small>' : ''; ?>
                                                                </td>
                                                                <td><?= $resource['name']; ?></td>
                                                                <td>
                                                                    <a
                                                                        href="<?= UrlHelper::backend($resource['url']); ?>"
                                                                        class="btn btn-blank float-right"
                                                                        title="Edit the <?= str_replace('-', ' ', $resource['type']); ?>"
                                                                        data-toggle="tooltip"
                                                                        data-trigger="hover"
                                                                        data-dismiss="click"
                                                                        data-placement="top">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                            <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                                        </svg>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            <?php
                                                        }
                                                        ?>
                                                    </tbody>
                                                </table>
                                                <?php
                                            } else {
                                                ?>
                                                <strong>Not used</strong>
                                                <?php
                                            }
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?= $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true#notes-tab'
                                                ]
                                            ); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('stats-tab', 'overview-tab'); ?>"
                    id="stats-tab"
                    role="tabpanel"
                    aria-labelledby="stats-tab">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-header">
                                    <span class="card-title">Keyword traction</span>
                                </div>
                                <div class="card-body pt-0">
                                    <canvas id="stats" width="600" height="200"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        var ctx = document.getElementById('stats').getContext('2d');
                        var orders = new Chart(ctx, {
                            type: 'line',
                            data: {
                                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                                datasets: [
                                    <?php
                                    $colours = [
                                        'visitors' => '#E14ECA',
                                        'search' => '#1D8CF8',
                                    ];

                                    foreach ($data->stats as $label => $stats) {
                                        if ($label == 'total') {
                                            continue;
                                        }
                                        $values = '';
                                        foreach ($stats as $value) {
                                            $values .= $value . ',';
                                        }
                                        ?>
                                        {
                                            label: '<?= ucwords($label); ?>',
                                            data: [<?= rtrim($values, ','); ?>],
                                            fill: false,
                                            backgroundColor: '<?= $colours[$label]; ?>',
                                            borderColor: '<?= $colours[$label]; ?>',
                                            tension: 0.1
                                        },
                                        <?php
                                    }
                                    ?>
                                ]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });
                    </script>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
