<?php
/**
 * Keyword widget template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Makabe\Models\Keywords;
use Kytschi\Makabe\Controllers\KeywordsController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

if (!isset($content)) {
    $content = '';
}

$keywords_url = ($this->di->getConfig())->urls->mms . '/keywords';

$keywords = (new Keywords)::find([
	'conditions' => 'deleted_at IS NULL',
    'order' => 'rank DESC'
]);
?>
<div class="card">
    <div class="card-header mb-2">
        <span class="card-title">Keyword index</span>
    </div>
    <div class="card-body p-3 pt-0">
        <div class="row">
            <div class="col-12">
                <?php
                if ($keywords->count()) {
                    ?>
                    <table class="table tablesorter table-hover">
                        <thead>
                            <tr>
                                <th>Keyword</th>
                                <th>Popularity</th>
                                <th>Already used</th>
                                <th width="230px">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($keywords as $key => $keyword) {
                                if ($keyword->rank < 10) {
                                    $bg_colour = 'badge-danger';
                                } elseif ($keyword->rank < 20) {
                                    $bg_colour = 'badge-warning';
                                } elseif ($keyword->rank < 30) {
                                    $bg_colour = 'badge-info';
                                } elseif ($keyword->rank < 40) {
                                    $bg_colour = 'badge-primary';
                                } else {
                                    $bg_colour = 'badge-success';
                                }

                                $url = $keywords_url  . '/edit/' . urlencode($keyword->id);
                                $url .= '?from=' . urlencode(UrlHelper::get());
                                ?>
                                <tr id="keyword-index-<?= $keyword->id; ?>">
                                    <td class="keyword-index-keyword"><span 
                                        class="badge <?= $bg_colour; ?>"
                                        data-toggle="tooltip"
                                        data-dismiss="hover"
                                        data-placement="top"
                                        title="<?= $keyword->popularity ?>, appears in search content <?= $keyword->rank; ?> time<?= $keyword->rank == 1 ? '' : 's'; ?>"><?= $keyword->keyword; ?></span>
                                    </td>
                                    <td
                                        class="keyword-index-popularity">
                                        <span class="badge <?= $bg_colour; ?>"><?= $keyword->popularity ?></span><br/>
                                        <small>appears in search content <?= $keyword->rank; ?> time<?= $keyword->rank == 1 ? '' : 's'; ?></small>
                                    </td>
                                    <td><?= KeywordsController::count($keyword->keyword, $content, $keyword->case_sensitive); ?></td>
                                    <td>
                                        <a
                                            class="btn btn-blank float-right m-0 p-3"
                                            data-toggle="collapse"
                                            href="#keyword-notes-<?= $key; ?>"
                                            role="button"
                                            aria-expanded="false"
                                            aria-controls="keyword-<?= $key; ?>">
                                            <span
                                                title="View the notes"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                                    <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                                    <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                                </svg>
                                            </span>
                                        </a>
                                        <a
                                            class="btn btn-blank float-right m-0 p-3"
                                            href="<?= UrlHelper::backend($url); ?>">
                                            <span
                                                title="Edit the keyword"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                </svg>
                                            </span>
                                        </a>
                                        <span class="btn btn-blank float-right m-0 p-3">
                                            <span
                                                class="add-keyword"
                                                data-id="<?= $keyword->id; ?>"
                                                title="Add to keyword list"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                                                    <path d="M8 4a.5.5 0 0 1 .5.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5A.5.5 0 0 1 8 4z"/>
                                                </svg>
                                            </span>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="collapse" id="keyword-notes-<?= $key; ?>">
                                    <td colspan="4">
                                        <h4>Notes</h4>
                                        <div class="row">
                                            <div class="col-12">
                                                <?php
                                                if ($keyword->notes->count()) {
                                                    foreach($keyword->notes as $note) {
                                                        ?>
                                                        <div class="alert alert-default d-flex align-items-center">
                                                            <div class="d-flex flex-column w-100">
                                                                <div class="row">
                                                                    <div class="col-12">
                                                                        <p><?= $note->content;?></p>
                                                                    </div>
                                                                    <div class="col-12">
                                                                        <p class="float-left pt-3">
                                                                            By <?= $note->created->full_name; ?>, <?= DateHelper::pretty($note->created_at, false); ?>
                                                                        </p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <?php
                                                    }
                                                } else {
                                                    ?>
                                                    <p class="mb-3">No notes</p>
                                                    <?php
                                                }
                                                ?>
                                                <div class="form-group mt-2">
                                                    <textarea
                                                        name="keyword_note[<?= $keyword->id; ?>]"
                                                        class="form-control"
                                                        placeholder="Add a note here"
                                                        rows="3"></textarea>
                                                </div>
                                                <button
                                                    type="button"
                                                    class="btn btn-default float-right m-0"
                                                    onclick="$('#btn-save').click()">
                                                        Add
                                                </button>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                    <?php
                } else {
                    ?>
                    <p class="h5 pt-3 pb-0 m-0">No keywords</p>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>