<?php
/**
 * Settings index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->cms . '/settings';

echo $this->partial("common/form/messages");
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update'); ?>">
    <div class="row mb-3">
		<div class="col-12">
			<div class="card p-0">
				<div class="card-body">
					<button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save my page"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
				</div>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div
                                class="preview-img"
                                title="I'm inactive"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <?php
                                    if ($data->status == 'offline') {
                                        $label = "I'm offline";
                                        $bg_colour = 'bg-danger';
                                    } else {
                                        $label = "I'm live!";
                                        $bg_colour = 'bg-success';
                                    }
                                    ?>
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="<?= $label; ?>">
                                    <div
                                        title="<?= $label; ?>"
                                        class="position-absolute circle <?= $bg_colour; ?>"
                                        style="width: 10px;height: 10px;margin-top: -5px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group form-check mt-0 mb-4">
                                <label for="status">Go live</label>
                                <div class="checkbox switcher mt-2">
                                    <label>
                                        <input
                                            id="status"
                                            type="checkbox"
                                            name="status"
                                            value="<?= FormController::getFormData('status', $data); ?>"
                                            <?= FormController::getFormData('status', $data) == 'online' ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group mb-4">
                                <label for="name">
                                    Name
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="slogan">
                                    Slogan
                                </label>
                                <input
                                    id="slogan"
                                    name="slogan"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="slogan"
                                    value="<?= FormController::getFormData('slogan', $data); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="contact_email">
                                    Contact email
                                </label>
                                <input
                                    id="contact_email"
                                    name="contact_email"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="contact_email"
                                    value="<?= FormController::getFormData('contact_email', $data); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="address">
                                    Address
                                </label>
                                <textarea name="address" rows="6" class="form-control mt-2" style="white-space: pre-wrap;"><?= FormController::getFormData('address', $data); ?></textarea>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
						<li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('stats-exclude-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#stats-exclude-tab">
                                Stats exclude
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link text-active-primary <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Meta</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="meta_description">
                                            Description
                                        </label>
                                        <input
                                            id="meta_description"
                                            name="meta_description"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="meta_description"
                                            value="<?= FormController::getFormData('meta_description', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="tags">
                                            Keywords
                                        </label>
                                        <?php
                                        $tags = '';
                                        foreach ($data->tags as $tag) {
                                            $tags .= $tag->tag . ', ';
                                        }
                                        ?>
                                        <input class="tags mb-4" name="tags" value="<?= rtrim($tags, ', '); ?>"/>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="meta_author">
                                            Author
                                        </label>
                                        <input
                                            id="meta_author"
                                            name="meta_author"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="meta_author"
                                            value="<?= FormController::getFormData('meta_author', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
						<div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">robots</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="robots_txt">
                                            robots.txt
                                        </label>
                                        <textarea name="robots_txt" rows="6" class="form-control mt-2"><?= FormController::getFormData('robots_txt', $data); ?></textarea>
										<small>Note, Sitemap is automatically added.</small>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="robots">
                                            meta robots
                                        </label>
                                        <input
                                            type="text"
                                            name="robots"
                                            class="form-control mt-2"
                                            value="<?= FormController::getFormData('robots', $data); ?>">
										<small>Can be used in the meta tag in the header</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">humans</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="humans_txt">
                                            humans.txt
                                        </label>
                                        <textarea name="humans_txt" rows="6" class="form-control mt-2"><?= FormController::getFormData('humans_txt', $data); ?></textarea>
										<small>If blank I'll generate it based on settings</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				<div
                    class="tab-pane <?= UrlHelper::activeTab('stats-exclude-tab', 'overview-tab'); ?>"
                    id="stats-exclude-tab"
                    role="tabpanel"
                    aria-labelledby="stats-exclude-tab">
                    <div class="row">
						<div class="col-12">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Add an exclude</span>
                                </div>
                                <div class="card-body p-3 pt-0">
									<div class="row">
										<div class="col-12">
											<button
								                class="btn btn-blank float-right"
								                type="button"
								                title="Add an exclude"
								                data-toggle="tooltip"
								                data-trigger="hover"
								                data-dismiss="click"
								                data-placement="top"
												onclick="$('#btn-save').click()">
								                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5z"/>
                                                    <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5L14 4.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5h-2z"/>
                                                </svg>
								            </button>
										</div>
										<div class="col-12">
											<div class="form-group mb-4">
		                                        <label for="meta_description">
		                                            Domain/IP
		                                        </label>
		                                        <input
		                                            id="stats_exclude"
		                                            name="stats_exclude"
		                                            type="text"
		                                            class="form-control mt-2"
		                                            aria-describedby="stats_exclude"
		                                            value="<?= FormController::getFormData('stats_exclude', $data); ?>">
		                                    </div>
										</div>
									</div>
								</div>
							</div>
						</div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Excluding from the stats</span>
                                </div>
                                <div class="card-body p-3 pt-0">
									<?php
									if ($data->excludes->count()) {
										?>
										<table class="table tablesorter">
											<thead>
												<tr>
													<th>Exclude</th>
													<th width="110px">&nbsp;</th>
												</tr>
											</thead>
											<tbody>
												<?php
												foreach ($data->excludes as $exclude) {
													?>
													<tr>
														<td><?= $exclude->exclude; ?></td>
														<td>
															<button
											                    class="btn btn-blank m-0 mr-2 p-3"
											                    type="button"
											                    data-original-title="Are you sure?"
											                    data-html="true"
											                    data-trigger="focus"
											                    data-toggle="popover"
											                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/stats-exclude/delete/' . $exclude->id . '?tab=stats-exclude-tab&from=' . urlencode($url)); ?>">Yes</a>'>
											                    <div
											                        data-toggle="tooltip"
											                        data-dismiss="hover"
											                        data-placement="top"
											                        title="Throw the exclude into the trash">
											                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                                    </svg>
											                    </div>
											                </button>
														</td>
													</tr>
													<?php
												}
												?>
											</tbody>
										</table>
										<?php
									} else {
										?>
										<p class="h5 pt-3 pb-0 m-0">No excludes</p>
										<?php
									}
									?>
								</div>
							</div>
						</div>
					</div>
				</div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'content-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
