<?php
use Kytschi\Tengu\Controllers\Website\BlogPostsController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
$crumbs = UrlHelper::breadcrumbs();

$latest_posts = (new BlogPostsController())->get(3, $page->id, true);
?>
<div id="page" class="col-12">
    <div class="container-fluid">
        <div class="container">
            <section>
                <div class="page-content">
                    <nav class="page-crumbs" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <?php
                            $key = 1;
                            foreach ($crumbs as $name => $url) {
                                if ($key == count($crumbs)) {
                                    ?>
                                    <li class="breadcrumb-item active">
                                        <a href="<?= $page->url; ?>"><h2><?= $page->name; ?></h2></a>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li class="breadcrumb-item">
                                        <a href="<?= $url; ?>"><?= ucwords($name); ?></a>
                                    </li>
                                    <?php
                                }
                                $key++;
                            }
                            ?>
                        </ol>
                    </nav>
                    <div class="page-body">
                        <?php
                        if (!empty($page->cover_image)) {
                            ?>
                            <div class="card-image">
                                <img src="<?= $page->cover_image->url; ?>" alt="<?= $page->cover_image->label; ?>">
                            </div>
                            <?php
                        }
                        ?>
                        <div>
                            <?= $page->content; ?>
                        </div>
                    </div>
                </div>
                <?php
                if (!empty($page->banner_image)) {
                    ?>
                    <div class="page-background-image">
                        <img src="<?= $page->banner_image->url; ?>" alt="<?= $page->banner_image->label; ?>">
                    </div>
                    <?php
                }
                ?>
                <?= $this->partial('common/theme_animation'); ?>
            </section>
        </div>
    </div>
</div>
<?= $this->partial("common/maybe_of_interest"); ?>
