<?php
/**
 * Projects edit template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->hrs . '/timesheets';
$from = $url . '/edit/' . $data->id . '?tab=timesheet-tab';

if (file_exists($file = ($this->di->getConfig())->application->pluginsDir . 'mai/assets/js/timesheet.js')) {
    echo '<script type="text/javascript">' . file_get_contents($file) . '</script>';
}

echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-primary">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9H5.5zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518l.087.02z"/>
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 13.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11zm0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= NumberHelper::toCurrency($data->total); ?></strong>
                </div>
                <div class="text-white">
                    Total income
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a
                    href="<?= UrlHelper::generate(UrlHelper::backend($url)); ?>"
                    class="btn btn-blank mr-2 text-center"
                    title="Go back to the projects list"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                        <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                    </svg><br/>
                    back
                </a>
                <button
                    id="btn-save"
                    class="btn btn-blank float-right"
                    type="button"
                    title="Save the project"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg><br/>
                    save
                </button>
                <a
                    href="<?= UrlHelper::backend($url . '/add'); ?>"
                    class="btn btn-blank float-right"
                    title="Add a new project"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                    </svg><br/>
                    new
                </a>
                <?php
                    if ($data->status == 'deleted') {
                        ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Recover the project from the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                </svg><br/>
                                recover
                            </div>
                        </button>
                        <?php
                    } else {
                    ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Throw the project into the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg><br/>
                                delete
                            </div>
                        </button>
                        <?php
                    }
                    ?>
            </div>
        </div>
    </div>
</div>
<form
    id="form-edit"
    method="post"
    action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>" enctype="multipart/form-data">
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <?php
                            switch ($data->status) {
                                case 'active':
                                    $label = "I'm live!";
                                    $bg_colour = 'bg-success';
                                    break;
                                case 'inactive':
                                    $label = "I'm inactive";
                                    $bg_colour = 'bg-warning';
                                    break;
                                case 'deleted':
                                    $label = "I'm in a deleted state";
                                    $bg_colour = 'bg-danger';
                                    break;
                                default:
                                    break;
                            }
                            ?>
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="name">
                                    Title
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="summary">Description</label>
                                <input
                                    id="summary"
                                    name="summary"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="summary"
                                    value="<?= FormController::getFormData('summary', $data); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="period_start" class="form-label">
                                    Period
                                </label>
                                <table class="table table-borderless">
                                    <tr>
                                        <td class="p-0">
                                            <input
                                                name="period_start"
                                                type="text"
                                                class="form-control form-control-bordered p-3 datepicker"
                                                value="<?= DateHelper::pretty(FormController::getFormData('period_start', $data), false); ?>"/>
                                        </td>
                                        <td class="pl-4" width="70px">to</td>
                                        <td class="p-0">
                                            <input
                                                name="period_end"
                                                type="text"
                                                class="form-control form-control-bordered p-3 datepicker"
                                                value="<?= DateHelper::pretty(FormController::getFormData('period_end', $data), false); ?>"/>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="form-group mb-4">
                                <label for="project_id">Project</label>
                                <select
									name="project_id"
									class="form-control mt-2">
									<?php
									$selected = FormController::getFormData('project_id', $data);
										?>
										<option value="">No project</option>
										<?php
									foreach ($projects as $project) {
										?>
										<option
											value="<?= $project->id; ?>"
											<?= $selected == $project->id ? ' selected' : ''; ?>><?= $project->name; ?></option>
										<?php
									}
									?>
								</select>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('timesheet-tab', 'timesheet-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#timesheet-tab"
                                aria-controls="timesheet-tab"
                                aria-selected="<?= UrlHelper::activeTab('timesheet-tab', 'timesheet-tab', true); ?>">
                                Timesheet
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'timesheet-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab"
                                aria-controls="overview-tab"
                                aria-selected="<?= UrlHelper::activeTab('overview-tab', 'timesheet-tab', true); ?>">
                                Overview
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'timesheet-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('activity-tab', 'timesheet-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('timesheet-tab', 'timesheet-tab'); ?>"
                    id="timesheet-tab"
                    role="tabpanel"
                    aria-labelledby="timesheet-tab">
                    <div class="row">
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <button
                                        data-toggle="modal"
                                        data-target="#modal-add-entry"
                                        class="btn btn-blank float-right">
                                        <span
                                            title="Add board entry"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="bottom">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                                            </svg><br/>
                                            add
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if ($data->entries->count()) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th width="120px">Started on</th>
                                                    <th width="120px">Ended on</th>
                                                    <th width="120px">Hours</th>
                                                    <th width="120px">Price</th>
                                                    <th width="150px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                foreach ($data->entries as $entry) {
                                                    ?>
                                                    <tr>
                                                        <td class="align-top"><?= $entry->title; ?></td>
                                                        <td class="align-top"><?= DateHelper::pretty($entry->started_at, true, false, 'Not set', false); ?></td>
                                                        <td class="align-top"><?= DateHelper::pretty($entry->ended_at, true, false, 'Not set', false); ?></td>
                                                        <td class="align-top"><?= DateHelper::numberOfHours($entry->started_at, $entry->ended_at); ?></td>
                                                        <td class="align-top"><?= NumberHelper::toCurrency($entry->price); ?></td>
                                                        <td class="align-top">
                                                            <button
                                                                class="btn btn-blank float-right btn-umi-edit-entry"
                                                                type="button"
                                                                data-id="<?= $entry->id; ?>"
                                                                data-url="<?= Urlhelper::backend($url . '/entries/update/' . $entry->id . '?from=' . $from); ?>"
                                                                data-title="<?= $entry->title; ?>"
                                                                data-description="<?= $entry->description; ?>"
                                                                data-price="<?= $entry->price; ?>"
                                                                data-started_at="<?= DateHelper::pretty($entry->started_at, true, false, '', false); ?>"
                                                                data-ended_at="<?= DateHelper::pretty($entry->ended_at, true, false, '', false); ?>">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                                </svg>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                        <?php
                                    } else {
                                        ?>
                                        <p class="p-3 mb-0">
                                            <strong class="h5">No entries</strong>
                                        </p>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'timesheet-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'timesheet-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?= $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true&tab=notes-tab'
                                                ]
                                            ); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'timesheet-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="modal" tabindex="-1" id="modal-add-entry">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add entry</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
            <form
                method="post"
                action="<?= UrlHelper::backend($url . '/entries/save'). (!empty($from) ? '?from=' . urlencode($from) : ''); ?>">
                <div class="modal-body">
                    <div class="form-group mb-4">
                        Required fields <span class="required">*</span>
                    </div>
                    <div class="form-group mb-4">
                        <label for="title" class="form-label">
                            Title
                            <span class="required">*</span>
                        </label>
                        <input
                            name="title"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a title"
                            required/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="description" class="form-label">
                            Description
                        </label>
                        <input
                            name="description"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a description if needed"/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="price" class="form-label">
                            Price
                        </label>
                        <input
                            name="price"
                            type="text"
                            class="form-control mt-2"
                            value="<?= !empty($data->project) ? $data->project->day_rate : ''; ?>"
                            placeholder="Please enter a price if needed"/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="started_at" class="form-label">
                            Started on
                        </label>
                        <input
                            name="started_at"
                            type="text"
                            class="form-control form-control-bordered p-3 datetimepicker"
                            value=""/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="ended_at" class="form-label">
                            Ended on
                        </label>
                        <input
                            name="ended_at"
                            type="text"
                            class="form-control form-control-bordered p-3 datetimepicker"
                            value=""/>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-12 p-0 m-0">
                        <button type="submit" class="btn btn-primary float-right">Save</button>
                        <button type="button" class="btn btn-secondary float-right mr-2" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
                <input type="hidden" name="timesheet_id" value="<?= $data->id; ?>"/>
            </form>
        </div>
    </div>
</div>
<div class="modal" tabindex="-1" id="modal-edit-entry">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editing the entry</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
            <form
                method="post"
                action="">
                <div class="modal-body">
                    <div class="form-group mb-4">
                        Required fields <span class="required">*</span>
                    </div>
                    <div class="form-group mb-4">
                        <label for="title" class="form-label">
                            Title
                            <span class="required">*</span>
                        </label>
                        <input
                            name="title"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a title"
                            required/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="description" class="form-label">
                            Description
                        </label>
                        <input
                            name="description"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a description if needed"/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="price" class="form-label">
                            Price
                        </label>
                        <input
                            name="price"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a price if needed"/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="started_at" class="form-label">
                            Started on
                        </label>
                        <input
                            name="started_at"
                            type="text"
                            class="form-control form-control-bordered p-3 datetimepicker"
                            value=""/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="ended_at" class="form-label">
                            Ended on
                        </label>
                        <input
                            name="ended_at"
                            type="text"
                            class="form-control form-control-bordered p-3 datetimepicker"
                            value=""/>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-12 p-0 m-0">
                        <button type="submit" class="btn btn-primary float-right">Save</button>
                        <button type="button" class="btn btn-secondary float-right mr-2" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>