<?php
/**
 * Groups index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/logs';

$filter_status = $this->tengu->getFilters('status');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=deleted'); ?>" class="card bg-danger">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    Fatal errors
                </div>
                <div class="text-white">
					<strong><?= $stats['danger']; ?></strong> log<?= $stats['danger'] == 1 ? ' is ' : 's are'; ?> fatal errors
				</div>
            </div>
        </a>
    </div>
</div>
<?php
if ($data->total_items) {
    ?>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card p-0">
                <div class="card-body">
                    <button
                        class="btn btn-blank float-right"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/clear'); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Delete all the logs">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16" class="pb-2">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg><br/>
                            delete all
                        </div>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
<div class="row mb-3">
	<div class="col-12">
        <div class="card p-0">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
		        <div class="float-right dropdown">
		            <a 
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
		                        <option value="danger"<?= $filter_status == 'danger' ? ' selected="selected"' : ''; ?>>Fatal error</option>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body p-3">
                <?php
                if ($data->total_items) {
                    ?>
                    <table class="table tablesorter">
                        <thead>
                            <tr>
                                <th width="100px">Type</th>
                                <th width="150px">Resource</th>
                                <th>Summary</th>
                                <th width="150px">Date</th>
                                <th width="100px">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($data->getItems() as $row) {
                                $type = $row->type;

                                switch ($row->type) {
                                    case 'danger':
                                        $bg_colour = 'badge-danger';
                                        $type = 'failed';
                                        break;
                                    case 'error':
                                        $bg_colour = 'badge-danger';
                                        break;
                                    case 'info':
                                        $bg_colour = 'badge-info';
                                        break;
                                    case 'success':
                                        $bg_colour = 'badge-success';
                                        break;
                                    case 'warning':
                                        $bg_colour = 'badge-warning';
                                        break;
                                    default:
                                        $bg_colour = 'badge-primary';
                                        break;
                                }
                                ?>
                                <tr>
                                    <td>
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <span class="badge <?= $bg_colour; ?>"><?= $type; ?></span>
                                        </a>
                                    </td>
                                    <td>
                                        <?php
                                        if ($resource_url = $row->resource_url) {
                                            ?>
                                            <a 
                                                href="<?= UrlHelper::backend($resource_url); ?>"
                                                target="_blank"
                                                class="badge badge-primary"><?= $row->resource; ?></a>
                                            <?php
                                        } else {
                                            ?>
                                            <?= $row->resource; ?>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <?= $row->summary; ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                            <?= DateHelper::prettyFull($row->created_at); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a
                                            href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
                                            class="btn btn-blank float-right p-0"
                                            title="View the log"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 16 16">
                                                <path d="M6 9a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3A.5.5 0 0 1 6 9zM3.854 4.146a.5.5 0 1 0-.708.708L4.793 6.5 3.146 8.146a.5.5 0 1 0 .708.708l2-2a.5.5 0 0 0 0-.708l-2-2z"/>
                                                <path d="M2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h12z"/>
                                            </svg>
                                        </a>
                                        <button
                                            type="button"
                                            class="btn btn-blank float-right p-0 mr-2"
                                            data-original-title="Are you sure?"
                                            data-trigger="focus"
                                            data-html="true"
                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                            data-toggle="popover">
                                            <span
                                                title="Delete the log"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                            </span>
                                        </button>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                    <?php
                } else {
                    ?>
                    <strong class="h5">No results</strong>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
