<?php
/**
 * Users edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/users';
$statement_url = ($this->di->getConfig())->urls->fms . '/statements';
$tax_codes_url = ($this->di->getConfig())->urls->fms . '/user-tax-codes';
echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-primary">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1">
                    <?= $data->type; ?>
                </div>
                <div class="text-white">
                    Type
                </div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8Zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022ZM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816ZM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275ZM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0Zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1">
                    <?= $data->group->name; ?>
                </div>
                <div class="text-white">
                    Group
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
<?php
if ($data->dividends->count()) {
    ?>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1">
                    <?= NumberHelper::toCurrency($data->dividends_current_year_amount); ?>
                </div>
                <div class="text-white">
                    Dividends this year
                </div>
            </div>
        </div>
    </div>
    <?php
}
if ($data->payments->count()) {
    ?>
    <div class="col-3">
        <div class="card bg-warning">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1">
                    <?= NumberHelper::toCurrency($data->payments_current_year_amount); ?>
                </div>
                <div class="text-white">
                    Payments this year
                </div>
            </div>
        </div>
    </div>
    <?php
}
if ($data->expenses->count()) {
    ?>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1">
                    <?= NumberHelper::toCurrency($data->expenses_current_year_amount); ?>
                </div>
                <div class="text-white">
                    Expenses this year
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
</div>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>" enctype="multipart/form-data">
    <div class="row mb-3">
		<div class="col-12">
			<div class="card p-0">
				<div class="card-body">
					<a
						href="<?= UrlHelper::backend($url); ?>"
						class="btn btn-blank mr-2 text-center"
						title="Go back to the users list"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="bottom">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
							<path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
						</svg><br/>
						back
					</a>
					<button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save the user"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
					<a
						href="<?= UrlHelper::backend($url . '/add'); ?>"
						class="btn btn-blank float-right"
						title="Add a new user"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
							<path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
							<path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
						</svg><br/>
						new
					</a>
					<?php
					if ($data->status == 'deleted') {
						?>
						<button
							class="btn btn-blank float-right"
							type="button"
							data-original-title="Are you sure?"
							data-html="true"
							data-trigger="focus"
							data-toggle="popover"
							data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
							<div
								data-toggle="tooltip"
								data-dismiss="hover"
								data-placement="top"
								title="Recover the user from the trash">
								<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
									<path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
								</svg><br/>
								recover
							</div>
						</button>
						<?php
					} else {
					?>
						<button
							class="btn btn-blank float-right"
							type="button"
							data-original-title="Are you sure?"
							data-html="true"
							data-trigger="focus"
							data-toggle="popover"
							data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
							<div
								data-toggle="tooltip"
								data-dismiss="hover"
								data-placement="top"
								title="Throw the user into the trash">
								<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
									<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
									<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
								</svg><br/>
								delete
							</div>
						</button>
						<?php
					}
					?>
				</div>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div class="preview-img">
								<div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
								</div>
                                <?php
                                switch ($data->status) {
                                    case 'active':
                                        $label = "I'm live!";
                                        $bg_colour = 'bg-success';
                                        break;
                                    case 'inactive':
                                        $label = "I'm inactive";
                                        $bg_colour = 'bg-warning';
                                        break;
                                    case 'deleted':
                                        $label = "I'm in a deleted state";
                                        $bg_colour = 'bg-danger';
                                        break;
                                    default:
                                        break;
                                }
                                ?>
                                <div title="<?= $label; ?>" class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label for="first_name">
                                            First name
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="first_name"
                                            name="first_name"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="first_name"
                                            value="<?= FormController::getFormData('first_name', $data); ?>"
                                            required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="email">
                                            Email
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="email"
                                            name="email"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="email"
                                            value="<?= FormController::getFormData('email', $data); ?>"
                                            required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="type">
                                            Type
                                            <span class="required">*</span>
                                        </label>
                                        <select
                                            name="type"
                                            class="form-control mt-2"
                                            tabindex="-1"
                                            aria-hidden="true"
                                            required>
                                            <?php
                                            $selected = FormController::getFormData('type', $data);
                                            foreach ($types as $type) {
                                                ?>
                                                <option value="<?= $type; ?>" <?= $selected == $type ? 'selected' : '';?>>
                                                    <?= $type; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label for="last_name">
                                            Last name
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="last_name"
                                            name="last_name"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="last_name"
                                            value="<?= FormController::getFormData('last_name', $data); ?>"
                                            required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="group_id">
                                            Group
                                            <span class="required">*</span>
                                        </label>
                                        <select
                                            name="group_id"
                                            class="form-control mt-2"
                                            tabindex="-1"
                                            aria-hidden="true"
                                            required>
                                            <?php
                                            $selected = FormController::getFormData('group_id', $data);
                                            if (count($groups)) {
                                                foreach ($groups as $group) {
                                                    ?>
                                                    <option value="<?= $group['id']; ?>" <?= $selected == $group['id'] ? 'selected' : '';?>>
                                                        <?= $group['name'] . ' (' . $group['status'] . ')'; ?>
                                                    </option>
                                                    <?php
                                                }
                                            } else {
                                                ?>
                                                <option value="">No groups</option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('contact-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#contact-tab">
                                Contact
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('employee-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#employee-tab">
                                Employee details
                            </a>
                        </li>
                        <?php
                        if (($this->di->getConfig())->apps->wako) {
                            ?>
                            <li class="nav-item mt-2">
                                <a
                                    class="nav-link <?= UrlHelper::activeTab('payments-tab', 'overview-tab'); ?>"
                                    data-toggle="tab"
                                    role="tab"
                                    href="#payments-tab">
                                    Payments
                                    <?php
                                    if ($payments_count = $data->payments->count()) {
                                        ?>
                                        <span class="badge badge-primary"><?= $payments_count; ?></span>
                                        <?php
                                    }
                                    ?>
                                </a>
                            </li>
                            <li class="nav-item mt-2">
                                <a
                                    class="nav-link <?= UrlHelper::activeTab('expenses-tab', 'overview-tab'); ?>"
                                    data-toggle="tab"
                                    role="tab"
                                    href="#expenses-tab">
                                    Expenses
                                    <?php
                                    if ($expenses_count = $data->expenses->count()) {
                                        ?>
                                        <span class="badge badge-primary"><?= $expenses_count; ?></span>
                                        <?php
                                    }
                                    ?>
                                </a>
                            </li>
                            <li class="nav-item mt-2">
                                <a
                                    class="nav-link <?= UrlHelper::activeTab('dividends-tab', 'overview-tab'); ?>"
                                    data-toggle="tab"
                                    role="tab"
                                    href="#dividends-tab">
                                    Dividends
                                    <?php
                                    if ($divs_count = $data->dividends->count()) {
                                        ?>
                                        <span class="badge badge-primary"><?= $divs_count; ?></span>
                                        <?php
                                    }
                                    ?>
                                </a>
                            </li>
                            <?php
                        }
                        ?>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Security</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="password">
                                            Password
                                        </label>
                                        <input
                                            id="password"
                                            name="password"
                                            type="password"
                                            class="form-control mt-2"
                                            aria-describedby="password"
                                            value="">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="password_check">
                                            Password check
                                        </label>
                                        <input
                                            id="password_check"
                                            name="password_check"
                                            type="password"
                                            class="form-control mt-2"
                                            aria-describedby="password_check"
                                            value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Profile picture</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <?php
                                    if ($data->profile_image) {
                                        ?>
                                        <div class="form-group float-left mr-4">
                                            <span class="profile-pic">
                                                <img src="<?= $data->profile_image->url; ?>">
                                            </span>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                    <div class="form-group mb-4 float-left">
                                        <label for="upload_picture">
                                            Upload picture
                                        </label>
                                        <input
                                            id="upload_picture"
                                            name="upload_picture"
                                            type="file"
                                            accept="image/jpeg, image/png, capture=camera"
                                            class="form-control mt-2">
                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('contact-tab', 'overview-tab'); ?>"
                    id="contact-tab"
                    role="tabpanel"
                    aria-labelledby="contact-tab">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Address</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="address_line_1">
                                            Address line 1
                                        </label>
                                        <input
                                            id="address_line_1"
                                            name="address_line_1"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="address_line_1"
                                            value="<?= FormController::getFormData('address_line_1', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="address_line_2">
                                            Address line 2
                                        </label>
                                        <input
                                            id="address_line_2"
                                            name="address_line_2"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="address_line_2"
                                            value="<?= FormController::getFormData('address_line_2', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="town">
                                            Town/City
                                        </label>
                                        <input
                                            id="town"
                                            name="town"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="town"
                                            value="<?= FormController::getFormData('town', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="county">
                                            County/State
                                        </label>
                                        <input
                                            id="county"
                                            name="county"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="county"
                                            value="<?= FormController::getFormData('county', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="country">
                                            Country
                                        </label>
                                        <input
                                            id="country"
                                            name="country"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="country"
                                            value="<?= FormController::getFormData('country', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="postcode">
                                            Postcode
                                        </label>
                                        <input
                                            id="postcode"
                                            name="postcode"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="postcode"
                                            value="<?= FormController::getFormData('postcode', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Phone</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="phone">
                                            Phone
                                        </label>
                                        <input
                                            id="phone"
                                            name="phone"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="phone"
                                            value="<?= FormController::getFormData('phone', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('employee-tab', 'overview-tab'); ?>"
                    id="employee-tab"
                    role="tabpanel"
                    aria-labelledby="employee-tab">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Employee details</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="employee_ref">
                                            Employee reference
                                        </label>
                                        <input
                                            id="employee_ref"
                                            name="employee_ref"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="employee_ref"
                                            value="<?= FormController::getFormData('employee_ref', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="dob">
                                            Date of birth
                                        </label>
                                        <input
                                            id="dob"
                                            name="dob"
                                            type="text"
                                            class="form-control mt-2 datepicker"
                                            aria-describedby="dob"
                                            value="<?= DateHelper::pretty(FormController::getFormData('dob', $data), false); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="national_insurance">
                                            National insurance no.
                                        </label>
                                        <input
                                            id="national_insurance"
                                            name="national_insurance"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="national_insurance"
                                            value="<?= FormController::getFormData('national_insurance', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="utr">
                                            UTR
                                        </label>
                                        <input
                                            id="utr"
                                            name="utr"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="utr"
                                            value="<?= FormController::getFormData('utr', $data); ?>">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="upload_picture">
                                            Upload signature
                                        </label>
                                        <input
                                            id="upload_sig"
                                            name="upload_sig"
                                            type="file"
                                            accept="image/jpeg, image/png, capture=camera"
                                            class="form-control mt-2">
                                        <?php
                                        if ($data->sig) {
                                            ?>
                                            <small>Signature has been uploaded</small>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Add tax code</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="tax_year_id">
                                            Tax year
                                        </label>
                                        <select
                                            name="tax_year_id"
                                            class="form-control mt-2"
                                            data-placeholder="Please select a tax year"
                                            tabindex="-1"
                                            aria-hidden="true">
                                            <option value="">None selected</option>
                                            <?php
                                            foreach ($tax_years as $year) {
                                                ?>
                                                <option value="<?= $year->id; ?>">
                                                    <?= $year->code; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="tax_code">
                                            Code
                                        </label>
                                        <input
                                            id="tax_code"
                                            name="tax_code"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="tax_code"
                                            value="<?= FormController::getFormData('tax_code', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Tax codes</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Year</th>
                                                <th>Code</th>
                                                <th width="120px">&nbsp;</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            foreach ($data->tax_codes as $row) {
                                                ?>
                                                <tr>
                                                    <td><?= $row->tax_year->code; ?></td>
                                                    <td><?= $row->code; ?></td>
                                                    <td>
                                                        <button
                                                            type="button"
                                                            class="btn btn-blank float-right"
                                                            data-original-title="Are you sure?"
                                                            data-trigger="focus"
                                                            data-html="true"
                                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($tax_codes_url . '/delete/' . $row->id); ?>?from=<?= urlencode($url . '/edit/' . $data->id); ?>">Yes</a>'
                                                            data-toggle="popover">
                                                            <span
                                                                title="Delete the code"
                                                                data-toggle="tooltip"
                                                                data-trigger="hover"
                                                                data-dismiss="click"
                                                                data-placement="top">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                                </svg>
                                                            </span>
                                                        </button>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('payments-tab', 'overview-tab'); ?>"
                    id="payments-tab"
                    role="tabpanel"
                    aria-labelledby="payments-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if ($data->payments->count()) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th width="160px">Processed at</th>
                                                    <th>Description</th>
                                                    <th width="200px">Out (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th width="160px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            foreach ($data->payments as $row) {
                                                ?>
                                                <tr <?= $row->deleted_at ? ' class="text-danager text-strikethrough"' : '';?>>
                                                    <td class="align-top">
                                                        <?= DateHelper::pretty($row->processed_at, false); ?><br/>
                                                        <?php
                                                        if (!empty($row->tax_year)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                                                <span class="badge badge-primary">
                                                                    <?= $row->tax_year->code; ?>
                                                                </span>
                                                            </a>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <span class="badge badge-danger">
                                                                none
                                                            </span>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <p><?= nl2br($row->description); ?></p>
                                                        <?php
                                                        if (!empty($row->tags)) {
                                                            foreach ($row->tags as $tag) {
                                                                ?>
                                                                <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                                                                <?php
                                                            }
                                                        }
                                                        if (!empty($row->shareholder)) {
                                                            ?>
                                                            <span class="float-left badge badge-primary mr-2 mt-2">Shareholder payment to <?= $row->shareholder->full_name; ?></span>
                                                            <?php                                                            
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top"><?= NumberHelper::toCurrency($row->out); ?></td>
                                                    <td class="align-top">
                                                        <a
                                                            href="<?= UrlHelper::backend($statement_url . '/' . $row->statement_id . '/items/edit/' . $row->id, 'here'); ?>"
                                                            class="btn btn-blank float-right"
                                                            title="Edit the item"
                                                            data-toggle="tooltip"
                                                            data-trigger="hover"
                                                            data-dismiss="click"
                                                            data-placement="top">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                            </svg>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                            <?php
                                    } else {
                                        ?>
                                        <strong class="h4">No items</strong>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('expenses-tab', 'overview-tab'); ?>"
                    id="expenses-tab"
                    role="tabpanel"
                    aria-labelledby="expenses-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if ($data->expenses->count()) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th width="160px">Processed at</th>
                                                    <th>Description</th>
                                                    <th width="200px">Out (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th width="160px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            foreach ($data->expenses as $row) {
                                                ?>
                                                <tr <?= $row->deleted_at ? ' class="text-danager text-strikethrough"' : '';?>>
                                                    <td class="align-top">
                                                        <?= DateHelper::pretty($row->processed_at, false); ?><br/>
                                                        <?php
                                                        if (!empty($row->tax_year)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                                                <span class="badge badge-primary">
                                                                    <?= $row->tax_year->code; ?>
                                                                </span>
                                                            </a>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <span class="badge badge-danger">
                                                                none
                                                            </span>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <p><?= nl2br($row->description); ?></p>
                                                        <?php
                                                        if (!empty($row->tags)) {
                                                            foreach ($row->tags as $tag) {
                                                                ?>
                                                                <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                                                                <?php
                                                            }
                                                        }
                                                        if (!empty($row->shareholder)) {
                                                            ?>
                                                            <span class="float-left badge badge-primary mr-2 mt-2">Shareholder payment to <?= $row->shareholder->full_name; ?></span>
                                                            <?php                                                            
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top"><?= NumberHelper::toCurrency($row->out); ?></td>
                                                    <td class="align-top">
                                                        <a
                                                            href="<?= UrlHelper::backend($statement_url . '/' . $row->statement_id . '/items/edit/' . $row->id, 'here'); ?>"
                                                            class="btn btn-blank float-right"
                                                            title="Edit the item"
                                                            data-toggle="tooltip"
                                                            data-trigger="hover"
                                                            data-dismiss="click"
                                                            data-placement="top">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                            </svg>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                            <?php
                                    } else {
                                        ?>
                                        <strong class="h4">No items</strong>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('dividends-tab', 'overview-tab'); ?>"
                    id="dividends-tab"
                    role="tabpanel"
                    aria-labelledby="dividends-tab">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Shareholder</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="shareholder">
                                            Shareholder (&percnt;)
                                        </label>
                                        <input
                                            id="shareholder"
                                            name="shareholder"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="shareholder"
                                            value="<?= FormController::getFormData('shareholder', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body p-4">
                                    <?php
                                    if ($data->dividends->count()) {
                                        ?>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th width="160px">Processed at</th>
                                                    <th>Description</th>
                                                    <th width="200px">Out (<?= NumberHelper::currencySymbol(); ?>)</th>
                                                    <th width="160px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            foreach ($data->dividends as $row) {
                                                ?>
                                                <tr <?= $row->deleted_at ? ' class="text-danager text-strikethrough"' : '';?>>
                                                    <td class="align-top">
                                                        <?= DateHelper::pretty($row->processed_at, false); ?><br/>
                                                        <?php
                                                        if (!empty($row->tax_year)) {
                                                            ?>
                                                            <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                                                <span class="badge badge-primary">
                                                                    <?= $row->tax_year->code; ?>
                                                                </span>
                                                            </a>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <span class="badge badge-danger">
                                                                none
                                                            </span>
                                                            <?php
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top">
                                                        <p><?= nl2br($row->description); ?></p>
                                                        <?php
                                                        if (!empty($row->tags)) {
                                                            foreach ($row->tags as $tag) {
                                                                ?>
                                                                <span class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></span>
                                                                <?php
                                                            }
                                                        }
                                                        if (!empty($row->shareholder)) {
                                                            ?>
                                                            <span class="float-left badge badge-primary mr-2 mt-2">Shareholder payment to <?= $row->shareholder->full_name; ?></span>
                                                            <?php                                                            
                                                        }
                                                        ?>
                                                    </td>
                                                    <td class="align-top"><?= NumberHelper::toCurrency($row->out); ?></td>
                                                    <td class="align-top">
                                                        <a
                                                            href="<?= UrlHelper::backend($statement_url . '/' . $row->statement_id . '/items/edit/' . $row->id, 'here'); ?>"
                                                            class="btn btn-blank float-right"
                                                            title="Edit the item"
                                                            data-toggle="tooltip"
                                                            data-trigger="hover"
                                                            data-dismiss="click"
                                                            data-placement="top">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                                <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                            </svg>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                            <?php
                                    } else {
                                        ?>
                                        <strong class="h4">No items</strong>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="card">
                        <div class="card-header m-0">
                            <span class="card-title">Notes</span>
                        </div>
                        <div class="card-body">
                            <?= $this->partial(
                                'common/notes/list',
                                [
                                    'notes' => $data->notes,
                                    'url' => $url . '/edit/' . $data->id . '?clear=true#notes-tab'
                                ]
                            ); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
