<?php
/**
 * Login template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/login';
if (!empty($_GET['from'])) {
	$url .= '?from=' . $_GET['from'];
}
?>
<div class="d-flex justify-content-center pt-5">
    <div class="col-10 col-lg-6">
        <?= $this->partial("errors/form"); ?>
        <form class="card p-2" method="post" novalidate="novalidate" action="<?= UrlHelper::backend($url); ?>">
            <div class="card-header">
                <span class="card-title">Welcome, please login</span>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>
                        Email
                        <span class="required">*</span>
                    </label>
                    <input
						type="text"
						class="form-control mt-2"
						name="email"
						placeholder="Please enter your email"
						autocomplete="off"
						tabindex="1"
						required>
                </div>
                <div class="form-group">
                    <label>
                        Password
                        <span class="required">*</span>
                    </label>
                    <input
						type="password"
						class="form-control mt-2"
						name="password"
						placeholder="Please enter your password"
						autocomplete="off"
						tabindex="2"
						required>
                </div>
                <div class="form-group">
                    <label>
                        Please complete the captcha
                        <span class="required">*</span>
                    </label>
                    <div class="captcha">
                        <?= $this->tengu->captcha(); ?>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">login</button>
            </div>
            <input name="_TSC" type="hidden" value="<?= FormController::generateTSC(); ?>">
        </form>
    </div>
</div>
