<?php
/**
 * User profile template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/users';

echo $this->partial("common/form/messages");
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/profile-save'); ?>" enctype="multipart/form-data">
	<div class="row mb-3">
		<div class="col-12">
            <div class="card p-0">
				<div class="card-body">
					<button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save my page"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
				</div>
			</div>
		</div>
	</div>
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div
                                    class="preview-img"
                                    title="I'm inactive"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                    <?php
                                    switch ($data->status) {
                                        case 'active':
                                            $label = "I'm live!";
                                            $bg_colour = 'bg-success';
                                            break;
                                        case 'inactive':
                                            $label = "I'm inactive";
                                            $bg_colour = 'bg-warning';
                                            break;
                                        case 'deleted':
                                            $label = "I'm in a deleted state";
                                            $bg_colour = 'bg-danger';
                                            break;
                                        default:
                                            break;
                                    }
                                    ?>
                                    <div
                                        title="<?= $label; ?>"
                                        class="position-absolute circle border border-white <?= $bg_colour; ?>"
                                        style="width: 10px;height: 10px;margin-top: -5px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label for="first_name">
                                            First name
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="first_name"
                                            name="first_name"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="first_name"
                                            value="<?= FormController::getFormData('first_name', $data); ?>"
                                            required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="email">
                                            Email
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="email"
                                            name="email"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="email"
                                            value="<?= FormController::getFormData('email', $data); ?>"
                                            required>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label for="last_name">
                                            Last name
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="last_name"
                                            name="last_name"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="last_name"
                                            value="<?= FormController::getFormData('last_name', $data); ?>"
                                            required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="job_title">
                                            Job title
                                        </label>
                                        <input
                                            id="job_title"
                                            name="job_title"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="job_title"
                                            value="<?= FormController::getFormData('job_title', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Security</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="password">
                                            Password
                                        </label>
                                        <input
                                            id="password"
                                            name="password"
                                            type="password"
                                            class="form-control mt-2"
                                            aria-describedby="password"
                                            value="<?= FormController::getFormData('password'); ?>">
                                        <small>Leave this blank if you'd like the user to set their own</small>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="password">
                                            Password check
                                        </label>
                                        <input
                                            id="password"
                                            name="password"
                                            type="password"
                                            class="form-control mt-2"
                                            aria-describedby="password"
                                            value="<?= FormController::getFormData('password'); ?>">
                                        <small>Leave this blank if you'd like the user to set their own</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header mb-2">
                                    <span class="card-title">Profile picture</span>
                                </div>
                                <div class="card-body p-3 pt-0">
                                    <div class="form-group mb-4">
                                        <label for="upload_picture">
                                            Upload picture
                                        </label>
                                        <input
                                            id="upload_picture"
                                            name="upload_picture"
                                            type="file"
                                            accept="image/jpeg, image/png, capture=camera"
                                            class="form-control mt-2">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
