<?php
/**
 * Form messages template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;

$output = false;
$status = '';
if (!empty($data)) {
    if (!empty($data->status)) {
        $status = $data->status;
    }
}

echo $this->partial("errors/form");

if ($message = FormController::getFormSaved()) {
    $output = true;
    ?>
    <div class="alert alert-success d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="mb-1">Yay!</h4>
            <p><?= is_bool($message) ? 'Entry successfully saved' : $message;?></p>
        </div>
    </div>
    <?php
}

if ($message = FormController::getFormUpdated()) {
    $output = true;
    ?>
    <div class="alert alert-success d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="mb-1">Yay!</h4>
            <p><?= is_bool($message) ? 'Entry successfully updated' : $message;?></p>
        </div>
    </div>
    <?php
}

if ($message = FormController::getFormDeleted()) {
    $output = true;
    ?>
    <div class="alert alert-warning d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="mb-1">Off to the trash</h4>
            <p><?= is_bool($message) ? 'Entry successfully deleted' : $message;?></p>
        </div>
    </div>
    <?php
}

if ($message = FormController::getFormWarning()) {
    $output = true;
    ?>
    <div class="alert alert-warning d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="mb-1">Warning</h4>
            <p><?= $message;?></p>
        </div>
    </div>
    <?php
}

if ($status == 'deleted') {
    $output = true;
    ?>
    <div class="alert alert-danger d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="mb-1">I'm in a deleted state</h4>
            <p>Don't worry I can be recovered, just click the recover button above</p>
        </div>
    </div>
    <?php
}

if ($output) {
    echo '<div class="row"><div class="col-12 mb-3"></div></div>';
}
?>
