<?php
/**
 * List pagination template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Helpers\UrlHelper;

if (empty($data)) {
	return;
}

$limits = [30,100,250];
$limit = !empty($data->limit) ? intval($data->limit) : 30;
if (!empty($_GET['limit']) && in_array(intval($_GET['limit']), $limits)) {
    $limit = intval($_GET['limit']);
}

$start = intval($data->current / 5) * 5;
if ($start <= 0) {
    $start = 1;
}

$result_start = (($start - 1) * $limit) + 1;

$end = $start + 4;
$result_end = (($end - 1) * $limit) + 1;

if ($end > $data->last) {
    $end = $data->last;
    $result_end = $data->total_items;
}

if ($result_end == 0) {
	$result_start = 0;
}

if ($result_start) {
?>
<div class="row">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
				<div class="row mt-2 mb-2">
				    <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
				        <div>
				            Showing <?= $result_start; ?> to <?= $result_end; ?> of <?= $data->total_items; ?> entries
				        </div>
				    </div>
					<?php
					if ($result_start) {
						?>
					    <div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end">
					        <div class="d-flex mr-2">
					            <select id="limit" name="per_page" class="form-control form-control-solid select-per-page">
					            <?php
					            foreach ($limits as $value) {
					                ?>
					                <option value="<?= $value; ?>" <?= $limit == $value ? 'selected' :''; ?>>
					                    <?= $value; ?>
					                </option>
					                <?php
					            }
					            ?>
					            </select>
					        </div>
					        <div class="d-flex">
					            <ul class="pagination">
					                <li class="page-item previous <?= $data->current == $data->first ? ' disabled' : ''; ?>">
					                    <a href="<?= UrlHelper::generate($url, ['page' => $data->current - 1 > $data->first ? $data->current - 1 : $data->first]); ?>" class="page-link">
					                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
					                            <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
					                        </svg>
					                    </a>
					                </li>
					                <?php
					                for ($iLoop = $start; $iLoop <= $end; $iLoop++) {
					                    ?>
					                    <li class="page-item <?= $data->current == $iLoop ? 'active' :''; ?><?= $start == $end ? ' disabled text-muted' : ''; ?>">
					                        <a href="<?= UrlHelper::generate($url, ['page' => $iLoop]); ?>" class="page-link"><?= $iLoop; ?></a>
					                    </li>
					                    <?php
					                }
					                ?>
					                <li class="page-item next <?= $data->current == $data->last ? ' disabled text-muted' : ''; ?>">
					                    <a href="<?= UrlHelper::generate($url, ['page' => $data->current + 1 < $data->last ? $data->current + 1 : $data->last]); ?>" class="page-link">
					                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
					                            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
					                        </svg>
					                    </a>
					                </li>
					            </ul>
					        </div>
				    	</div>
						<?php
					}
					?>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?= $this->tengu->theme->getAsset('js/core/pagination.js'); ?>"></script>
<?php
}
?>
