<?php
/**
 * List search template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Helpers\UrlHelper;
?>
<form method="get" action="<?= UrlHelper::backend($url); ?>" class="float-left col-5 p-0">
    <input
        type="text"
        name="search"
        class="form-control input-search float-left"
        placeholder="Search"
        value="<?= !empty($_GET['search']) ? $_GET['search'] : ''; ?>">
    <?php
    if (!empty($_GET['search'])) {
        ?>
        <a
            href="<?= UrlHelper::backend($url); ?>"
            title="Clear the search"
            class="btn btn-clear-search float-left">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
            </svg>
        </a>
        <?php
    }
    ?>
</form>
