<?php
/**
 * List sorting template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

if (empty($name)) {
    $name = 'name';
}
$filters = $this->tengu->getFilters();
$filter_sort = !empty($filters['order_by']) ? $filters['order_by'] : $name;
?>
<label class="form-label fw-bold">Sort:</label>
<select
    id="filters_order_by"
    name="filters[order_by]"
    class="form-control form-control-solid"
    tabindex="-1"
    aria-hidden="true">
    <option
        value="<?= $name; ?>|ASC"
        <?= ($filter_sort == $name . '|ASC') ? ' selected="selected"' :''; ?>>
        A-Z
    </option>
    <option
        value="<?= $name; ?>|DESC"
        <?= ($filter_sort == $name . '|DESC') ? ' selected="selected"' :''; ?>>
        Z-A
    </option>
    <option
        value="created_at|DESC"
        <?= ($filter_sort == 'created_at|DESC') ? ' selected="selected"' :''; ?>>
        Newest
    </option>
    <option
        value="created_at|ASC"
        <?= ($filter_sort == 'created_at|ASC') ? ' selected="selected"' :''; ?>>
        Oldest
    </option>
</select>
