<?php
if (!empty($page->banner_image)) {
    ?>
    <div class="page-background-image">
        <img src="<?= $page->banner_image->url; ?>" alt="<?= $page->banner_image->label; ?>">
    </div>
    <?php
}
?>
<div class="container">
    <div id="page-content" class="row mt-5 mb-5">
        <div class="col-12">
            <div class="page-title">
                <h2>
                    <a onclick="window.history.back();" class="btn btn-primary">&lt;</a>&nbsp;&nbsp;OH NO!
                </h2>
            </div>
            <section class="card">
                <div class="card-body">
                    <?= (!empty($message) ? $message : 'Something major has gone wrong'); ?>
                </div>
            </section>
        </div>
    </div>
</div>
