<?php
/**
 * Invoices index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->fms . '/invoices';

$filter_status = $this->tengu->getFilters('status');
$filter_direction = $this->tengu->getFilters('direction');
$filter_year = $this->tengu->getFilters('year');
$filter_project = $this->tengu->getFilters('project');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
					<?= NumberHelper::toCurrency($stats['incoming']); ?>
				</div>
                <div class="text-white">
					Incoming this tax year
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
					<?= NumberHelper::toCurrency($stats['outgoing']); ?>
				</div>
                <div class="text-white">
					Outgoing this tax year
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-warning">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['vat']); ?>
				</div>
                <div class="text-white">
					<?= NumberHelper::taxLabel($this->tengu->settings->finance->currency); ?>
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-dark">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
					<?= $stats['unpaid']; ?>
				</div>
                <div class="text-white">
					Unpaid
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
        <div class="card p-0">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
				<a href="<?= UrlHelper::backend($url . '/create'); ?>" class="btn btn-primary float-right">
		            Create
		        </a>
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
                            <?php
                                $this->partial('common/lists/sorting', ['url' => $url]);
                            ?>
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($statuses as $status) {
                                    ?>
                                    <option value="<?= $status; ?>"<?= $filter_status == $status ? ' selected="selected"' : ''; ?>>
                                        <?= $status; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
                            <label class="form-label fw-bold">Direction:</label>
		                    <select
		                        name="filters[direction]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($directions as $direction) {
                                    ?>
                                    <option value="<?= $direction; ?>"<?= $filter_direction == $direction ? ' selected="selected"' : ''; ?>>
                                        <?= $direction; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
                            <label class="form-label fw-bold">Tax year:</label>
		                    <select
		                        name="filters[year]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($years as $year) {
                                    ?>
                                    <option value="<?= $year->id; ?>"<?= $filter_year == $year->id ? ' selected="selected"' : ''; ?>>
                                        <?= $year->code; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
                            <label class="form-label fw-bold">Project:</label>
		                    <select
		                        name="filters[project]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($projects as $project) {
                                    ?>
                                    <option value="<?= $project->id; ?>"<?= $filter_project == $project->id ? ' selected="selected"' : ''; ?>>
                                        <?= $project->name; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>				
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
    <div class="col-12"><path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
        <div class="card">
            <div class="card-body p-3">
            <?php
            if ($data->total_items) {
                ?>
                <table class="table tablesorter">
                    <thead>
                        <tr>
                            <th>Tax year</th>
                            <th>Name</th>
                            <th width="180px">Ref</th>
                            <th width="150px">
                                Amount/<?= NumberHelper::taxLabel($this->tengu->settings->finance->currency); ?>
                            </th>
                            <th width="150px">Issued on</th>
                            <th width="150px">Direction</th>
                            <th width="100px">Status</th>
                            <th width="250px">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($data->getItems() as $row) {
                            switch ($row->status) {
                                case 'paid':
                                    $bg_colour = 'success';
                                    break;
                                default:
                                    $bg_colour = 'danger';
                                    break;
                            }
                            ?>
                            <tr>
                                <td class="align-top">
                                    <?php
                                    if (!empty($row->tax_year)) {
                                        ?>
                                        <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[year]=' . $row->tax_year->id)); ?>">
                                            <span class="badge badge-primary">
                                                <?= $row->tax_year->code; ?>
                                            </span>
                                        </a>
                                        <?php
                                    } else {
                                        ?>
                                        <span class="badge badge-danger">
                                            none
                                        </span>
                                        <?php
                                    }
                                    ?>
                                </td>
                                <td class="align-top">
                                    <a class="float-left w-100" href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                        <?= $row->name; ?>
                                    </a>
                                    <?php
                                    if ($row->tags->count()) {
                                        foreach ($row->tags as $tag) {
                                        ?>
                                        <a href="<?= UrlHelper::backend($url . '?search=' . $tag->tag); ?>" class="float-left badge badge-primary mr-2 mt-2"><?= $tag->tag; ?></a>
                                        <?php
                                        }
                                    }
                                    if ($row->project) {
                                        ?>
                                        <p class="w-100 float-left">
                                            <a href="<?= UrlHelper::backend($url . '?filters[project]=' . $row->project->id); ?>" class="float-left badge badge-info mr-2 mt-2">Project: <?= $row->project->name; ?></a>
                                        </p>
                                        <?php
                                    }
                                    ?>
                                </td>
                                <td class="align-top">
                                    <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                    <?php
                                    if ($row->ref) {
                                        ?>
                                        <span class="badge badge-primary">
                                            <?= $row->ref; ?>
                                        </span>
                                        <?php
                                    }
                                    ?>
                                    </a>
                                </td>
                                <td class="align-top">
                                    <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                        <span class="badge badge-<?= $row->direction == 'outgoing' ? 'danger' : 'success'; ?>">
                                            <?= NumberHelper::toCurrency($row->amount, $row->currency); ?>
                                        </span><br/><br/>
                                        <span 
                                            class="badge badge-warning"
                                            title="<?= NumberHelper::taxLabel($row->currency); ?> amount"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="top">
                                            <?= NumberHelper::toCurrency($row->vat, $row->currency); ?>
                                        </span>
                                    </a>
                                </td>
                                <td class="align-top">
                                    <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                        <span class="badge badge-warning">
                                            <?= DateHelper::pretty($row->issued_on, false); ?>
                                        </span>
                                    </a>
                                </td>
                                <td class="align-top">
                                    <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                        <span class="badge badge-<?= $row->direction == 'outgoing' ? 'danger' : 'success'; ?>">
                                            <?= $row->direction ?>
                                        </span>
                                    </a>
                                </td>
                                <td class="align-top">
                                    <a href="<?= UrlHelper::backend(UrlHelper::append($url, 'filters[status]=' . $row->status)); ?>">
                                        <span class="badge badge-<?= $bg_colour; ?>">
                                            <?= $row->status ?>
                                        </span>
                                    </a>
                                </td>
                                <td class="align-top">
                                    <a
                                        href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
                                        class="btn btn-blank float-right"
                                        title="Edit the receipt"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                        </svg>
                                    </a>
                                    <?php
                                    if (!empty($row->file)) {
                                        ?>
                                        <a
                                            href="<?= UrlHelper::backend($row->file->download_url); ?>"
                                            class="btn btn-blank float-right"
                                            title="Download the file"
                                            target="_blank"
                                            data-toggle="tooltip"
                                            data-trigger="hover"
                                            data-dismiss="click"
                                            data-placement="top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                                            </svg>
                                        </a>
                                        <?php
                                    }
                                    if (!$row->deleted_at) {
                                        ?>
                                        <button
                                            type="button"
                                            class="btn btn-blank float-right"
                                            data-original-title="Are you sure?"
                                            data-trigger="focus"
                                            data-html="true"
                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                            data-toggle="popover">
                                            <span
                                                title="Delete the receipt"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                            </span>
                                        </button>
                                        <?php
                                    } else {
                                        ?>
                                        <button
                                            type="button"
                                            class="btn btn-blank float-right"
                                            data-original-title="Are you sure?"
                                            data-trigger="focus"
                                            data-html="true"
                                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                            data-toggle="popover">
                                            <span
                                                title="Recover the receipt"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                                </svg>
                                            </span>
                                        </button>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <?php
            }  else {
                ?>
                <strong class="h5">No results</strong>
                <?php
            }
            ?>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
