<?php
/**
 * Page sections for SEO template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Controllers\KeywordsController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$tags = '';
if (!empty($data)) {
	$tags = (new FormController())->tagsToString($data->tags);
}
?>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header mb-2">
				<span class="card-title">How to find me</span>
            </div>
            <div class="card-body p-3 pt-0">
                <div class="form-group mb-4">
                    <label for="url" class="form-label">URL</label>
                    <input
                        id="url"
                        name="url"
                        type="text"
                        class="form-control mt-2"
                        value="<?= FormController::getFormData('url', $data); ?>"
                        placeholder="Enter a URL if required"/>
                    <small>If you don't enter one then I'll create one for you</small>
                </div>
                <div class="form-group mb-4">
                    <label for="canonical_url" class="form-label">Canonical URL</label>
                    <input
                        id="canonical_url"
                        name="canonical_url"
                        type="text"
                        class="form-control mt-2"
                        value="<?= FormController::getFormData('canonical_url', $data); ?>"
                        placeholder="Enter a canonical URL if required"/>
                    <small>If you don't enter one then I'll create one for you</small>
                </div>
				<div class="form-group form-check mt-0 mb-4">
					<label for="searchable">Searchable</label>
					<div class="checkbox switcher mt-2">
						<label>
							<input
								id="searchable"
								type="checkbox"
								name="searchable"
								value="<?= FormController::getFormData('searchable', $data, ($add ? true : null)); ?>"
								<?= FormController::getFormData('searchable', $data, ($add ? true : null)) ? ' checked="checked"' : ''; ?>>
							<span>
								<small class="switcher-on">
									<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
										<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
									</svg>
								</small>
								<small class="switcher-off">
									<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
										<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
									</svg>
								</small>
							</span>
						</label>
					</div>
				</div>
                <div class="form-group form-check mt-0 mb-4">
					<label for="sitemap">Allow in sitemap</label>
					<div class="checkbox switcher mt-2">
						<label>
							<input
								id="sitemap"
								type="checkbox"
								name="sitemap"
								value="<?= FormController::getFormData('sitemap', $data, ($add ? true : null)); ?>"
								<?= FormController::getFormData('sitemap', $data, ($add ? true : null)) ? ' checked="checked"' : ''; ?>>
							<span>
								<small class="switcher-on">
									<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
										<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
									</svg>
								</small>
								<small class="switcher-off">
									<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
										<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
									</svg>
								</small>
							</span>
						</label>
					</div>
				</div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header mb-2">
				<span class="card-title">Meta data</span>
            </div>
            <div class="card-body p-3 pt-0">
                <div class="form-group mb-4">
                    <label for="meta_description" class="form-label">Description</label>
                    <input
                        name="meta_description"
                        type="text"
                        class="form-control mt-2"
                        value="<?= FormController::getFormData('meta_description', $data); ?>"
                        placeholder="Please enter the description"/>
                </div>
                <div class="form-group mb-4">
                    <label for="meta_keywords" class="form-label">Keywords</label>
                    <input
                        class="tags mt-2"
                        name="meta_keywords"
                        value="<?= FormController::getFormData('meta_keywords', $data); ?>"/>
                </div>
                <div class="form-group mb-4">
                    <label for="meta_author" class="form-label">Author</label>
                    <input
                        name="meta_author"
                        type="text"
                        class="form-control mt-2"
                        value="<?= FormController::getFormData('meta_author', $data); ?>"
                        placeholder="Please enter the author of this page"/>
                </div>
            </div>
        </div>
    </div>
    <?php
    if (empty($add)) {
        ?>
        <div class="col-12">
            <div class="card">
                <div class="card-header mb-2">
                    <span class="card-title">Old URLs</span>
                </div>
                <div class="card-body p-3 pt-0">
                <div class="row">
                    <div class="col-6">
                        <input
                            name="old_url"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter the old URL"/>
                    </div>
                    <div class="col-6">
                        <button type="button" class="btn btn-blank btn-save p-0 m-0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                            </svg><br/>
                            add
                        </button>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-12">
                        <?php
                        if (count($data->old_urls)) {
                            ?>
                            <table class="table table-sorter">
                                <thead>
                                    <tr>
                                        <th>URL</th>
                                        <th width="10px">&nbsp;</th>
                                        <th width="120px">Active</th>
                                        <th width="100px">&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($data->old_urls as $result) {
                                        ?>
                                        <tr id="url-<?= $result->id; ?>">
                                            <td class="url">
                                                <input
                                                    name="old_urls[]"
                                                    type="text"
                                                    class="form-control"
                                                    value="<?= $result->url; ?>"
                                                    placeholder="Please enter the old URL"/>
                                            </td>
                                            <td>&nbsp;</td>
                                            <td style="padding-top: 20px !important;">
                                                <div class="form-group form-check">
                                                    <div class="checkbox switcher">
                                                        <label>
                                                            <input
                                                                type="checkbox"
                                                                name="old_urls_status[]"
                                                                value="<?= $result->status; ?>"
                                                                <?= (($result->status == 'active') ? true : false) ? ' checked="checked"' : ''; ?>>
                                                            <span>
                                                                <small class="switcher-on">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                    </svg>
                                                                </small>
                                                                <small class="switcher-off">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                    </svg>
                                                                </small>
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="widget-category-button">
                                                <button
                                                    class="btn btn-blank float-right btn-delete-old-url m-0 p-0"
                                                    data-id="<?= $result->id; ?>"
                                                    type="button">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </button>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                            <?php
                        } else {
                            ?>
                            <strong class="h5">No URLs</strong>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <?php
    }
    ?>
</div>
<script type="text/javascript">
    $(function () {
        $(".btn-delete-old-url").click(function() {
            $("#url-" + $(this).data("id")).remove();
        });
    });
</script>