<?php
/**
 * Basket index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\GroupsController;
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$group = (new GroupsController())->getGroup('Customer');

$url = ($this->di->getConfig())->urls->sales . '/basket';

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-primary">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->quantity; ?></strong>
                </div>
                <div class="text-white">
                    Quantity
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->sub_total; ?></strong>
                </div>
                <div class="text-white">
                    Sub-total
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-warning">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->vat; ?></strong>
                </div>
                <div class="text-white">
                    VAT
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1H1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                    <path d="M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2H3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $data->total; ?></strong>
                </div>
                <div class="text-white">
                    Total
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card p-0">
            <div class="card-body">
                <button
                    class="btn btn-blank"
                    type="button"
                    data-original-title="Are you sure?"
                    data-html="true"
                    data-trigger="focus"
                    data-toggle="popover"
                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/clear'); ?>">Yes</a>'>
                    <div
                        data-toggle="tooltip"
                        data-dismiss="hover"
                        data-placement="top"
                        title="Throw the basket into the trash">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg><br/>
                        delete
                    </div>
                </button>
                <button
                    class="btn btn-blank"
                    type="button"
                    data-original-title="Are you sure?"
                    data-html="true"
                    data-trigger="focus"
                    data-toggle="popover"
                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/archive'); ?>">Yes</a>'>
                    <div
                        data-toggle="tooltip"
                        data-dismiss="hover"
                        data-placement="top"
                        title="Save the basket for later">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                        </svg><br/>
                        archive
                    </div>
                </button>
                <button
                    id="btn-save"
                    class="btn btn-blank btn-save float-right"
                    type="submit"
                    name="shipping"
                    title="Complete the order"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                    </svg><br/>
                    complete
                </button>
                <input name="delivery" type="hidden" value="1">
                <a
                    href="<?= $url; ?>"
                    class="btn btn-blank float-right"
                    name="basket"
                    title="Go to basket step"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                    </svg><br/>
                    back
                </a>
            </div>
        </div>
    </div>
</div>
<form
    id="form-edit"
    method="post"
    action="<?= UrlHelper::backend($url . '/update/' . $data->id, 'here'); ?>">
    <div class="row mb-3">
        <div class="col-12 mb-3">
            Required fields <span class="required">*</span>
        </div>
        <div class="col-6">
            <div class="card">
                <div id="billing" class="card-body">
                    <table class="table table-borderless mb-0">
                        <tbody>
                            <tr>
                                <td class="align-top p-0">
                                    <h4>
                                        Billing address
                                    </h4>
                                </td>
                                <td width="140px" class="p-0" style="height: 90px;">
                                    &nbsp;
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="form-group mb-4">
                        <label for="billing_email">
                            Email<span class="required">*</span>
                        </label>
                        <input
                            id="billing_email"
                            name="billing_email"
                            type="text"
                            class="form-control mt-2 email"
                            aria-describedby="billing_email"
                            value="<?= FormController::getFormData('billing_email'); ?>"
                            required>
                    </div>
                    <div class="customers form-group mb-4" style="display: none">
                        <label for="customers">
                            Customers
                        </label>
                        <select
                            name="customers"
                            class="form-control mt-2" 
                            data-target="billing"></select>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_first_name">
                            First name<span class="required">*</span>
                        </label>
                        <input
                            id="billing_first_name"
                            name="billing_first_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_first_name"
                            value="<?= FormController::getFormData('billing_first_name'); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_last_name">
                            Last name<span class="required">*</span>
                        </label>
                        <input
                            id="billing_last_name"
                            name="billing_last_name"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_last_name"
                            value="<?= FormController::getFormData('billing_last_name'); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_phone">
                            Phone
                        </label>
                        <input
                            id="billing_phone"
                            name="billing_phone"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_phone"
                            value="<?= FormController::getFormData('billing_phone'); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_company">
                            Company
                        </label>
                        <input
                            id="billing_company"
                            name="billing_company"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_company"
                            value="<?= FormController::getFormData('billing_company'); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_postcode">
                            Postcode<span class="required">*</span>
                        </label>
                        <input
                            id="billing_postcode"
                            name="billing_postcode"
                            type="text"
                            class="form-control mt-2 postcode"
                            aria-describedby="billing_postcode"
                            data-target="billing"
                            value="<?= FormController::getFormData('billing_postcode'); ?>"
                            required>
                    </div>
                    <div class="postcodes form-group mb-4">
                        <label for="postcodes">
                            Addresses
                        </label>
                        <select
                            name="postcodes"
                            class="form-control mt-2" 
                            data-target="billing"></select>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_address_line_1">
                            Address line 1<span class="required">*</span>
                        </label>
                        <input
                            id="billing_address_line_1"
                            name="billing_address_line_1"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_address_line_1"
                            value="<?= FormController::getFormData('billing_address_line_1'); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_address_line_2">
                            Address line 2
                        </label>
                        <input
                            id="billing_address_line_2"
                            name="billing_address_line_2"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_address_line_2"
                            value="<?= FormController::getFormData('billing_address_line_2'); ?>">
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_town">
                            Town<span class="required">*</span>
                        </label>
                        <input
                            id="billing_town"
                            name="billing_town"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_town"
                            value="<?= FormController::getFormData('billing_town'); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_county">
                            County<span class="required">*</span>
                        </label>
                        <input
                            id="billing_county"
                            name="billing_county"
                            type="text"
                            class="form-control mt-2"
                            aria-describedby="billing_county"
                            value="<?= FormController::getFormData('billing_county'); ?>"
                            required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="billing_country">
                            Country<span class="required">*</span>
                        </label>
                        <select 
                            id="billing_country"
                            name="billing_country"
                            class="form-control mt-2"
                            aria-describedby="billing_country"
                            required>
                        <?php
                        $selected = FormController::getFormData('billing_country', null, 'United Kingdom');
                        foreach (FormController::defaultCountries() as $country) {
                            ?>
                            <option
                                value="<?= $country; ?>"
                                <?= $selected == $country ? ' selected': '' ; ?>><?= $country; ?></option>
                            <?php
                        }
                        ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <table class="table table-borderless mb-0">
                        <tbody>
                            <tr>
                                <td class="align-top p-0">
                                    <h4>
                                        Delivery address
                                    </h4>
                                </td>
                                <td width="140px" class="p-0" style="height: 90px;">
                                    <div class="form-group form-check mt-0">
                                        <label for="status">Same as billing</label>
                                        <div class="checkbox switcher mt-2">
                                            <label>
                                                <input
                                                    id="same_billing"
                                                    type="checkbox"
                                                    name="same_billing"
                                                    value="<?= FormController::getFormData('same_billing', null, true); ?>"
                                                    <?= FormController::getFormData('same_billing', null, true) == 'active' ? ' checked="checked"' : ''; ?>>
                                                <span>
                                                    <small class="switcher-on">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                        </svg>
                                                    </small>
                                                    <small class="switcher-off">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                        </svg>
                                                    </small>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div id="delivery">
                        <div class="form-group mb-4">
                            <label for="delivery_email">
                                Email<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_email"
                                name="delivery_email"
                                type="text"
                                class="form-control mt-2 email"
                                aria-describedby="delivery_email"
                                value="<?= FormController::getFormData('delivery_email'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_first_name">
                                First name<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_first_name"
                                name="delivery_first_name"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_first_name"
                                value="<?= FormController::getFormData('delivery_first_name'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_last_name">
                                Last name<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_last_name"
                                name="delivery_last_name"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_last_name"
                                value="<?= FormController::getFormData('delivery_last_name'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_phone">
                                Phone
                            </label>
                            <input
                                id="delivery_phone"
                                name="delivery_phone"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_phone"
                                value="<?= FormController::getFormData('delivery_phone'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_company">
                                Company
                            </label>
                            <input
                                id="delivery_company"
                                name="delivery_company"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_company"
                                value="<?= FormController::getFormData('delivery_company'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_postcode">
                                Postcode<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_postcode"
                                name="delivery_postcode"
                                type="text"
                                class="form-control mt-2 postcode"
                                aria-describedby="delivery_postcode"
                                data-target="delivery"
                                value="<?= FormController::getFormData('delivery_postcode'); ?>"
                                disabled>
                        </div>
                        <div class="postcodes form-group mb-4">
                            <label for="postcodes">
                                Addresses
                            </label>
                            <select
                                name="postcodes"
                                class="form-control mt-2" 
                                data-target="delivery"></select>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_address_line_1">
                                Address line 1<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_address_line_1"
                                name="delivery_address_line_1"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_address_line_1"
                                value="<?= FormController::getFormData('delivery_address_line_1'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_address_line_2">
                                Address line 2
                            </label>
                            <input
                                id="delivery_address_line_2"
                                name="delivery_address_line_2"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_address_line_2"
                                value="<?= FormController::getFormData('delivery_address_line_2'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_town">
                                Town<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_town"
                                name="delivery_town"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_town"
                                value="<?= FormController::getFormData('delivery_town'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_county">
                                County<span class="required">*</span>
                            </label>
                            <input
                                id="delivery_county"
                                name="delivery_county"
                                type="text"
                                class="form-control mt-2"
                                aria-describedby="delivery_county"
                                value="<?= FormController::getFormData('delivery_county'); ?>"
                                disabled>
                        </div>
                        <div class="form-group mb-4">
                            <label for="delivery_country">
                                Country<span class="required">*</span>
                            </label>
                            <select 
                                id="delivery_country"
                                name="delivery_country"
                                class="form-control mt-2"
                                aria-describedby="delivery_country"
                                disabled>
                            <?php
                            $selected = FormController::getFormData('delivery_country', null, 'United Kingdom');
                            foreach (FormController::defaultCountries() as $country) {
                                ?>
                                <option
                                    value="<?= $country; ?>"
                                    <?= $selected == $country ? ' selected': '' ; ?>><?= $country; ?></option>
                                <?php
                            }
                            ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<script src="<?= $this->tengu->theme->getAsset('js/core/postcode.js'); ?>"></script>
<script type="text/javascript">
$(function () {
	$("input.email").keypress(function(event) {
        if ((event.keyCode ? event.keyCode : event.which) == '13') {
            $.ajax({
                url: TENGU_URL + "/api/v1/users",
                method: "POST",
                headers: {
                    "TENGU-API-KEY": TENGU_API_KEY
                },
                data: {
                    "email": $(event.target).val(),
                    "group": "<?= $group[0]; ?>"
                }
            })
            .done(function(response) {
                if (typeof response == "undefined") {
                    return;
                }
                
                let target = $(event.target).data('target');

                var html = '<option value="" selected disabled>Please select a customer</option>';

                $.each(response.data, function (key, value) {
                    html += '<option value="' +
                            value['address_line_1'] +
                            '|' + value['address_line_2'] +
                            '|' + value['town'] +
                            '|' + value['county'] +
                            '|' + value['country'] +
                        '">' +
                            value['address_line_1'] +
                        "</option>";
                });

                $("#" + target + " .postcodes").show();
                $("#" + target + " .postcodes select").html(html);

                $("select[name=postcodes] option").on("click", function(event) {
                    postcodeClick(event);
                });
            })
            .fail(function(response) {
                throwError(response);
            });
        }
    });
});
</script>
