<?php
/**
 * Basket index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->sales . '/products';

echo $this->partial("common/form/messages");
?>
<div class="d-flex justify-content-center pt-5">
    <div class="text-center">
        <img src="/tengu/imgs/illustrations/sigma-1/3-dark.png" alt="Order successfully placed" width="460px">
        <div class="text-left">
            <div class="card mb-2">
                <div class="card-header mb-0">
                    <span class="card-title">Order successfully placed</span>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <a href="<?= $url; ?>" class="btn btn-primary">Done</a>
                </div>
            </div>
        </div>
    </div>
</div>
