<?php
/**
 * Basket index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->sales . '/products';

echo $this->partial("common/form/messages");
?>
<div class="d-flex justify-content-center pt-5">
    <div class="text-center">
        <img src="/tengu/imgs/illustrations/sigma-1/3-dark.png" alt="Order successfully placed" width="460px">
        <div class="text-left">
            <div class="card mb-2">
                <div class="card-header mb-0">
                    <span class="card-title">Order successfully placed</span>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <a href="<?= $url; ?>" class="btn btn-primary">Done</a>
                </div>
            </div>
        </div>
    </div>
</div>
