<?php
/**
 * Queue edit template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/queue';
echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
		<?php
		if ($data->status == 'pending') {
			?>
			<div class="card bg-warning">
				<div class="card-body">
					<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
						<path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
						<path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
					</svg>
					<div class="h3 text-white mt-3 mb-1">
						Pending
					</div>
					<div class="text-white">
						Status of the job
					</div>
				</div>
			</div>
			<?php
		} elseif ($data->status == 'running') {
			?>
			<div class="card bg-primary">
				<div class="card-body">
					<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
						<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
					</svg>
					<div class="h3 text-white mt-3 mb-1">
						Running
					</div>
					<div class="text-white">
						Status of the job
					</div>
				</div>
			</div>
			<?php
		} elseif ($data->status == 'complete') {
			?>
			<div class="card bg-success">
				<div class="card-body">
					<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
						<path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
					</svg>	
					<div class="h3 text-white mt-3 mb-1">
						Complete
					</div>
					<div class="text-white">
						Status of the job
					</div>
				</div>
			</div>
			<?php
		} elseif ($data->status == 'failed') {
			?>
			<div class="card bg-danger">
				<div class="card-body">
					<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
						<path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
					</svg>	
					<div class="h3 text-white mt-3 mb-1">
						Failed
					</div>
					<div class="text-white">
						Status of the job
					</div>
				</div>
			</div>
			<?php
		}
		?>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
				<a
					href="<?= UrlHelper::backend($url); ?>"
					class="btn btn-blank mr-2 text-center"
					title="Go back to the groups list"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
					</svg><br/>
					back
				</a>
				<?php
				if (!$data->deleted_at && !$data->completed_at) {
				?>
					<button
						class="btn btn-blank float-right"
						type="button"
						data-original-title="Are you sure?"
						data-html="true"
						data-trigger="focus"
						data-toggle="popover"
						data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
						<div
							data-toggle="tooltip"
							data-dismiss="hover"
							data-placement="top"
							title="Throw the group into the trash">
							<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16" class="pb-2">
								<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
								<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
							</svg><br/>
							delete
						</div>
					</button>
					<?php
				}
				?>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-6">
		<div class="card">
			<div class="card-header mb-2">
				<span class="card-title">Job</span>
			</div>
			<div class="card-body p-3 pt-0">
				<table class="table">
					<tbody>
						<tr>
							<th width="150px">
								Priority
							</th>
							<td>
								<?= $data->priority_string; ?>
							</td>
						</tr>
						<tr>
							<th>
								Job type
							</th>	
							<td>
								<?= $data->job_name; ?>
							</td>
						</tr>
						<tr>
							<th>
								Status
							</th>	
							<td>
								<?php
								switch ($data->status) {
									case 'pending':
										$bg_colour = 'badge-warning';
										break;
									case 'running':
										$bg_colour = 'badge-primary';
										break;
									case 'failed':
										$bg_colour = 'badge-danger';
										break;
									default:
										$bg_colour = 'badge-success';
										break;
								}
								?>
								<span class="badge <?= $bg_colour; ?>"><?= ucwords($data->status); ?></span>
							</td>
						</tr>
						<tr>
							<th>
								Started at
							</th>	
							<td>
								<?= DateHelper::prettyFull($data->started_at); ?>
							</td>
						</tr>
						<tr>
							<th>
								Completed at
							</th>	
							<td>
								<?= DateHelper::prettyFull($data->completed_at); ?>
							</td>
						</tr>
						<tr>
							<th>
								Execution time
							</th>	
							<td>
								<?php
								if ($data->started_at && $data->completed_at) {
									$start_date = new \DateTime($data->started_at);
									$end_date = new \DateTime($data->completed_at);
						
									$diff = $start_date->diff($end_date);
									echo $diff->format("%I:%S");
								} else {
									echo 'Unknown';
								}
								?>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-6">
		<?= $this->partial("common/logs", ['data' => $data->logs]); ?>
	</div>
</div>
