<?php
/**
 * Access denined error template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */
?>

<div id="error" class="d-flex justify-content-center pb-5">
    <div class="text-center">
        <img src="<?= $this->tengu->theme->getAsset('imgs/auth-error.png'); ?>" alt="Restricted area" width="460px">
        <div class="text-left">
            <div class="card mb-5 w-100">
                <div class="card-header mb-0">
                    <span class="card-title">Access denined!</span>
                </div>
                <div class="card-body">
                    <?php
                    echo (!empty($message) ? $message : 'Nice try');
                    ?>
                </div>
            </div>
            <a href="#" onclick="window.history.back();" class="btn btn-primary mt-3">Go back</a>
        </div>
    </div>
</div>
