<?php
/**
 * Not found error template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

?>
<div id="error" class="d-flex justify-content-center pb-5">
    <div class="text-center">
        <img src="<?= $this->tengu->theme->getAsset('imgs/no-image.png'); ?>" alt="404" width="460px">
        <div class="text-left">
            <div class="card mt-4 mb-2">
                <div class="card-header mb-0">
                    <span class="card-title">Seems there is nothing here</span>
                </div>
                <div class="card-body mb-4">
                    <?php
                    echo (!empty($message) ? $message : 'That was not found');
                    ?>
                </div>
            </div>
            <a href="#" onclick="window.history.back();" class="btn btn-primary mt-3">Go back</a>
        </div>
    </div>
</div>
