<?php
/**
 * Not found error template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

?>
<div id="error" class="d-flex justify-content-center pb-5">
    <div class="text-center">
        <img src="<?= $this->tengu->theme->getAsset('imgs/no-image.png'); ?>" alt="404" width="460px">
        <div class="text-left">
            <div class="card mt-4 mb-2">
                <div class="card-header mb-0">
                    <span class="card-title">Seems there is nothing here</span>
                </div>
                <div class="card-body mb-4">
                    <?php
                    echo (!empty($message) ? $message : 'That was not found');
                    ?>
                </div>
            </div>
            <a href="#" onclick="window.history.back();" class="btn btn-primary mt-3">Go back</a>
        </div>
    </div>
</div>
