<?php
/**
 * Save error template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

?>

<div id="error" class="d-flex justify-content-center pb-5">
    <div class="text-center">
        <img src="/tengu/imgs/illustrations/sigma-1/9-dark.png" alt="I failed at something" width="460px">
        <div class="text-left">
            <div class="card mb-2">
                <div class="card-header mb-0">
                    <span class="card-title">OH NO!</span>
                </div>
                <div class="card-body mb-4">
                    <?php
                    echo !empty($message) ? $message : 'Something has gone wrong';
                    if (($_ENV['APP_DEBUG'] || $_ENV['APP_DEBUG'] == 'true')) {
                        if (!empty($data)) {
                            ?>
                            <p class="pt-4">
                            <?php
                            if (is_array($data) || is_object($data)) {
                                ?>
                                <pre><?php var_dump($data); ?></pre>
                                <?php
                            } else {
                                echo $data;
                            }
                            ?>
                            </p>
                            <?php
                        }
                    }
                    ?>
                </div>
            </div>
            <a href="#" onclick="window.history.back();" class="btn btn-primary mt-3">Go back</a>
        </div>
    </div>
</div>
