<?php
/**
 * Statement item edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->fms . '/statements/' . $data->statement_id . '/items';
$update_url = $url . '/update/' . $data->id;

$back_url = UrlHelper::backend(($this->di->getConfig())->urls->fms . '/statements/edit/' . $data->statement_id);
if (!empty($_GET['from'])) {
    $back_url = urldecode($_GET['from']);
}

echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<style>
    .results-select {
        position: relative;
        overflow-y: scroll;
        height: 600px;
        padding-top: 20px;
        padding-bottom: 20px;
    }
</style>
<div class="row mb-3">
    <?php
    if ($data->tax_year) {
        ?>
        <div class="col-3">
            <div class="card bg-info">
                <div class="card-body">
                    <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                    </svg>
                    <div class="h4 text-white mt-3 mb-1" style="height: 30px">
                        <?php
                            echo DateHelper::pretty($data->tax_year->tax_year_start, false) . ' to ' . DateHelper::pretty($data->tax_year->tax_year_end, false) ;
                        ?>
                    </div>
                    <div class="text-white">
                        Tax year (<?= $data->tax_year->code; ?>)
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
    ?>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v2h6a.5.5 0 0 1 .5.5c0 .253.08.644.306.958.207.288.557.542 1.194.542.637 0 .987-.254 1.194-.542.226-.314.306-.705.306-.958a.5.5 0 0 1 .5-.5h6v-2A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M16 6.5h-5.551a2.678 2.678 0 0 1-.443 1.042C9.613 8.088 8.963 8.5 8 8.5c-.963 0-1.613-.412-2.006-.958A2.679 2.679 0 0 1 5.551 6.5H0v6A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-6z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1" style="height: 30px">
                    <?= NumberHelper::toCurrency($data->in); ?>
				</div>
                <div class="text-white">
					Incoming
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499L12.136.326zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484L5.562 3zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($data->out); ?>
				</div>
                <div class="text-white">
					Outgoing
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-2">
    <div class="col-12">
        <div class="card p-0">
            <div class="card-body">
                <a
                    href="<?= UrlHelper::generate($back_url); ?>"
                    class="btn btn-blank mr-2 text-center"
                    title="Go back to the receipts list"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                        <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                    </svg><br/>
                    back
                </a>
                <button
                    id="btn-save"
                    class="btn btn-blank float-right"
                    type="button"
                    title="Save the receipt"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg><br/>
                    save
                </button>
                <a
                    href="<?= UrlHelper::backend($url . '/add'); ?>"
                    class="btn btn-blank float-right"
                    title="Add a new statement item"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                    </svg><br/>
                    new
                </a>
                <?php
                if ($data->deleted_at) {
                    ?>
                    <button
                        class="btn btn-blank float-right"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Recover the receipt from the trash">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                            </svg><br/>
                            recover
                        </div>
                    </button>
                    <?php
                } else {
                ?>
                    <button
                        class="btn btn-blank float-right"
                        type="button"
                        data-original-title="Are you sure?"
                        data-html="true"
                        data-trigger="focus"
                        data-toggle="popover"
                        data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                        <div
                            data-toggle="tooltip"
                            data-dismiss="hover"
                            data-placement="top"
                            title="Throw the receipt into the trash">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg><br/>
                            delete
                        </div>
                    </button>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
<form
    id="form-edit"
    method="post"
    action="<?= UrlHelper::backend($update_url); ?>"
    enctype="multipart/form-data">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <?php
                            $label = "I'm live!";
                            $bg_colour = 'bg-success';
                            if ($data->deleted_at) {
                                $label = "I'm in a deleted state";
                                $bg_colour = 'bg-danger';
                            }
                            ?>
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="processed_at">
                                    Processed at
                                </label>
                                <input
                                    id="processed_at"
                                    name="processed_at"
                                    type="text"
                                    class="form-control mt-2 datepicker"
                                    aria-describedby="processed_at"
                                    value="<?= DateHelper::pretty(FormController::getFormData('processed_at', $data), false); ?>">
                            </div>
                            <div class="form-group form-check mt-0 mb-4">
                                <label for="taxable">Taxable</label>
                                <div class="checkbox switcher mt-2">
                                    <label>
                                        <input
                                            type="checkbox"
                                            name="taxable"
                                            value="1"
                                            <?= FormController::getFormData('taxable', $data) ? ' checked="checked"' : ''; ?>>
                                        <span>
                                            <small class="switcher-on">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                </svg>
                                            </small>
                                            <small class="switcher-off">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            </small>
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('receipt-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#receipt-tab">
                                Receipts
                                <?php
                                if ($data->receipts->count()) {
                                    ?>
                                    <span class="badge-svg badge-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-paperclip" viewBox="0 0 16 16">
                                            <path d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
                                        </svg>
                                    </span>
                                    <?php
                                }
                                ?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('invoice-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#invoice-tab">
                                Invoices
                                <?php
                                if ($data->invoices->count()) {
                                    ?>
                                    <span class="badge-svg badge-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-paperclip" viewBox="0 0 16 16">
                                            <path d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
                                        </svg>
                                    </span>
                                    <?php
                                }
                                ?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('statement-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#statement-tab">
                                Statement
                                <?php
                                if (!empty($data->statement)) {
                                    ?>
                                    <span class="badge-svg badge-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-paperclip" viewBox="0 0 16 16">
                                            <path d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
                                        </svg>
                                    </span>
                                    <?php
                                }
                                ?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header m-0">
                            <span class="card-title">
                                Description
                                <span class="required">*</span>
                            </span>
                        </div>
                        <div class="card-body">
                            <textarea
                                class="form-control mt-2"
                                rows="6"
                                name="description"
                                required><?= FormController::getFormData('description', null, $data->description); ?></textarea>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header m-0">
                            <span class="card-title">
                                Amount (<?= NumberHelper::currencySymbol(); ?>)
                                <span class="required">*</span>
                            </span>
                        </div>
                        <div class="card-body">
                            <input
                                name="amount"
                                type="text"
                                class="form-control mt-2"                                
                                value="<?= FormController::getFormData('amount', null, ($data->in != 0.00 ? $data->in : $data->out)); ?>"
                                required>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header m-0">
                                    <span class="card-title">Attached to</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group mb-4">
                                        <label for="project_id">Project</label>
                                        <select
                                            name="project_id"
                                            class="form-control mt-2">
                                            <?php
                                            $selected = FormController::getFormData('project_id', $data);
                                                ?>
                                                <option value="">No project</option>
                                                <?php
                                            foreach ($projects as $project) {
                                                ?>
                                                <option
                                                    value="<?= $project->id; ?>"
                                                    <?= $selected == $project->id ? ' selected' : ''; ?>><?= $project->name; ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="shareholder_id">
                                            Shareholder
                                        </label>
                                        <?php
                                            $selected = FormController::getFormData('shareholder_id', $data);
                                            ?>
                                        <select
                                            name="shareholder_id"
                                            class="form-control mt-2">
                                            <option value=""<?= !$selected ? ' selected' : ''; ?>>None</option>
                                            <?php
                                            foreach ($users as $user) {
                                                ?>
                                                <option 
                                                    value="<?= $user->id; ?>"
                                                    <?= $selected == $user->id ? ' selected' : ''; ?>><?= $user->full_name; ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="employee_id">
                                            PAYE payment
                                        </label>
                                        <?php
                                            $selected = FormController::getFormData('employee_id', $data);
                                            ?>
                                        <select
                                            name="employee_id"
                                            class="form-control mt-2">
                                            <option value=""<?= !$selected ? ' selected' : ''; ?>>None</option>
                                            <?php
                                            foreach ($users as $user) {
                                                ?>
                                                <option 
                                                    value="<?= $user->id; ?>"
                                                    <?= $selected == $user->id ? ' selected' : ''; ?>><?= $user->full_name; ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="expenses_employee_id">
                                            Expenses payment
                                        </label>
                                        <?php
                                            $selected = FormController::getFormData('expenses_employee_id', $data);
                                            ?>
                                        <select
                                            name="expenses_employee_id"
                                            class="form-control mt-2">
                                            <option value=""<?= !$selected ? ' selected' : ''; ?>>None</option>
                                            <?php
                                            foreach ($users as $user) {
                                                ?>
                                                <option 
                                                    value="<?= $user->id; ?>"
                                                    <?= $selected == $user->id ? ' selected' : ''; ?>><?= $user->full_name; ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="card">
                                <div class="card-header m-0">
                                    <span class="card-title">Money</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group mb-4">
                                        <label for="direction">
                                            Direction
                                            <span class="required">*</span>
                                        </label>
                                        <?php
                                            $selected = FormController::getFormData('direction', null, ($data->in != 0.00 ? 'incoming' : 'outgoing'));
                                            ?>
                                        <select
                                            name="direction"
                                            class="form-control mt-2"
                                            required>
                                            <option value="outgoing"<?= $selected == 'outgoing' ? ' selected' : ''; ?>>Outgoing</option>
                                            <option value="incoming"<?= $selected == 'incoming' ? ' selected' : ''; ?>>Incoming</option>
                                        </select>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="balance">
                                            Balance at time (<?= NumberHelper::currencySymbol(); ?>)
                                        </label>
                                        <input
                                            name="balance"
                                            type="text"
                                            class="form-control mt-2"                                
                                            value="<?= FormController::getFormData('balance', $data); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('receipt-tab', 'overview-tab'); ?>"
                    id="receipt-tab"
                    role="tabpanel"
                    aria-labelledby="receipt-tab">
                    <div class="row">
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card">
                                        <div class="card-header m-0">
                                            <span class="card-title">Receipts</span>
                                        </div>
                                        <div class="card-body p-0 pt-2">
                                            <div id="receipts-view">
                                            <?php
                                            if ($data->receipts->count()) {
                                                foreach ($data->receipts as $key => $item) {
                                                ?>
                                                <div class="card">
                                                    <div 
                                                        class="card-header row-header m-0"
                                                        data-toggle="collapse" 
                                                        data-target="#view-receipt-<?= $key; ?>" 
                                                        aria-expanded="true" 
                                                        aria-controls="view-receipt-<?= $key; ?>">
                                                        <span class="card-title float-left"><?= $item->name; ?></span>
                                                        <input type="hidden" name="receipts_id[]" value="<?= $item->id; ?>"/>
                                                        <div class="form-group form-check float-right">
                                                            <label for="taxable">Sync amount</label>
                                                            <div class="checkbox switcher mt-2">
                                                                <label>
                                                                    <input
                                                                        type="checkbox"
                                                                        name="receipts_sync[]"
                                                                        value="<?= $item->id; ?>">
                                                                    <span>
                                                                        <small class="switcher-on">
                                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                            </svg>
                                                                        </small>
                                                                        <small class="switcher-off">
                                                                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                            </svg>
                                                                        </small>
                                                                    </span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div 
                                                        id="view-receipt-<?= $key; ?>" 
                                                        class="card-body p-0 pdf-render collapse<?= !$key ? ' show' : '';?>"
                                                        data-url="<?= UrlHelper::backend($item->file->output_url); ?>">
                                                    </div>
                                                </div>
                                                <?php
                                                }
                                            } else {
                                                ?>
                                                <div class="row">
                                                    <div class="col-12 p-4">
                                                        <strong class="h4">No receipts</strong>
                                                    </div>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <button
                                        class="btn btn-save btn-blank float-right"
                                        type="button"
                                        title="Add the receipt"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
                                            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                        </svg><br/>
                                        add
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card">
                                        <div class="card-header m-0">
                                            <span class="card-title">Search for receipt</span>
                                        </div>
                                        <div class="card-body">
                                            <div class="row mb-4">
                                                <div class="col-12">
                                                    <input
                                                        type="text"
                                                        name="receipts_search"
                                                        class="form-control input-search float-left"
                                                        placeholder="Search"
                                                        value=""
                                                        data-type="receipts">
                                                    <button
                                                        id="receipts-clear"
                                                        type="button"
                                                        title="Clear the search"
                                                        class="btn btn-clear-search float-left hide"
                                                        data-type="receipts">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                        </svg>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="receipts-results" class="hide">
                                                <div class="row m-0">
                                                    <div class="col-4 results-select border">
                                                        <div id="receipts-select"></div>
                                                    </div>
                                                    <div class="col-8">
                                                        <div id="receipts-preview" class="pdf-render" data-url="">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="receipts-nothing" class="hide">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <strong class="h4">No results</strong>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card">
                                        <div 
                                            class="card-header m-0"
                                            data-toggle="collapse" 
                                            data-target="#add-receipt" 
                                            aria-expanded="true" 
                                            aria-controls="add-receipt">
                                            <span class="card-title">Upload new receipt</span>
                                        </div>
                                        <div id="add-receipt" class="card-body collapse">
                                            <div class="flex-grow-1 mb-4">
                                                <div class="form-group mb-4">
                                                    <label>
                                                        Label
                                                        <span class="required">*</span>
                                                    </label>
                                                    <input
                                                        id="receipt_name"
                                                        name="receipt_name"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        value="<?= FormController::getFormData('receipt_name'); ?>"
                                                        required>
                                                </div>
                                                <div class="form-group mb-4">
                                                    <label>
                                                        Amount (<?= NumberHelper::currencySymbol(); ?>)
                                                    </label>
                                                    <input
                                                        name="receipt_amount"
                                                        type="text"
                                                        class="form-control mt-2"
                                                        value="<?= FormController::getFormData('receipt_amount'); ?>">
                                                </div>
                                                <div class="form-group mb-4">
                                                    <label>
                                                        Issued on
                                                    </label>
                                                    <input
                                                        name="receipt_issued_on"
                                                        type="text"
                                                        class="form-control mt-2 datepicker"
                                                        value="<?= DateHelper::pretty(FormController::getFormData('receipt_issued_on'), false); ?>">
                                                </div>
                                                <div class="form-group mb-4">
                                                    <label>Upload</label>
                                                    <input
                                                        id="upload_receipt"
                                                        name="upload_receipt"
                                                        type="file"
                                                        accept="image/jpeg, image/png, capture=camera"
                                                        class="form-control mt-2">
                                                </div>
                                                <div class="form-group form-check mt-0 mb-4">
                                                    <label>Taxable</label>
                                                    <div class="checkbox switcher mt-2">
                                                        <label>
                                                            <input
                                                                type="checkbox"
                                                                name="receipt_taxable"
                                                                value="1"
                                                                <?= FormController::getFormData('receipt_taxable', null, 1) ? ' checked="checked"' : ''; ?>>
                                                            <span>
                                                                <small class="switcher-on">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                    </svg>
                                                                </small>
                                                                <small class="switcher-off">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                    </svg>
                                                                </small>
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('invoice-tab', 'overview-tab'); ?>"
                    id="invoice-tab"
                    role="tabpanel"
                    aria-labelledby="invoice-tab">
                    <div class="row">
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card">
                                        <div class="card-header m-0">
                                            <span class="card-title">Invoices</span>
                                        </div>
                                        <div class="card-body p-0 pt-4">
                                            <div id="invoices-view">
                                            <?php
                                            if ($data->invoices->count()) {
                                                foreach ($data->invoices as $key => $item) {
                                                ?>
                                                <div class="card">
                                                    <div 
                                                        class="card-header m-0"
                                                        data-toggle="collapse" 
                                                        data-target="#view-invoice-<?= $key; ?>" 
                                                        aria-expanded="true" 
                                                        aria-controls="view-invoice-<?= $key; ?>">
                                                        <span class="card-title"><?= $item->name; ?></span>
                                                    </div>
                                                    <div 
                                                        id="view-invoice-<?= $key; ?>" 
                                                        class="card-body p-0 pdf-render collapse<?= !$key ? ' show' : '';?>"
                                                        data-url="<?= UrlHelper::backend($item->file->output_url); ?>">
                                                    </div>
                                                </div>
                                                <?php
                                                }
                                            } else {
                                                ?>
                                                <div class="row">
                                                    <div class="col-12 p-4">
                                                        <strong class="h4">No invoices</strong>
                                                    </div>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <button
                                        class="btn btn-save btn-blank float-right"
                                        type="button"
                                        title="Add the invoice"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
                                            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                        </svg><br/>
                                        add
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mb-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card">
                                        <div class="card-header m-0">
                                            <span class="card-title">Search for invoice</span>
                                        </div>
                                        <div class="card-body">
                                            <div class="row mb-4">
                                                <div class="col-12">
                                                    <input
                                                        type="text"
                                                        name="invoices_search"
                                                        class="form-control input-search float-left"
                                                        placeholder="Search"
                                                        value=""
                                                        data-type="invoices">
                                                    <button
                                                        id="invoices-clear"
                                                        type="button"
                                                        title="Clear the search"
                                                        class="btn btn-clear-search float-left hide"
                                                        data-type="invoices">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                        </svg>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="invoices-results" class="hide">
                                                <div class="row">
                                                    <div class="col-4 results-select border">
                                                        <div id="invoices-select"></div>
                                                    </div>
                                                    <div class="col-8">
                                                        <div class="pdf-render" id="invoices-preview" data-url=""></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="invoices-nothing" class="hide">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <strong class="h4">No results</strong>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('statement-tab', 'overview-tab'); ?>"
                    id="statement-tab"
                    role="tabpanel"
                    aria-labelledby="statement-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <?php
                                    if (!empty($data->statement->file)) {
                                        switch ($data->statement->file->mime_type) {
                                            case 'application/pdf':
                                                ?>
                                                <div class="pdf-render"
                                                    data-url="<?= UrlHelper::backend($data->statement->file->output_url);?>"></div>
                                                <?php
                                                break;
                                            default:
                                            ?>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <span class="h4">No statement to preview</span>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?= $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true#notes-tab'
                                                ]
                                            ); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="receipts-template" class="hide">
    <div class="col-12">
        <div class="form-group form-check mt-0 mb-4">
            <label class="receipts-name"></label>
            <div class="radio switcher mt-2">
                <label>
                    <input
                        class="receipts-select"
                        type="radio"
                        name="receipts_id[]"
                        value="1">
                    <span>
                        <small class="switcher-on">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                            </svg>
                        </small>
                        <small class="switcher-off">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </small>
                    </span>
                </label>
            </div>
        </div>
        <hr/>
    </div>
</div>

<div id="invoices-template" class="hide">
    <div class="col-12">
        <div class="form-group form-check mt-0 mb-4">
            <label class="invoices-name"></label>
            <div class="radio switcher mt-2">
                <label>
                    <input
                        class="invoices-select"
                        type="radio"
                        name="invoices_id[]"
                        value="1">
                    <span>
                        <small class="switcher-on">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                            </svg>
                        </small>
                        <small class="switcher-off">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </small>
                    </span>
                </label>
            </div>
        </div>
        <hr/>
    </div>
</div>

<script type="text/javascript">
$(function () {
    $("#invoices-clear, #receipts-clear").click(function() {
        let type = $(this).data("type");

        $("#" + type + "-select").html("");
        $("#" + type + "-clear").hide();
        $("#" + type + "-results").hide();
        $("#" + type + "-nothing").hide();
    });

	$("input[name=receipts_search], input[name=invoices_search]").keypress(function(event) {
        let type = $(this).data("type");

        if ((event.keyCode ? event.keyCode : event.which) == '13') {
            $("#" + type + "-clear").show();
            $("#" + type + "-select").html("");
            $("#" + type + "-results").hide();
            $("#" + type + "-nothing").hide();

            $.ajax({
                url: TENGU_URL + "/api/v1/" + type,
                method: "POST",
                headers: {
                    "TENGU-API-KEY": TENGU_API_KEY
                },
                data: {
                    "query": $(event.target).val()
                }
            })
            .done(function(response) {
                if (typeof response == "undefined") {
                    return;
                }
                
                let html = '';
                let message = '';

                $.each(response.data, function (key, value) {
                    message = value["name"] + "<br/>" + prettyDate(value["date"], false);
                    $("#" + type + "-template ." + type + "-name").html(message);
                    $("#" + type + "-template input").val(value["id"]);
                    $("#" + type + "-template input").attr("data-url", value["url"]);
                    html += $("#" + type + "-template").html();
                });

                if (html) {
                    $("#" + type + "-select").html(html);

                    $("input." + type + "-select").on("change", function(event) {
                        $("#" + type + "-preview").attr("data-url", TENGU_URL + $(event.target).data("url"));
                        renderPDF($("#" + type + "-preview"));
                    });

                    $("#" + type + "-results").show();
                } else {
                    $("#" + type + "-nothing").show();
                }
            })
            .fail(function(response) {
                throwError(response);
            });
        }
    });

    $("#upload_receipt").change(function() {
        if (!$("#receipt_name").val()) {
            $("#receipt_name").val(($("#upload_receipt").val().split(/(\\|\/)/g).pop()).split(/\./g).shift());
        }
    });
});
</script>
