<?php
/**
 * Logs template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Helpers\DateHelper;

if (!isset($label)) {
    $label = 'Activity';
}
?>
<div class="card">
    <div class="card-header mb-4">
        <span class="card-title"><?= $label; ?></span>
    </div>
    <div class="card-body p-0 pb-3">
        <?php
        if (count($data)) {
            ?>
            <div id="logs" class="pl-3 timeline-label<?= count($data) > 10 ? ' timeline-hide-overflow' : '';?>">
                <?php
                foreach ($data as $log) {
                    ?>
                    <div class="timeline-item">
                        <div class="timeline-label">
                            <?= DateHelper::prettyFull($log->created_at, false); ?>
                        </div>
                        <div class="timeline-badge bg-<?= !empty($log->type) ? $log->type : 'primary'; ?>"></div>
                        <div class="timeline-content">
                            <?= $log->summary; ?><br/>
                            <small class="text-muted">at <?= date('H:i', strtotime($log->created_at)); ?></small>
                        </div>
                    </div>
                    <?php
                }
            ?>
            </div>
            <?php
			if (count($data) > 10) {
				?>
				<div class="pt-2 w-100 text-center text-primary">
					<span id="logs-timeline-show" class="timeline-show">More</span>
					<span id="logs-timeline-hide" class="timeline-hide">Less</span>
				</div>
				<?php
			}
        } else {
            ?>
            <strong class="pl-3">No activity</strong>
            <?php
        }
        ?>
    </div>
</div>
<script type="text/javascript">
$(function () {
	$('#logs-timeline-show').click(function() {
		$('#logs').addClass('timeline-expand collapse show');
		$('#logs-timeline-show').hide();
		$('#logs-timeline-hide').show();
	});
	$('#logs-timeline-hide').click(function() {
		$('#logs').removeClass('timeline-expand collapse show');
		$('#logs-timeline-hide').hide();
		$('#logs-timeline-show').show();
	});
});
</script>
