<?php
/**
 * Logs template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Helpers\DateHelper;

if (!isset($label)) {
    $label = 'Activity';
}
?>
<div class="card">
    <div class="card-header mb-4">
        <span class="card-title"><?= $label; ?></span>
    </div>
    <div class="card-body p-0 pb-3">
        <?php
        if (count($data)) {
            ?>
            <div id="logs" class="pl-3 timeline-label<?= count($data) > 10 ? ' timeline-hide-overflow' : '';?>">
                <?php
                foreach ($data as $log) {
                    ?>
                    <div class="timeline-item">
                        <div class="timeline-label">
                            <?= DateHelper::prettyFull($log->created_at, false); ?>
                        </div>
                        <div class="timeline-badge bg-<?= !empty($log->type) ? $log->type : 'primary'; ?>"></div>
                        <div class="timeline-content">
                            <?= $log->summary; ?><br/>
                            <small class="text-muted">at <?= date('H:i', strtotime($log->created_at)); ?></small>
                        </div>
                    </div>
                    <?php
                }
            ?>
            </div>
            <?php
			if (count($data) > 10) {
				?>
				<div class="pt-2 w-100 text-center text-primary">
					<span id="logs-timeline-show" class="timeline-show">More</span>
					<span id="logs-timeline-hide" class="timeline-hide">Less</span>
				</div>
				<?php
			}
        } else {
            ?>
            <strong class="pl-3">No activity</strong>
            <?php
        }
        ?>
    </div>
</div>
<script type="text/javascript">
$(function () {
	$('#logs-timeline-show').click(function() {
		$('#logs').addClass('timeline-expand collapse show');
		$('#logs-timeline-show').hide();
		$('#logs-timeline-hide').show();
	});
	$('#logs-timeline-hide').click(function() {
		$('#logs').removeClass('timeline-expand collapse show');
		$('#logs-timeline-hide').hide();
		$('#logs-timeline-show').show();
	});
});
</script>
