<div id="onscreen-keyboard">
    <div id="onscreen-keyboard-close">
        <div
            id="button-onscreen-keyboard"
            title="Show or hide the keyboard"
            data-toggle="tooltip"
            data-dismiss="click"
            data-placement="top">
            <button 
                class="btn btn-blank text-white" 
                type="button" 
                data-toggle="collapse" 
                data-target="#onscreen-keyboard-keys" 
                aria-expanded="false" 
                aria-controls="onscreen-keyboard-keys">
                <svg id="onscreen-keyboard-hide" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5zm-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5z"/>
                </svg>
                <svg id="onscreen-keyboard-show" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 3.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5zM8 6a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 .708-.708L7.5 12.293V6.5A.5.5 0 0 1 8 6z"/>
                </svg>
            </button>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div id="onscreen-keyboard-keys" class="collapse">
            <table id="onscreen-keyboard-letters" class="float-left mr-3">
                <tbody>
                    <tr class="onscreen-keyboard-specials hide">
                        
                        <td>
                            <button class="btn btn-default">"</button>
                        </td>
                        <td>
                            <button class="btn btn-default">'</button>
                        </td>
                        <td>
                            <button class="btn btn-default">£</button>
                        </td>
                        <td>
                            <button class="btn btn-default">$</button>
                        </td>
                        <td>
                            <button class="btn btn-default">€</button>
                        </td>
                        <td>
                            <button class="btn btn-default">%</button>
                        </td>
                        <td>
                            <button class="btn btn-default">*</button>
                        </td>
                        <td>
                            <button class="btn btn-default">-</button>
                        </td>
                        <td>
                            <button class="btn btn-default">+</button>
                        </td>
                        <td>
                            <button class="btn btn-default">=</button>
                        </td>
                    </tr>
                    <tr class="onscreen-keyboard-specials hide">
                        <td>
                            <button class="btn btn-default">:</button>
                        </td>
                        <td>
                            <button class="btn btn-default">!</button>
                        </td>
                        <td>
                            <button class="btn btn-default">&</button>
                        </td>
                        <td>
                            <button class="btn btn-default">(</button>
                        </td>
                        <td>
                            <button class="btn btn-default">)</button>
                        </td>
                        <td>
                            <button class="btn btn-default">~</button>
                        </td>
                        <td>
                            <button class="btn btn-default">[</button>
                        </td>
                        <td>
                            <button class="btn btn-default">]</button>
                        </td>
                        <td>
                            <button class="btn btn-default">{</button>
                        </td>
                        <td>
                            <button class="btn btn-default">}</button>
                        </td>
                    </tr>
                    <tr class="onscreen-keyboard-specials hide">
                        <td>
                            <button class="btn btn-default">;</button>
                        </td>
                        <td>
                            <button class="btn btn-default">|</button>
                        </td>
                        <td>
                            <button class="btn btn-default">`</button>
                        </td>
                        <td>
                            <button class="btn btn-default">^</button>
                        </td>
                        <td>
                            <button class="btn btn-default"><</button>
                        </td>
                        <td>
                            <button class="btn btn-default">></button>
                        </td>
                        <td>
                            <button class="btn btn-default">?</button>
                        </td>
                        <td>
                            <button class="btn btn-default">/</button>
                        </td>
                        <td>
                            <button class="btn btn-default">\</button>
                        </td>
                        <td>
                            <button class="btn btn-default">_</button>
                        </td>
                    </tr>
                    <tr class="onscreen-keyboard-standard">
                        <td>
                            <button class="btn btn-default">q</button>
                        </td>
                        <td>
                            <button class="btn btn-default">w</button>
                        </td>
                        <td>
                            <button class="btn btn-default">e</button>
                        </td>
                        <td>
                            <button class="btn btn-default">r</button>
                        </td>
                        <td>
                            <button class="btn btn-default">t</button>
                        </td>
                        <td>
                            <button class="btn btn-default">y</button>
                        </td>
                        <td>
                            <button class="btn btn-default">u</button>
                        </td>
                        <td>
                            <button class="btn btn-default">i</button>
                        </td>
                        <td>
                            <button class="btn btn-default">o</button>
                        </td>
                        <td>
                            <button class="btn btn-default">p</button>
                        </td>
                    </tr>
                    <tr class="onscreen-keyboard-standard">
                        <td>
                            <button class="btn btn-default">a</button>
                        </td>
                        <td>
                            <button class="btn btn-default">s</button>
                        </td>
                        <td>
                            <button class="btn btn-default">d</button>
                        </td>
                        <td>
                            <button class="btn btn-default">f</button>
                        </td>
                        <td>
                            <button class="btn btn-default">g</button>
                        </td>
                        <td>
                            <button class="btn btn-default">h</button>
                        </td>
                        <td>
                            <button class="btn btn-default">j</button>
                        </td>
                        <td>
                            <button class="btn btn-default">k</button>
                        </td>
                        <td>
                            <button class="btn btn-default">l</button>
                        </td>
                        <td>
                            <button class="btn btn-default">@</button>
                        </td>
                    </tr>
                    <tr class="onscreen-keyboard-standard">
                        <td>
                            <button class="btn btn-default">z</button>
                        </td>
                        <td>
                            <button class="btn btn-default">x</button>
                        </td>
                        <td>
                            <button class="btn btn-default">c</button>
                        </td>
                        <td>
                            <button class="btn btn-default">v</button>
                        </td>
                        <td>
                            <button class="btn btn-default">b</button>
                        </td>
                        <td>
                            <button class="btn btn-default">n</button>
                        </td>
                        <td>
                            <button class="btn btn-default">m</button>
                        </td>
                        
                        <td>
                            <button class="btn btn-default">.</button>
                        </td>
                        <td>
                            <button class="btn btn-default">,</button>
                        </td>
                        <td>
                            <button class="btn btn-default">#</button>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button class="btn btn-default onscreen-keyboard-caps">CAPS</button>
                        </td>
                        <td colspan="6">
                            <button class="btn btn-default">SPACE</button>
                        </td>
                        <td colspan="2">
                            <button class="btn btn-default onscreen-keyboard-shift">SHIFT</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table id="onscreen-keyboard-numbers" class="float-left mr-3">
                <tbody>
                    <tr>
                        <td>
                            <button class="btn btn-default">7</button>
                        </td>
                        <td>
                            <button class="btn btn-default">8</button>
                        </td>
                        <td>
                            <button class="btn btn-default">9</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button class="btn btn-default">4</button>
                        </td>
                        <td>
                            <button class="btn btn-default">5</button>
                        </td>
                        <td>
                            <button class="btn btn-default">6</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button class="btn btn-default">1</button>
                        </td>
                        <td>
                            <button class="btn btn-default">2</button>
                        </td>
                        <td>
                            <button class="btn btn-default">3</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button class="btn btn-default">0</button>
                        </td>
                        <td colspan="2">
                            <button class="btn btn-default">DEL</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table id="onscreen-keyboard-control" class="float-left mr-3">
                <tbody>
                    <tr>
                        <td>
                            <button id="onscreen-keyboard-up" class="btn btn-default">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
                                </svg>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button id="onscreen-keyboard-down" class="btn btn-default">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                                </svg>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td id="onscreen-keyboard-enter">
                            <button class="btn btn-default">ENTER</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>