<?php
/**
 * Tags template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;

if (!isset($meta)) {
    $meta = false;
}

if (empty($data)) {
    $tags_string = FormController::getFormData('tags');
    $data = preg_split('/\|*\|/i', $tags_string, -1, PREG_SPLIT_NO_EMPTY | PREG_SPLIT_DELIM_CAPTURE);
}

?>
<div class="card">
    <div class="card-header mb-3">
        <span class="card-title">Tags</span>
    </div>
    <div class="card-body p-0">
        <input
            class="tags mb-2"
            name="tags"
            value="<?= !empty($data) ? (new FormController())->tagsToString($data) : ''; ?>"/>
        <?php
        if ($meta) {
            ?>
            <small>Tags will also be used as meta keywords on the front end</small>
            <?php
        }
        ?>
    </div>
</div>
