<?php
/**
 * Settings index template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/settings';

echo $this->partial("common/form/messages");
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update'); ?>">
    <div class="row mb-3">
		<div class="col-12">
			<div class="card p-0">
				<div class="card-body">
					<button
						id="btn-save"
						class="btn btn-blank float-right"
						type="button"
						title="Save my page"
						data-toggle="tooltip"
						data-trigger="hover"
						data-dismiss="click"
						data-placement="top">
						<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg><br/>
						save
					</button>
				</div>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div
								class="preview-img"
								title="I'm inactive"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
                                    data-placement="bottom">
                                <div class="position-relative border">
                                    <?php
                                    if ($data->status == 'offline') {
                                        $label = "I'm offline";
                                        $bg_colour = 'bg-danger';
                                    } else {
                                        $label = "I'm live!";
                                        $bg_colour = 'bg-success';
                                    }
                                    ?>
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="<?= $label; ?>">
                                    <div
                                        title="<?= $label; ?>"
                                        class="position-absolute circle <?= $bg_colour; ?>"
                                        style="width: 10px;height: 10px;margin-top: -5px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="tengu_theme">
                                    Theme
                                    <span class="required">*</span>
                                </label>
                                <select
                                    name="tengu_theme"
                                    class="form-control mt-2">
                                    <?php
                                    $selected = FormController::getFormData('tengu_theme', $data);
                                    foreach ($themes as $theme) {
                                        ?>
                                        <option
                                            value="<?= $theme; ?>"
                                            <?= $selected == $theme ? ' selected' : ''; ?>><?= $theme; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Extra
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
