<?php
/**
 * Theme index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->cms . '/themes';

$filter_status = $this->tengu->getFilters('status');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
				<a href="<?= UrlHelper::backend($url . '/add'); ?>" class="btn btn-primary float-right">
		            Add
		        </a>
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
                            <?php
                                $this->partial('common/lists/sorting', ['url' => $url]);
                            ?>
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
		                        <option value="active"<?= $filter_status == 'active' ? ' selected="selected"' : ''; ?>>Active</option>
		                        <option value="inactive"<?= $filter_status == 'inactive' ? ' selected="selected"' : ''; ?>>Inactive</option>
		                        <option value="deleted"<?= $filter_status == 'deleted' ? ' selected="selected"' : ''; ?>>Deleted</option>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>
				
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body p-3">
                <?php
                if ($data->total_items) {
                    ?>
                    <form id="form-list" method="post" action="<?= UrlHelper::backend($url . '/active'); ?>">
                        <table class="table tablesorter">
                            <thead>
                                <tr>
                                    <th width="140px">Active</th>
                                    <th>Name</th>
                                    <th width="110px">Status</th>
									<th width="110px">Annual</th>
                                    <th width="150px">Go live</th>
                                    <th width="150px">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($data->getItems() as $row) {
                                    switch ($row->status) {
                                        case 'active':
                                            $bg_colour = 'badge-success';
                                            break;
                                        case 'inactive':
                                            $bg_colour = 'badge-warning';
                                            break;
                                        case 'deleted':
                                            $bg_colour = 'badge-danger';
                                            break;
                                        default:
                                            break;
                                    }
                                    ?>
                                    <tr>
                                        <td>
                                            <div class="form-group form-check mt-0 mb-4">
                                                <div class="radio switcher mt-2">
                                                    <label>
                                                        <input
                                                            type="radio"
                                                            name="active"
                                                            value="<?= $row->id; ?>"
                                                            onchange="$('#form-list').submit()"
                                                            <?= ($row->status == 'active') ? 'checked' : ''; ?>>
                                                        <span>
                                                            <small class="switcher-on">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                </svg>
                                                            </small>
                                                            <small class="switcher-off">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                </svg>
                                                            </small>
                                                        </span>
                                                    </label>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                                <?= $row->name; ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
                                                <span class="badge <?= $bg_colour; ?>"><?= $row->status; ?></span>
                                            </a>
                                        </td>
										<td>
											<a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
												<?= StringHelper::toYesNo($row->annual); ?>
											</a>
										</td>
                                        <td class="text-end">
											<a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
											<?php
											if ($row->active_from) {
												?>
	                                            <div class="d-flex flex-column w-100">
	                                                <div class="d-flex flex-stack mb-2">
	                                                    <span>
															<?php
															if ($row->active_from) {
																$percent = 0;
																if ($row->status == 'active') {
																	$percent = 100;
																	echo 'Now';
																} else {
																	$days = DateHelper::numberOfDays(date('Y-m-d'), $row->active_from);
																	$percent = ((365 - $days) / 365) * 100;
																	echo $days . ' days';
																}
															}
															?>
	                                                    </span>
	                                                </div>
	                                                <div class="progress h-6px w-100">
	                                                    <div
															class="progress-bar bg-primary"
															role="progressbar"
															style="width: <?= $percent; ?>%"></div>
	                                                </div>
	                                            </div>
                                                <!--<div>
                                                    <br/>
                                                    <?= DateHelper::pretty($row->active_from, false); ?> to <br/>
                                                    <?= DateHelper::pretty($row->active_to, false); ?>
                                                </div>-->
												<?php
											} else {
												?>
												<span class="text-muted">N/A</span>
												<?php
											}
											?>
											</a>
                                        </td>
                                        <td>
                                            <a
                                                href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
                                                class="btn btn-blank float-right"
                                                title="Edit the theme"
                                                data-toggle="tooltip"
                                                data-trigger="hover"
                                                data-dismiss="click"
                                                data-placement="top">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                </svg>
                                            </a>
                                            <?php
                                            if (!$row->deleted_at) {
                                                ?>
                                                <button
                                                    type="button"
                                                    class="btn btn-blank float-right"
                                                    data-original-title="Are you sure?"
                                                    data-trigger="focus"
                                                    data-html="true"
                                                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                                    data-toggle="popover">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </button>
                                                <?php
                                            } else {
                                                ?>
                                                <button
                                                    type="button"
                                                    class="btn btn-blank float-right"
                                                    data-original-title="Are you sure?"
                                                    data-trigger="focus"
                                                    data-html="true"
                                                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
                                                    data-toggle="popover">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                                    </svg>
                                                </button>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                            </tbody>
                        </table>
                    </form>
                    <?php
                } else {
                    ?>
                    <strong class="h5">No results</strong>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
