<?php
/**
 * Templates add template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->cms . '/templates';
echo $this->partial("common/form/messages");
?>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/save'); ?>">
    <div class="row mb-4">
        <div class="col-12">
            <button
                id="btn-save"
                class="btn btn-primary float-right m-0 p-3"
                type="button"
                title="Save my template"
                data-toggle="tooltip"
                data-trigger="hover"
                data-dismiss="click"
                data-placement="top">
                Save
            </button>
            <button
                type="button"
                title="Are you sure?"
                data-html="true"
                data-trigger="focus"
                data-toggle="popover"
                data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/build'); ?>">Yes</a>'
                class="btn btn-default float-right m-0 mr-2 p-3">
                <div
                    title="Start over with a fresh template"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    Reset
                </div>
            </button>
            <a
                href="<?= UrlHelper::backend($url); ?>"
                class="btn btn-default m-0 mr-2 p-3"
                title="Go back to the templates list"
                data-toggle="tooltip"
                data-trigger="hover"
                data-dismiss="click"
                data-placement="bottom">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4.854 1.146a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L4 2.707V12.5A2.5 2.5 0 0 0 6.5 15h8a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 12.5V2.707l3.146 3.147a.5.5 0 1 0 .708-.708l-4-4z"/>
                </svg>
            </a>
        </div>
    </div>
    <div class="row">
		<div class="col-12 mb-3">
			Required fields <span class="required">*</span>
		</div>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <div
                                class="preview-img"
                                title="I'm inactive"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/new-item.png'); ?>" 
                                        alt="Add an entry">
                                    <div
                                        title="I'm inactive"
                                        class="position-absolute circle bg-warning"
                                        style="width: 10px;height: 10px;margin-top: -5px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="name">
                                    Name
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name'); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="slug">
                                    Slug
                                </label>
                                <input
                                    id="slug"
                                    name="slug"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="slug"
                                    value="<?= FormController::getFormData('slug'); ?>">
                                <small>If you don't want to set one I'll generate one for you</small>
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab">
                                Settings <span class="required">*</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <span class="card-title">Some additional settings</span>
                                </div>
                                <div class="card-body pt-0 mb-4">
                                    <div class="form-group form-check mb-4">
                                        <label for="default">
                                            Make me default
                                        </label>
                                        <div class="checkbox switcher mt-2">
                                            <label>
                                                <input
                                                    id="default"
                                                    type="checkbox"
                                                    name="default"
                                                    value="1"
                                                    <?= FormController::getFormData('default') ? ' checked="checked"' : ''; ?>>
                                                <span>
                                                    <small class="switcher-on">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                        </svg>
                                                    </small>
                                                    <small class="switcher-off">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                        </svg>
                                                    </small>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="file">
                                            File name of the template
                                            <span class="required">*</span>
                                        </label>
                                        <input
                                            id="file"
                                            name="file"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="file"
                                            value="<?= FormController::getFormData('file'); ?>"
											required>
                                        <small>It can include the local folder its in, i.e. page/view</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
