<?php
/**
 * Template index template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->cms . '/templates';

$templates = [];
if ($data) {
	foreach ($data as $row) {
		$splits = explode('/', $row->file);

		if (count($splits) == 1) {
			$templates[$row->file] = $row->id;
			continue;
		}

		$tmp = &$templates;
	    $end_key = count($splits) - 1;

	    foreach ($splits as $key => $value) {
	        if ($end_key != $key) {
	            if (empty($tmp[$value])) {
	                $tmp[$value] = array();
	            }
	            $tmp = &$tmp[$value];
	        } else {
	            @$tmp[$value] = $row->id . (!empty($row->deleted) ? '-deleted' : '');
	            unset($templates[$row->file]);
	        }
	    }
	}
}

function outputChildren($folder, $children) {
	$html = '<li><span><a data-toggle="collapse" href="#folder-' . $folder . '" aria-expanded="false" aria-controls="folder-' . $folder . '">';
	$html .= '<i class="collapsed">';
	$html .= '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/></svg>';
	$html .= '</i>';
	$html .= '<i class="expanded">';
	$html .= '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M1 3.5A1.5 1.5 0 0 1 2.5 2h2.764c.958 0 1.76.56 2.311 1.184C7.985 3.648 8.48 4 9 4h4.5A1.5 1.5 0 0 1 15 5.5v.64c.57.265.94.876.856 1.546l-.64 5.124A2.5 2.5 0 0 1 12.733 15H3.266a2.5 2.5 0 0 1-2.481-2.19l-.64-5.124A1.5 1.5 0 0 1 1 6.14V3.5zM2 6h12v-.5a.5.5 0 0 0-.5-.5H9c-.964 0-1.71-.629-2.174-1.154C6.374 3.334 5.82 3 5.264 3H2.5a.5.5 0 0 0-.5.5V6zm-.367 1a.5.5 0 0 0-.496.562l.64 5.124A1.5 1.5 0 0 0 3.266 14h9.468a1.5 1.5 0 0 0 1.489-1.314l.64-5.124A.5.5 0 0 0 14.367 7H1.633z"/></svg>';
	$html .= '</i>&nbsp;' . $folder . '</a></span>';

	$html .= '<ul><div id="folder-' . $folder . '" class="collapse' . (!empty($_GET['search']) ? ' show' : '') . '">';
	if (is_array($children)) {
		foreach ($children as $child_folder => $childs) {
			if (is_array($childs)) {
				$html .= outputChildren($child_folder, $childs);
			} else {
				$html .= outputSingle($folder, $child_folder, $childs);
			}
		}
	} else {
		$html .= outputSingle($folder, $children);
	}
	$html .= '</div></ul></li>';

	return $html;
}

function outputSingle($folder, $file, $id) {
	$html = '<li data-target="#file-' . $id . '" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse"><span><a href="#" class="template-file' . (strpos($id, '-deleted') !== false ? ' text-strikethrough' : '') . '" data-folder="' . $folder . '">';
	$html .= '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16"><path d="M7 4.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0zm-.861 1.542 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V7.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V7s1.54-1.274 1.639-1.208zM5 9a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1H5z"/><path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/></svg>&nbsp;';
	$html .= $file . '</a></span></li>';

	return $html;
}

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
			</div>
		</div>
	</div>
</div>
<form id="form-edit" class="row mb-5" method="post" action="<?= UrlHelper::backend($url . '/files'); ?>">
	<div class="col-md-12 col-lg-6">
		<div class="card">
			<div class="card-body p-3 pt-0">
				<div class="row">
					<div class="col-12">
						<h4 class="card-title float-left">Files</h4>
						<button
				            id="btn-add-file"
				            class="btn btn-default float-right"
				            type="button"
							data-target="#add-file"
							aria-expanded="true"
							aria-controls="collapseOne"
							data-toggle="collapse">
							<span
								title="Add a template"
					            data-toggle="tooltip"
					            data-trigger="hover"
					            data-dismiss="click"
					            data-placement="top">
								<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" viewBox="0 0 16 16">
  									<path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5z"/>
  									<path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5L14 4.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5h-2z"/>
								</svg>
							</span>
				        </button>
					</div>
					<div class="col-12">
						<?php
						if ($data) {
							?>
							<div class="tree">
								<ul>
									<li>
										<span class="text-primary">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
												<path d="M1 3.5A1.5 1.5 0 0 1 2.5 2h2.764c.958 0 1.76.56 2.311 1.184C7.985 3.648 8.48 4 9 4h4.5A1.5 1.5 0 0 1 15 5.5v.64c.57.265.94.876.856 1.546l-.64 5.124A2.5 2.5 0 0 1 12.733 15H3.266a2.5 2.5 0 0 1-2.481-2.19l-.64-5.124A1.5 1.5 0 0 1 1 6.14V3.5zM2 6h12v-.5a.5.5 0 0 0-.5-.5H9c-.964 0-1.71-.629-2.174-1.154C6.374 3.334 5.82 3 5.264 3H2.5a.5.5 0 0 0-.5.5V6zm-.367 1a.5.5 0 0 0-.496.562l.64 5.124A1.5 1.5 0 0 0 3.266 14h9.468a1.5 1.5 0 0 0 1.489-1.314l.64-5.124A.5.5 0 0 0 14.367 7H1.633z"/>
											</svg>
											views
										</span>
										<div id="views" class="collapse show">
											<ul>
												<?php
												foreach ($templates as $folder => $children) {
													if (is_array($children)) {
														echo outputChildren($folder, $children);
													} else {
														echo outputSingle('views', $folder, $children);
													}
												}
												?>
											</ul>
										</div>
									</li>
								</ul>
							</div>
							<?php
						} else {
							?>
                			<strong class="h5">No results</strong>
							<?php
						}
						?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php
	if ($data) {
		?>
		<div class="col-md-12 col-lg-6">
			<div class="row">
				<div class="col-12 mb-2">
					<div class="card p-0">
						<div class="card-body">
							<button
								id="btn-save"
								class="btn btn-blank float-right"
								type="button"
								title="Save my page"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="top">
								<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                            		<path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        		</svg><br/>
								save
							</button>
						</div>
					</div>
				</div>
				<div class="col-12 mb-5">
					<div class="collapse w-100" id="add-file">
						<div class="card">
							<div class="card-header mb-2">
								<h4 class="card-title mb-1">Add a new template</h4>
							</div>
				            <div class="card-body p-3 pt-0">
								<div class="form-group mb-4">
									<label>
										Place into folder
										<span class="required">*</span>
									</label>
									<?php
										$selected = FormController::getFormData('folder_new');
									?>
									<select
				                        name="folder_new"
				                        class="form-control mt-2"
				                        data-placeholder="Please select a folder"
				                        tabindex="-1"
				                        aria-hidden="true"
										required>
				                        <option value="">views</option>
										<?php
										foreach ($folders as $folder) {
											?>
											<option value="<?= $folder; ?>"<?= $folder == $selected ? ' selected' : '';?>><?= $folder; ?></option>
											<?php
										}
										?>
				                    </select>
								</div>
								<div class="form-group mb-4">
									<label>
										File
										<span class="required">*</span>
									</label>
									<input
										name="file_new"
										type="text"
										class="form-control mt-2"
										value="<?= FormController::getFormData('file_new'); ?>"
										required>
									<small>Only .phtml and .volt templates are supported</small>
								</div>
								<div class="form-group mb-4">
									<label>
										Label
									</label>
									<input
										name="name_new"
										type="text"
										class="form-control mt-2"
										value="<?= FormController::getFormData('name_new'); ?>">
									<small>Label the file if you'd like or I'll just use the filename</small>
								</div>
								<div class="form-group form-check mb-4">
									<label>
										Make me default
									</label>
									<div class="checkbox switcher mt-2">
										<label>
											<input
												type="checkbox"
												name="default_new"
												value="1"
												<?= FormController::getFormData('default_new') ? ' checked="checked"' : ''; ?>>
											<span>
												<small class="switcher-on">
													<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
														<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
													</svg>
												</small>
												<small class="switcher-off">
													<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
														<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
													</svg>
												</small>
											</span>
										</label>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card">
						<div class="card-header mb-2">
							<h4 class="card-title mb-1">File details</h4>
						</div>
			            <div id="file-details" class="card-body accordion p-3 pt-0">
							<div class="collapse show" data-parent="#file-details">
								Please select a file
							</div>
							<?php
							foreach ($data as $row) {
								?>
								<div id="file-<?= $row->id . (!empty($row->deleted) ? '-deleted' : ''); ?>" class="collapse" data-parent="#file-details">
									<div class="form-group mb-4">
										<label>
											Label
										</label>
										<input
											name="name[<?= $row->id; ?>]"
											type="text"
											class="form-control mt-2"
											value="<?= $row->name; ?>">
									</div>
									<div class="form-group form-check mb-4">
										<label>
											Make me default
										</label>
										<div class="checkbox switcher mt-2">
											<label>
												<input
													type="checkbox"
													name="default[<?= $row->id; ?>]"
													value="1"
													<?= $row->default ? ' checked="checked"' : ''; ?>>
												<span>
													<small class="switcher-on">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
														</svg>
													</small>
													<small class="switcher-off">
														<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
															<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
														</svg>
													</small>
												</span>
											</label>
										</div>
									</div>
									<div class="form-group mb-4">
									<?php
						            if ($row->deleted_at) {
						                ?>
						                <button
											class="btn btn-blank float-right"
						                    type="button"
						                    data-original-title="Are you sure?"
						                    data-html="true"
						                    data-trigger="focus"
						                    data-toggle="popover"
						                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id); ?>">Yes</a>'
						                >
						                    <div
						                        data-toggle="tooltip"
						                        data-dismiss="hover"
						                        data-placement="top"
						                        title="Recover the template from the trash">
						                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
													<path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
												</svg><br/>
												recover
						                    </div>
						                </button>
						                <?php
						            } else {
						            ?>
						                <button
						                    class="btn btn-blank float-right"
						                    type="button"
						                    data-original-title="Are you sure?"
						                    data-html="true"
						                    data-trigger="focus"
						                    data-toggle="popover"
						                    data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>">Yes</a>'>
						                    <div
						                        data-toggle="tooltip"
						                        data-dismiss="hover"
						                        data-placement="top"
						                        title="Throw the template into the trash">
						                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
													<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
													<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
												</svg><br/>
												delete
						                    </div>
						                </button>
						                <?php
						            }
						            ?>
									</div>
								</div>
								<?php
							}
							?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php
	}
	?>
</form>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
