<?php
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
$crumbs = UrlHelper::breadcrumbs();
?>
<div id="page" class="col-12">
    <div class="container-fluid">
        <div class="container">
            <section>
                <!--<div class="page-content">
                    
                    <?php
                    if ($page->content && empty($page->summary)) {
                        ?>
                        <div class="page-body">
                            <?= $page->content; ?>
                        </div>
                        <?php
                    }
                    ?>
                </div>-->
                <?php            
                if (!empty($page->banner_image)) {
                    ?>
                    <div class="page-background-image">
                        <img src="<?= $page->banner_image->url; ?>" alt="<?= $page->banner_image->label; ?>">
                    </div>
                    <?php
                }
                ?>
                <?= $this->partial('common/theme_animation'); ?>
            </section>
        </div>
        <div id="page-summary" class="col-12">
            <nav class="page-crumbs" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <?php
                    $key = 1;
                    foreach ($crumbs as $name => $url) {
                        if ($key == count($crumbs)) {
                            ?>
                            <li class="breadcrumb-item active">
                                <a href="<?= $page->url; ?>"><h2><?= $page->name; ?></h2></a>
                            </li>
                            <?php
                        } else {
                            ?>
                            <li class="breadcrumb-item">
                                <a href="<?= $url; ?>"><?= ucwords($name); ?></a>
                            </li>
                            <?php
                        }
                        $key++;
                    }
                    ?>
                </ol>
            </nav>
            <?php
            if ($page->summary) {
                ?>
                <div>
                    <?= $page->summary; ?>
                </div>
                <?php
            }
            ?>
        </div>
        <div class="category-pages col-12">
            <?= $this->partial('common/category_latest_reviews'); ?>            
        </div>
    </div>
</div>