<?php
/**
 * Main dashboard template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.2
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Tengu\Controllers\Core\UsersController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
use Kytschi\Tengu\Models\Core\Logs;

$user = UsersController::getUser();
$logs = (new Logs())->find([
    'order' => 'created_at DESC',
    'limit' => 5
]);

$url = '/';
$filter_year = $this->tengu->getFilters('year');
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>
<link rel="stylesheet" href="<?= $this->tengu->theme->getAsset('plugins/leaflet/leaflet.css');?>" type="text/css" />
<script src="<?= $this->tengu->theme->getAsset('plugins/leaflet/leaflet.js');?>"></script>
<div class="row">
    <div class="col-xl-12 pb-3">
		<h2>Hi <?= $this->tengu->getUser('first_name'); ?> and welcome!</h2>
	</div>
</div>
<?php
$diff = 0;
$colour = 'warning';
if ($previous['before_last']) {
	$diff = $previous['last_month'] - $previous['before_last'];
	if ($diff < 0) {
		$colour = 'warning';
	} else {
		$colour = 'primary';
	}
}
?>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-<?= $colour; ?>">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
					<path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $previous['last_month']; ?></strong>
					<?php
					if ($diff) {
						?>
						<small> 
							<?= $diff; ?>
							<?php
							if ($colour == 'warning') {
								?>
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M1 3.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5zM8 6a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 .708-.708L7.5 12.293V6.5A.5.5 0 0 1 8 6z"/>
								</svg>
								<?php
							} else {
								?>
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5zm-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5z"/>
								</svg>
								<?php
							}
							?>
						</small>
						<?php
					}
					?>
                </div>
                <div class="text-white">
					Last month
				</div>
            </div>
		</div>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
                            <label class="form-label fw-bold">Year starting:</label>
		                    <select
		                        name="filters[year]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($years as $year) {
                                    ?>
                                    <option value="<?= $year; ?>"<?= $filter_year == $year ? ' selected="selected"' : ''; ?>>
                                        <?= $year; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>				
			</div>
		</div>
	</div>
</div>
<?php
if ($this->tengu->isAdmin()) {
	?>
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Visitors this year</span>
            </div>
            <div class="card-body">
				<?php
				if (count($visitors)) {
					?>
					<canvas id="visitors" width="600" height="200"></canvas>
					<script type="text/javascript">
					var ctx = document.getElementById('visitors').getContext('2d');
					var orders = new Chart(ctx, {
						type: 'line',
						data: {
							labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
							datasets: [
								<?php
								$colours = [
									'visitors' => '#00c129',
									'unique' => '#1D8CF8',
									'bot' => '#E14ECA',
								];

								foreach ($visitors as $label => $stats) {
									$values = '';
									foreach ($stats as $value) {
										$values .= $value . ',';
									}
									?>
									{
										label: '<?= ucwords($label); ?>',
										data: [<?= rtrim($values, ','); ?>],
										fill: false,
										backgroundColor: '<?= $colours[$label]; ?>',
										borderColor: '<?= $colours[$label]; ?>',
										tension: 0.1
									},
									<?php
								}
								?>
							]
						},
						options: {
							scales: {
								y: {
									beginAtZero: true
								}
							}
						}
					});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No vistors</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-xl-12">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Visitors map</span>
            </div>
            <div class="card-body">
				<div id="map" style="width: 100%; height:600px; background-color:#AAD3DF"></div>
				<script type="text/javascript">
					var map = L.map('map');

					/*L
						.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
							maxZoom: 19,
							noWrap: true,
							attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a>'
						})
						.addTo(map);*/

						L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
							attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
							subdomains: 'abcd',
							maxZoom: 20,
							noWrap: true
						}).addTo(map);

					var markers = map.createPane('markers');
					
					<?php
					foreach ($visitors_map as $marker) {
						?>
						L.circleMarker(
							[
								<?= $marker->latitude; ?>,
								<?= $marker->longitude; ?>
							], {
							pane: 'markers',
							"radius": 5,
							"fillColor": "#ff7800",
							"color": "#ff7800",
							"weight": 1,
							"opacity": 1
							}).addTo(map);
						<?php
					}
					?>
					map.setView({lat: 50, lng: 0}, 2.5);
				</script>
			</div>
		</div>
	</div>
	<div class="col-6">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Referrers</span>
            </div>
            <div class="card-body">
				<?php
				if (count($referrers)) {
					?>
					<canvas id="referrers" width="600" height="400"></canvas>
					<script type="text/javascript">
					var ctx_referrers = document.getElementById('referrers').getContext('2d');
					var referrers = new Chart(ctx_referrers, {
						type: 'doughnut',
						data: {
							<?php
							$labels = [];
							$totals = [];
							$colours = [];

							foreach ($referrers as $key => $values) {
								$labels[] = '"' . $values['referer'] . '"';
								$totals[] = $values['total'];
								$colours[] = '"#' . substr(md5($values['referer']), 3, 6) . '"';
							}
							?>
							labels: [<?= implode(',', $labels); ?>],
							datasets: [
								{
									label: 'referrers',
									data: [<?= implode(',', $totals); ?>],
									backgroundColor: [<?= implode(',', $colours); ?>],
									borderColor: "#5E5E60",
									borderWidth: 0.4
								},
							]
						},
						options: {
						}
					});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No referrers</strong>
					<?php
				}
				?>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
				<span class="card-title">Browsers</span>
            </div>
            <div class="card-body">
				<?php
				if (count($browsers)) {
					?>
					<canvas id="browsers" width="600" height="400"></canvas>
					<script type="text/javascript">
						var ctx_browsers = document.getElementById('browsers').getContext('2d');
						
						var browsers = new Chart(ctx_browsers, {
							type: 'doughnut',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($browsers as $key => $values) {
									$labels[] = '"' . $values['browser'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['browser']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'browsers',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
							}
						});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No browsers detected</strong>
					<?php
				}
				?>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
				<span class="card-title">Operating systems</span>
            </div>
            <div class="card-body">
				<?php
				if (count($operating_systems)) {
					?>
					<canvas id="operating_systems" width="600" height="400"></canvas>
					<script type="text/javascript">
						var ctx_operating_systems = document.getElementById('operating_systems').getContext('2d');
						
						var operating_systems = new Chart(ctx_operating_systems, {
							type: 'doughnut',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($operating_systems as $key => $values) {
									$labels[] = '"' . $values['operating_system'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['operating_system']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'operating_systems',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
							}
						});
					</script>
				<?php
				} else {
					?>
					<strong class="h5">No operating systems detected</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-6">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Bots</span>
            </div>
            <div class="card-body">
				<?php
				if (count($bots)) {
					?>
					<canvas id="bots" width="600" height="<?= ($height = count($bots) * 30) < 200 ? 200 : $height ; ?>"></canvas>
					<script type="text/javascript">
						var ctx_bots = document.getElementById('bots').getContext('2d');
						
						var bots = new Chart(ctx_bots, {
							type: 'horizontalBar',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($bots as $key => $values) {
									$labels[] = '"' . $values['bot'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['bot']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'bots',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
								indexAxis: 'y',
								responsive: true,
								legend: {
									display: false
								},
								plugins: {
									legend: {
										position: 'right'
									},
									title: {
										display: false
									}
								}
							}
						});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No bots detected</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-12">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Most viewed</span>
            </div>
            <div class="card-body">
				<table class="table">
					<thead>
						<tr>
							<th width="50px">&#35;</th>
							<th>Name</th>
							<th>URL</th>
							<th width="180px">Type</th>
							<th width="180px">Spinner</th>
							<th width="160px">Views</th>
						</tr>
					</thead>
					<tbody>
						<?php
						foreach ($most_viewed as $key => $result) {
							
							switch ($result->type) {
								case 'blog-post':
									$url = '/cms/blog-posts/edit/';
									$class = 'warning';
									break;
								case 'blog-post-category':
									$url = '/cms/blog-posts/categories/edit/';
									$class = 'warning';
									break;
								case 'portfolio':
									$url = '/cms/portfolio/edit/';
									$class = 'primary';
									break;
								case 'portfolio-category':
									$url = '/cms/portfolio/categories/edit/';
									$class = 'primary';
									break;
								case 'page-category':
									$url = '/cms/pages/categories/edit/';
									$class = 'success';
									break;
								default:
									$url = '/cms/pages/edit/';
									$class = 'success';
									break;
							}
							?>
							<tr>
								<td><?= $key + 1; ?></td>
								<td>
									<a href="<?= UrlHelper::backend($url . $result->id); ?>">
										<?= $result->name; ?>
									</a>
								</td>
								<td>
									<a href="<?= UrlHelper::backend($url . $result->id); ?>"><?= $result->url; ?></a>
								</td>
								<td>
									<span class="badge badge-<?= $class; ?>">
										<?= str_replace('-', ' ', $result->type); ?>
									</span>
								</td>
								<td>
									<span class="badge badge-<?= $result->spinnable ? 'success' : 'danger'; ?>">
										<?= StringHelper::toYesNo($result->spinnable); ?>
									</span>
								</td>
								<td>
									<?php
										$total_class = 'danger';
										if ($result->total >= 100 && $result->total < 500) {
											$total_class = 'warning';
										} elseif ($result->total >= 500 && $result->total < 1000) {
											$total_class = 'primary';
										} elseif ($result->total >= 1000) {
											$total_class = 'success';
										}
									?>
									<span class="badge badge-<?= $total_class; ?>">
										<?= $result->total; ?>
									</span>
								</td>
							</tr>
							<?php
						}
						?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
	<?php
}
?>
