<?php
/**
 * Main dashboard template.
 *
 * @copyright   2023 Kytschi
 * @version     0.0.2
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\UsersController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
use Kytschi\Tengu\Models\Core\Logs;

$user = UsersController::getUser();
$logs = (new Logs())->find([
    'order' => 'created_at DESC',
    'limit' => 5
]);

$url = '/';
$filter_year = $this->tengu->getFilters('year');
?>
<script src="<?= $this->tengu->theme->getAsset('js/plugins/chartjs.min.js'); ?>"></script>
<div class="row">
    <div class="col-xl-12 pb-3">
		<h2>Hi <?= $this->tengu->getUser('first_name'); ?> and welcome!</h2>
	</div>
</div>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
                            <label class="form-label fw-bold">Year starting:</label>
		                    <select
		                        name="filters[year]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($years as $year) {
                                    ?>
                                    <option value="<?= $year; ?>"<?= $filter_year == $year ? ' selected="selected"' : ''; ?>>
                                        <?= $year; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>				
			</div>
		</div>
	</div>
</div>
<?php
if ($this->tengu->isAdmin()) {
	?>
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Visitors this year</span>
            </div>
            <div class="card-body">
				<?php
				if (count($visitors)) {
					?>
					<canvas id="visitors" width="600" height="200"></canvas>
					<script type="text/javascript">
					var ctx = document.getElementById('visitors').getContext('2d');
					var orders = new Chart(ctx, {
						type: 'line',
						data: {
							labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
							datasets: [
								<?php
								$colours = [
									'visitors' => '#00c129',
									'unique' => '#1D8CF8',
									'bot' => '#E14ECA',
								];

								foreach ($visitors as $label => $stats) {
									$values = '';
									foreach ($stats as $value) {
										$values .= $value . ',';
									}
									?>
									{
										label: '<?= ucwords($label); ?>',
										data: [<?= rtrim($values, ','); ?>],
										fill: false,
										backgroundColor: '<?= $colours[$label]; ?>',
										borderColor: '<?= $colours[$label]; ?>',
										tension: 0.1
									},
									<?php
								}
								?>
							]
						},
						options: {
							scales: {
								y: {
									beginAtZero: true
								}
							}
						}
					});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No vistors</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-6">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Referrers</span>
            </div>
            <div class="card-body">
				<?php
				if (count($referrers)) {
					?>
					<canvas id="referrers" width="600" height="400"></canvas>
					<script type="text/javascript">
					var ctx_referrers = document.getElementById('referrers').getContext('2d');
					var referrers = new Chart(ctx_referrers, {
						type: 'doughnut',
						data: {
							<?php
							$labels = [];
							$totals = [];
							$colours = [];

							foreach ($referrers as $key => $values) {
								$labels[] = '"' . $values['referer'] . '"';
								$totals[] = $values['total'];
								$colours[] = '"#' . substr(md5($values['referer']), 3, 6) . '"';
							}
							?>
							labels: [<?= implode(',', $labels); ?>],
							datasets: [
								{
									label: 'referrers',
									data: [<?= implode(',', $totals); ?>],
									backgroundColor: [<?= implode(',', $colours); ?>],
									borderColor: "#5E5E60",
									borderWidth: 0.4
								},
							]
						},
						options: {
						}
					});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No referrers</strong>
					<?php
				}
				?>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
				<span class="card-title">Browsers</span>
            </div>
            <div class="card-body">
				<?php
				if (count($browsers)) {
					?>
					<canvas id="browsers" width="600" height="400"></canvas>
					<script type="text/javascript">
						var ctx_browsers = document.getElementById('browsers').getContext('2d');
						
						var browsers = new Chart(ctx_browsers, {
							type: 'doughnut',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($browsers as $key => $values) {
									$labels[] = '"' . $values['browser'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['browser']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'browsers',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
							}
						});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No browsers detected</strong>
					<?php
				}
				?>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
				<span class="card-title">Operating systems</span>
            </div>
            <div class="card-body">
				<?php
				if (count($operating_systems)) {
					?>
					<canvas id="operating_systems" width="600" height="400"></canvas>
					<script type="text/javascript">
						var ctx_operating_systems = document.getElementById('operating_systems').getContext('2d');
						
						var operating_systems = new Chart(ctx_operating_systems, {
							type: 'doughnut',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($operating_systems as $key => $values) {
									$labels[] = '"' . $values['operating_system'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['operating_system']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'operating_systems',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
							}
						});
					</script>
				<?php
				} else {
					?>
					<strong class="h5">No operating systems detected</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-6">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Bots</span>
            </div>
            <div class="card-body">
				<?php
				if (count($bots)) {
					?>
					<canvas id="bots" width="600" height="<?= ($height = count($bots) * 30) < 200 ? 200 : $height ; ?>"></canvas>
					<script type="text/javascript">
						var ctx_bots = document.getElementById('bots').getContext('2d');
						
						var bots = new Chart(ctx_bots, {
							type: 'horizontalBar',
							data: {
								<?php
								$labels = [];
								$totals = [];
								$colours = [];

								foreach ($bots as $key => $values) {
									$labels[] = '"' . $values['bot'] . '"';
									$totals[] = $values['total'];
									$colours[] = '"#' . substr(md5($values['bot']), 3, 6) . '"';
								}
								?>
								labels: [<?= implode(',', $labels); ?>],
								datasets: [
									{
										label: 'bots',
										data: [<?= implode(',', $totals); ?>],
										backgroundColor: [<?= implode(',', $colours); ?>],
										borderColor: "#5E5E60",
										borderWidth: 0.4
									},
								]
							},
							options: {
								indexAxis: 'y',
								responsive: true,
								legend: {
									display: false
								},
								plugins: {
									legend: {
										position: 'right'
									},
									title: {
										display: false
									}
								}
							}
						});
					</script>
					<?php
				} else {
					?>
					<strong class="h5">No bots detected</strong>
					<?php
				}
				?>
            </div>
        </div>
    </div>
	<div class="col-12">
        <div class="card">
            <div class="card-header">
				<span class="card-title">Most viewed</span>
            </div>
            <div class="card-body">
				<table class="table">
					<thead>
						<tr>
							<th width="50px">&#35;</th>
							<th>Name</th>
							<th>URL</th>
							<th width="180px">Type</th>
							<th width="180px">Spinner</th>
							<th width="160px">Views</th>
						</tr>
					</thead>
					<tbody>
						<?php
						foreach ($most_viewed as $key => $result) {
							
							switch ($result->type) {
								case 'blog-post':
									$url = '/cms/blog-posts/edit/';
									$class = 'warning';
									break;
								case 'blog-post-category':
									$url = '/cms/blog-posts/categories/edit/';
									$class = 'warning';
									break;
								case 'portfolio':
									$url = '/cms/portfolio/edit/';
									$class = 'primary';
									break;
								case 'portfolio-category':
									$url = '/cms/portfolio/categories/edit/';
									$class = 'primary';
									break;
								case 'page-category':
									$url = '/cms/pages/categories/edit/';
									$class = 'success';
									break;
								default:
									$url = '/cms/pages/edit/';
									$class = 'success';
									break;
							}
							?>
							<tr>
								<td><?= $key + 1; ?></td>
								<td>
									<a href="<?= UrlHelper::backend($url . $result->id); ?>">
										<?= $result->name; ?>
									</a>
								</td>
								<td>
									<a href="<?= UrlHelper::backend($url . $result->id); ?>"><?= $result->url; ?></a>
								</td>
								<td>
									<span class="badge badge-<?= $class; ?>">
										<?= str_replace('-', ' ', $result->type); ?>
									</span>
								</td>
								<td>
									<span class="badge badge-<?= $result->spinnable ? 'success' : 'danger'; ?>">
										<?= StringHelper::toYesNo($result->spinnable); ?>
									</span>
								</td>
								<td>
									<?php
										$total_class = 'danger';
										if ($result->total >= 100 && $result->total < 500) {
											$total_class = 'warning';
										} elseif ($result->total >= 500 && $result->total < 1000) {
											$total_class = 'primary';
										} elseif ($result->total >= 1000) {
											$total_class = 'success';
										}
									?>
									<span class="badge badge-<?= $total_class; ?>">
										<?= $result->total; ?>
									</span>
								</td>
							</tr>
							<?php
						}
						?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
	<?php
}
?>
