<?php
/**
 * List pagination template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com> Ltd
 * @version     0.0.1
 *
 * Copyright Kytschi Ltd - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Helpers\UrlHelper;

if (empty($data)) {
	return;
}

$limits = [30,100,250];
$limit = !empty($data->limit) ? intval($data->limit) : 30;
if (!empty($_GET['limit']) && in_array(intval($_GET['limit']), $limits)) {
    $limit = intval($_GET['limit']);
}

$start = intval($data->current / 5) * 5;
if ($start <= 0) {
    $start = 1;
}

$result_start = (($start - 1) * $limit) + 1;

$end = $start + 4;
$result_end = (($end - 1) * $limit) + 1;

if ($end > $data->last) {
    $end = $data->last;
    $result_end = $data->total_items;
}

if ($result_end == 0) {
	$result_start = 0;
}

if ($result_start) {
?>
<div class="row">
	<div class="col-12 mt-4 p-0">
		<div class="card">
			<div class="card-body p-0">
				<?php
				if ($result_start) {
					?>
					<ul class="pagination">
						<li class="page-item previous <?= $data->current == $data->first ? ' disabled' : ''; ?>">
							<a href="<?= UrlHelper::generate($url, ['page' => $data->current - 1 > $data->first ? $data->current - 1 : $data->first]); ?>" class="page-link">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
								</svg>
							</a>
						</li>
						<?php
						for ($iLoop = $start; $iLoop <= $end; $iLoop++) {
							?>
							<li class="page-item <?= $data->current == $iLoop ? 'active' :''; ?><?= $start == $end ? ' disabled text-muted' : ''; ?>">
								<a href="<?= UrlHelper::generate($url, ['page' => $iLoop]); ?>" class="page-link"><?= $iLoop; ?></a>
							</li>
							<?php
						}
						?>
						<li class="page-item next <?= $data->current == $data->last ? ' disabled text-muted' : ''; ?>">
							<a href="<?= UrlHelper::generate($url, ['page' => $data->current + 1 < $data->last ? $data->current + 1 : $data->last]); ?>" class="page-link">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
								</svg>
							</a>
						</li>
					</ul>
					<?php
				}
				?>
			</div>
		</div>
	</div>
</div>
<script src="/assets/js/core/pagination.js"></script>
<?php
}
?>
