<?php
if ($this->tengu->theme->getSlug()== "halloween") {
    ?>
    <div class="theme_animation">
        <?php
        function make_seed()
        {
        list($usec, $sec) = explode(' ', microtime());
        return $sec + $usec * 1000000;
        }
        srand(make_seed());

        $left = 0;
        $move = rand(50, 100);
        for ($iLoop=1; $iLoop <= 32; $iLoop++) {
            $left += 120;
            ?>
            <div class="ghost">
                <img src="/website/themes/halloween/assets/imgs/ghost<?= rand(1, 6); ?>.svg"/>
            </div>
            <style>
                .theme_animation div.ghost:nth-child(<?= $iLoop; ?>) {
                    left: <?= $left; ?>px;
                    animation: animate<?= $iLoop; ?> <?= rand(80, 100); ?>s linear infinite;
                    display: block;
                }
                @keyframes animate<?= $iLoop; ?> {
                    0% {
                        top: <?= rand(110, 150); ?>%;
                        left:  <?= $left + ($move *= -1); ?>px;
                        rotate: (0deg);
                    }
                    10% {
                        rotate: (5deg);
                    }
                    20% {
                        left: <?= $left + ($move *= -1); ?>px;
                        rotate: (0deg);
                    }
                    30% {
                        rotate: (5deg);
                    }
                    40% {
                        left:  <?= $left + ($move *= -1); ?>px;
                        rotate: (0deg);
                    }
                    50% {
                        rotate: (5deg);
                    }
                    60% {
                        left: <?= $left + ($move *= -1); ?>px;
                        rotate: (0deg);
                    }
                    70% {
                        rotate: (5deg);
                    }
                    80% {
                        left:  <?= $left + ($move *= -1); ?>px;
                        rotate: (0deg);
                    }
                    90% {
                        rotate: (5deg);
                    }
                    100% {
                        top: -<?= rand(0, 100); ?>%;
                        rotate: (1deg);
                    }
                }
            </style>
            <?php
        }
        ?>
    </div>
    <?php
} elseif (in_array($this->tengu->theme->getSlug(), ["new-year", "july-fourth"])) {
?>
<div class="theme_animation">
    <div class="pyro">
        <div class="before"></div>
        <div class="after"></div>
    </div>
</div>
<?php
} elseif ($this->tengu->theme->getSlug()== "xmas") {
    ?>
    <div class="theme_animation">
    <?php
        for ($i = 0; $i < 50; $i++) {
            ?>
            <div class="snow"></div>
            <?php
        }
    ?>
    </div>
    <?php
}
?>