<?php
use Kytschi\Tengu\Helpers\DateHelper;

if ($trending = $this->tengu->findTrendingSearch(10)) {
    if (!$trending->count()) {
        return;
    }
    ?>
    <div id="trending" class="row">
        <div class="col-12 p-0">
            <div class="col-12">
                <div class="container-fluid">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-12">
                                <span class="sub-heading-yellow">
                                    Trending
                                </span>
                            </div>
                        </div>
                        <div class="row">
                            <div id="trending-stats" class="col-12">
                                <?php
                                foreach ($trending as $item) {
                                    ?>
                                    <a href="/search?search=<?= urlencode($item->query); ?>">&#35;<?= htmlentities($item->query); ?></a>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>