<?php
/**
 * Board template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.2
 *
 * Copyright 2023 Mike Welsh

 */
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$my_id = FormController::getUserId();

$url = ($this->di->getConfig())->urls->pms;

if (file_exists($file = ($this->di->getConfig())->application->pluginsDir . 'umi/assets/js/board.js')) {
    echo '<script type="text/javascript">' . file_get_contents($file) . '</script>';
}

if (!empty($board->columns)) {
?>
<div class="row mt-3">
    <div id="accordion-board-entries" class="accordion col-12">
    <?php
        foreach ($board->columns as $column) {
            foreach ($column->entries as $sort => $entry) {
            ?>
            <form
                id="form-umi-edit-entry-<?= $entry->id; ?>"
                method="post"
                data-parent="#accordion-board-entries"
                action="<?= UrlHelper::backend($url . '/boards/entries/update'). '?from=' . urlencode($from . '?entry=' . 'form-umi-edit-entry-' . $entry->id); ?>"
                class="collapse page-collapse <?= UrlHelper::activeEntry('form-umi-edit-entry-' . $entry->id); ?>"
                enctype="multipart/form-data">
                <hr class="mb-4"/>
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="card p-0">
                            <div class="card-body">
                                <button
                                    type="button"
                                    class="btn btn-blank float-left btn-umi-entry-close"
                                    data-toggle="collapse"
                                    data-url="<?= UrlHelper::backend($from); ?>"
                                    data-target="#form-umi-edit-entry-<?= $entry->id; ?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                    </svg><br/>
                                    close
                                </button>
                                <button
                                    type="submit"
                                    class="btn btn-blank float-right">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                                    </svg><br/>
                                    save
                                </button>
                                <button
                                    id="btn-delete-umi-board-entry"
                                    type="button"
                                    class="btn btn-blank float-right mr-4"
                                    data-original-title="Are you sure?"
                                    data-trigger="focus"
                                    data-html="true"
                                    data-url="<?= UrlHelper::backend($url . '/boards/entries/delete/{id}'). (!empty($from) ? '?from=' . urlencode($from) : ''); ?>"
                                    data-content=''
                                    data-toggle="popover">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg><br/>
                                    delete
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-12">
                        <div class="card mb-3 p-0">
                            <div class="card-body">
                                <div class="card-header m-0">
                                    <span class="card-title">Board entry</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <input
                                            name="title"
                                            type="text"
                                            class="form-control form-control-bordered p-3"
                                            value="<?= $entry->title; ?>"
                                            placeholder="Please enter a title"
                                            required/>
                                    </div>
                                    <div class="form-group">
                                        <textarea
                                            name="description"
                                            class="form-control form-control-bordered p-3"													
                                            placeholder="Please enter a description"><?= $entry->description; ?></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="card-header m-0">
                                    <span class="card-title">Assign to</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <select class="form-control" name="assign_to">
                                            <?php
                                            foreach ($users as $user) {
                                                ?>
                                                <option 
                                                    <?= $user->id == $entry->assign_to ? 'selected' : ''; ?>
                                                    value="<?= $user->id; ?>">
                                                    <?= ($user->id == $my_id) ? 'Me' : $user->full_name; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card mb-3 p-0">
                            <div class="card-body">
                                <div class="card-header m-0">
                                    <span class="card-title">Due on</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <input
                                            name="due_on"
                                            type="text"
                                            class="form-control form-control-bordered p-3 datetimepicker"
                                            value="<?= DateHelper::pretty($entry->due_on, true, false, '', false); ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="card-header m-0">
                                    <span class="card-title">Attachments</span>
                                </div>
                                <div class="card-body">
                                    <div class="form-group mb-4">
                                        <label>File</label>
                                        <input
                                            name="file"
                                            type="file"
                                            accept="image/*, .pdf, .txt, .doc, .docx, .png, .jpg, .jpeg, .xml"
                                            class="form-control form-control-file mt-2"
                                            aria-describedby="file">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="file-label">Label</label>
                                        <input
                                            id="file_label"
                                            name="file_label[]"
                                            type="text"
                                            class="form-control mt-2"
                                            aria-describedby="file_label">
                                        <small>If you'd like to label the file to help easily identify it</small>
                                    </div>
                                    <?php
                                    if ($entry->attachments->count()) {
                                        ?>
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>File</th>
                                                    <th width="150px">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                foreach ($entry->attachments as $file) {
                                                    ?>
                                                    <tr>
                                                        <td><?= $file->label; ?></td>
                                                        <td>
                                                            <a
                                                                href="<?= $file->url; ?>"
                                                                class="btn btn-blank float-right mr-4"
                                                                title="Download the file"
                                                                data-toggle="tooltip"
                                                                data-trigger="hover"
                                                                data-dismiss="click"
                                                                data-placement="bottom">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                    <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                                                                    <path fill-rule="evenodd" d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
                                                                </svg>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-12">
                        <div class="card p-0">
                            <div class="card-body">
                                <div class="card-header m-0">
                                    <span class="card-title">Comments</span>
                                </div>
                                <div class="card-body pt-1">
                                    <?php
                                    echo $this->partial(
                                        'common/notes/list',
                                        [
                                            'notes' => $entry->notes,
                                            'url' => $from . '?clear=true&entry=form-umi-edit-entry-' . $entry->id,
                                            'form' => 'form-umi-edit-entry-' . $entry->id
                                        ]
                                    );
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="entry_id" value="<?= $entry->id; ?>"/>
                </div>
                <hr/>
            </form>
            <?php
            }
        }
        ?>
    </div>
</div>
<div class="row m-0 mb-5">
    <?php
    foreach ($board->columns as $column) {
        ?>
        <div class="col board-col">
            <div class="card">
                <div
                    class="umi-dropable-column card-header"
                    data-column="<?= $column->id; ?>"
                    data-sort="<?= $column->sort; ?>"
                    data-entry-status="<?= $column->entry_status; ?>"
                    ondblclick="umiShowColumn(this)">
                    <div
                        class="w-100"
                        title="Double click to edit the column"
                        data-toggle="tooltip"
                        data-trigger="hover"
                        data-dismiss="click"
                        data-placement="bottom"><?= $column->name; ?></div>
                </div>
                <form
                    id="umi-column-<?= $column->id; ?>"
                    class="card-body"
                    method="post"
                    action="<?= UrlHelper::backend($url . '/boards/columns/update-entries/' . $column->id) . (!empty($from) ? '?from=' . urlencode($from) : ''); ?>">
                    <ul 
                        id="umi-sortable-<?= $column->id; ?>"
                        class="umi-sortable-column sortable-column">
                        <?php
                        foreach ($column->entries as $sort => $entry) {
                            ?>
                            <li
                                class="board-entry ui-state-default"
                                id="umi-entry-<?= $entry->id; ?>"
                                data-id="<?= $entry->id; ?>"
                                data-sort="<?= $sort; ?>"
                                data-column="<?= $column->id; ?>"
                                ondblclick="umiShowEntry(this)">
                                <div
                                    title="Double click to edit the entry"
                                    class="w-100"
                                    data-toggle="tooltip"
                                    data-trigger="hover"
                                    data-dismiss="click"
                                    data-placement="bottom">
                                    <p class="pb-0 mb-1"><?= $entry->title; ?></p>
                                    <?php
                                    if ($entry->due_on) {
                                        ?>
                                        <small>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                                                <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                                                <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                                            </svg>
                                            <?= DateHelper::pretty($entry->due_on, true, false, '', false); ?>
                                        </small>
                                        <?php
                                    }
                                    ?>
                                    <textarea class="d-none"><?= $entry->description; ?></textarea>
                                    <input type="hidden" class="board-entry-sort" name="sort[]" value="<?= $sort; ?>"/>
                                    <input type="hidden" name="entry_id[]" value="<?= $entry->id; ?>"/>
                                </div>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>
                </form>
                <div class="card-footer">
                    <button
                        data-toggle="modal"
                        data-target="#modal-add-column-<?= $column->id; ?>"
                        class="btn btn-blank mt-2 p-0">
                        <span
                            title="Add board entry"
                            data-toggle="tooltip"
                            data-trigger="hover"
                            data-dismiss="click"
                            data-placement="bottom">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                            </svg>
                        </span>
                    </button>
                    <div class="modal" tabindex="-1" id="modal-add-column-<?= $column->id; ?>">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Add an entry</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                        <i class="tim-icons icon-simple-remove"></i>
                                    </button>
                                </div>
                                <form
                                    method="post"
                                    action="<?= UrlHelper::backend($url . '/boards/entries/add/' . $column->id). (!empty($from) ? '?from=' . urlencode($from) : '');?>">
                                    <div class="modal-body">
                                        <div class="form-group mb-4">
                                            Required fields <span class="required">*</span>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for="title" class="form-label">
                                                Title
                                                <span class="required">*</span>
                                            </label>
                                            <input
                                                name="title"
                                                type="text"
                                                class="form-control mt-2"
                                                value=""
                                                placeholder="Please enter a title"
                                                required/>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for="description" class="form-label">
                                                Description
                                            </label>
                                            <textarea
                                                name="description"
                                                class="form-control mt-2"													
                                                placeholder="Please enter a description"></textarea>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for="assign_to" class="form-label">
                                                Assign to
                                            </label>
                                            <select class="form-control" name="assign_to">
                                                <?php
                                                foreach ($users as $user) {
                                                    ?>
                                                    <option 
                                                        <?= $user->id == $my_id ? 'selected' : ''; ?>
                                                        value="<?= $user->id; ?>">
                                                        <?= ($user->id == $my_id) ? 'Me' : $user->full_name; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for="due_on" class="form-label">
                                                Due on
                                            </label>
                                            <input
                                                name="due_on"
                                                type="text"
                                                class="form-control form-control-bordered p-3 datetimepicker"
                                                value=""/>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Add</button>
                                    </div>
                                    <input type="hidden" name="sort" value="<?= $column->entries->count(); ?>"/>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
    ?>
</div>
<div class="modal" tabindex="-1" id="modal-edit-column">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update the column</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
            <form
                method="post"
                action="<?= UrlHelper::backend($url . '/boards/columns/update'). (!empty($from) ? '?from=' . urlencode($from) : ''); ?>">
                <div class="modal-body">
                    <div class="form-group mb-4">
                        Required fields <span class="required">*</span>
                    </div>
                    <div class="form-group mb-4">
                        <label for="name" class="form-label">
                            Title
                            <span class="required">*</span>
                        </label>
                        <input
                            name="name"
                            type="text"
                            class="form-control mt-2"
                            value=""
                            placeholder="Please enter a title"
                            required/>
                    </div>
                    <div class="form-group mb-4">
                        <label for="sort" class="form-label">Position</label>
                        <select
                            name="sort"
                            class="form-control form-control-solid"
                            data-placeholder="Please select the position of the column"
                            tabindex="-1"
                            aria-hidden="true">
                            <?php
                            for ($sort=0; $sort < $board->columns->count(); $sort++) {
                                ?>
                                <option value="<?= $sort; ?>"><?= $sort + 1; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group mb-4">
                        <label for="entry_status" class="form-label">Entry status</label>
                        <select
                            name="entry_status"
                            class="form-control form-control-solid"
                            data-placeholder="Set the entry status for this column if required"
                            tabindex="-1"
                            aria-hidden="true">
                            <option value="active">active</option>
                            <option value="complete">complete</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-12 p-0 m-0">
                        <button
                            type="button"
                            class="btn btn-danger float-left"
                            data-original-title="Are you sure?"
                            data-trigger="focus"
                            data-html="true"
                            data-url="<?= UrlHelper::backend($url . '/boards/columns/delete/{id}'). (!empty($from) ? '?from=' . urlencode($from) : ''); ?>"
                            data-content=''
                            data-toggle="popover">
                            Delete
                        </button>
                        <button type="submit" class="btn btn-primary float-right">Save</button>
                        <button type="button" class="btn btn-secondary float-right mr-2" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
                <input type="hidden" name="column_id" value=""/>
            </form>
        </div>
    </div>
</div>
<?php
} else {
    ?>
<div class="row mt-3 mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4>Invalid board</h4>
            </div>
        </div>
    </div>
</div>
    <?php
}
?>