<?php
/**
 * My board index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Helpers\UrlHelper;
$url = ($this->di->getConfig())->urls->pms . '/my-board';

echo $this->partial("common/form/messages");

if ($board) {
	echo $this->partial(
		'umi/my_board/board',
		[
			'board' => $board,
			'from' => $url
		]
	);
} else {
?>
	<div class="row mb-3">
		<div class="col-12">
			<div class="card">
				<div class="card-body">
					<p>
						This is the first time you are using this app so we'll need to create your board now.
					</p><br/>
					<a
						href="<?= UrlHelper::backend($url . '/create'); ?>"
						class="btn btn-primary"
						title="Create your board">
						Create
					</a>
				</div>
			</div>
		</div>
	</div>
<?php
}
?>