<?php
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="referrer" content="origin">
		<meta name="robots" content="<?= $this->tengu->settings->robots; ?>">
        <meta name="description" content="<?= $page->meta_description; ?>">
        <meta name="keywords" content="<?= $page->meta_keywords; ?>">
        <meta name="author" content="<?= $page->meta_author; ?>">
		<meta name="revised" content="<?= DateHelper::meta($page->page_updated); ?>">

        <title><?= (!empty($page->name) ? $page->name . ' - ' : '')  . $this->tengu->settings->name;?></title>

        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('bootstrap.min.css'); ?>">
        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('theme.css'); ?>">
        <link rel="icon" href="<?= $this->tengu->theme->getAsset('imgs/favicon.ico'); ?>" sizes="64x64">

        <link rel="canonical" href="<?= $this->tengu->canonicalUrl(); ?>">
        <link rel="author" href="/humans.txt">

        <script src="<?= $this->tengu->theme->getAsset('js/plugins/jquery.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/plugins/popper.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/plugins/bootstrap.min.js');?>"></script>

<!-- Start Open Web Analytics Tracker -->
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'https://stats.kytschi.com/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', 'bb0b3f0e9a9de37c4363197b4caefeeb']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/dist/owa.tracker.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
<!-- End Open Web Analytics Code -->
    </head>
    <body>
        <header>
            <?= $this->partial("common/menu"); ?>
        </header>
        <main>
            <div class="row m-0">
                <div class="col-12 p-0">
                    <?= $this->getContent(); ?>
                </div>
            </div>
        </main>
        <?= $this->partial('common/featured'); ?>
        <?= $this->partial('common/trending'); ?>
        <footer>
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="logo float-left">
                        <img src="<?= $this->tengu->theme->getAsset('imgs/logo.png'); ?>" alt="Talkopedia">
                    </div>
                    <div class="float-left pt-4">
                        <div class="copyright">
                            &copy;<?= date('Y'); ?>
                            <?= !empty($this->tengu->settings->company_name) ? $this->tengu->settings->company_name : $this->tengu->settings->name; ?>
                        </div>
                        <div class="powered-by">
                            <a href="https://tengu.kytschi.com" target="_blank">
                                Powered by Tengu
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <ul>
                        <?php
                        if ($footer_menu = $this->tengu->findMenu(['slug' => 'footer menu'])) {
                            foreach ($footer_menu->category_items as $item) {
                                $link = $item->link;
                                ?>
                                <li class="nav-item">
                                    <a
                                        href="<?= $link; ?>"
                                        class="nav-link<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                                        <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                                        title="Click to view the page, <?= $item->name; ?>">
                                        <?= $item->name; ?>
                                    </a>
                                </li>
                                <?php
                            }
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </footer>
	</body>
</html>
