<?php
/**
 * Form errors template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;

if ($err = FormController::getValidationError()) {
    $output = true;
    ?>
    <div class="alert alert-danger d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="text-white mb-1">Dang it!</h4>
            <p><?= $err->getMessage(); ?></p>
            <?php
            if ($err_data = $err->getData()) {
                ?>
                <ul>
                <?php
                foreach ($err_data as $item) {
                    ?>
                    <li><?= $item;?></li>
                    <?php
                }
                ?>
                </ul>
                <?php
            }
            ?>
        </div>
    </div>
    <?php
    echo '<script type="text/javascript">$(function (){form_changed = true;});</script>';
}

if ($errs = FormController::getFormErrors()) {
    $output = true;
    ?>
    <div class="alert alert-danger d-flex align-items-center">
        <div class="d-flex flex-column">
            <h4 class="text-white mb-1">Dang it!</h4>
            <?php
            foreach ($errs as $err) {
                ?>
                <p><?= $err; ?></p>
                <?php
            }
            ?>
        </div>
    </div>
    <?php
}

FormController::clearValidationError();
?>
