<?php
/**
 * Personas index template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->mms . '/personas';

$filter_status = $this->tengu->getFilters('status');
echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
	<div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=active'); ?>" class="card bg-primary">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
  					<path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
					<strong><?= $stats['active']; ?></strong> <?= $stats['active'] == 1 ? 'is' : 'are'; ?> live
				</div>
                <div class="text-white">
					Awesome
				</div>
            </div>
        </a>
    </div>
	<div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=inactive'); ?>" class="card bg-warning">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
  					<path fill-rule="evenodd" d="M11 7.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
					<strong><?= $stats['inactive']; ?></strong> <?= $stats['active'] == 1 ? 'is' : 'are'; ?> inactive
				</div>
                <div class="text-white">
					Inactive
				</div>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=deleted'); ?>" class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
  					<path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
					<strong><?= $stats['deleted']; ?></strong> <?= $stats['active'] == 1 ? 'is' : 'are'; ?> deleted
				</div>
                <div class="text-white">
					For the scrap heap
				</div>
            </div>
        </a>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
				<?php
				    $this->partial('common/lists/search', ['url' => $url]);
				?>
				<a href="<?= UrlHelper::backend($url . '/create'); ?>" class="btn btn-primary float-right">
		            Create
		        </a>
		        <div class="float-right dropdown mr-3">
		            <a
						href="#"
						class="btn btn-default form-control-solid dropdown-toggle"
						data-toggle="dropdown"
						role="button"
						aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
							<?php
								$this->partial('common/lists/sorting', ['url' => $url]);
							?>
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
		                        <option value="active"<?= $filter_status == 'active' ? ' selected="selected"' : ''; ?>>Active</option>
		                        <option value="pending"<?= $filter_status == 'inactive' ? ' selected="selected"' : ''; ?>>Inactive</option>
		                        <option value="deleted"<?= $filter_status == 'deleted' ? ' selected="selected"' : ''; ?>>Deleted</option>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
	<div class="col-12">
	<?php
	if ($data->total_items) {
		?>
		<div id="tiles">
			<?php
			foreach ($data->getItems() as $row) {
				switch ($row->status) {
					case 'active':
						$bg_colour = 'primary';
						break;
					case 'deleted':
						$bg_colour = 'danger';
						break;
					default:
						$bg_colour = 'primary';
						break;
				}
				?>
				<div class="tile-item">
					<div class="card p-2">
						<div class="card-body pb-0">
							<div class="row m-0">
								<div class="col-12 p-0 pb-3">
									<?php
									if ($row->profile_image) {
										?>
										<a
											href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
											class="profile-pic mr-3 float-left">
											<img src="<?= $row->profile_image->url; ?>" alt="<?= $row->full_name; ?>" />
										</a>
										<?php
									}
									?>
									<div class="float-left">
										<p class="h3 mb-0">
											<a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
												<?= ($row->title ? $row->title . ' ' : '') . $row->full_name; ?>
											</a>
										</p>
										<?php
										if ($row->job_title) {
											?>
											<p class="mb-0">
												<a href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>">
													<?= $row->job_title; ?> 
												</a>
											</p>
											<?php
										}
										?>
									</div>
								</div>
							</div>
						</div>
						<div class="card-footer">
							<span
								class="text-<?= $bg_colour;?> mr-4"
								title="Page is marked as <?= $row->status; ?>"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="top">
								<?php
								if ($row->status == 'active') {
									?>
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
										<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
										<path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
									</svg>
									<?php
								} else {
									?>
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
										<path fill-rule="evenodd" d="M6.146 5.146a.5.5 0 0 1 .708 0L8 6.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 7l1.147 1.146a.5.5 0 0 1-.708.708L8 7.707 6.854 8.854a.5.5 0 1 1-.708-.708L7.293 7 6.146 5.854a.5.5 0 0 1 0-.708z"/>
										<path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
									</svg>
									<?php
								}
								?>
							</span>
							<span
								class="mr-4"
								title="Last updated"
								data-toggle="tooltip"
								data-trigger="hover"
								data-dismiss="click"
								data-placement="top">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
									<path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
									<path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
								</svg>&nbsp;&nbsp;<?= DateHelper::prettyFull($row->updated_at, false); ?>
							</span>
							<a href="#" class="btn btn-blank float-right p-0" data-toggle="dropdown">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M2 12.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z"/>
								</svg>
							</a>
							<ul class="dropdown-menu">
								<li class="nav-link">
									<a
										href="<?= UrlHelper::backend($url . '/edit/' . $row->id); ?>"
										class="float-left mr-4"
										title="Edit the entry"
										data-toggle="tooltip"
										data-trigger="hover"
										data-dismiss="click"
										data-placement="top">
										<p class="float-left btn-list-icon mr-2">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
												<path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
											</svg>
										</p>
										<p class="float-left btn-list-text">
											Edit
										</p>
									</a>
								</li>
								<?php
								if (!$row->deleted_at) {
									?>
									<li class="nav-link">
										<a
											href="#"
											class="float-left mr-4"
											data-original-title="Are you sure?"
											data-trigger="focus"
											data-html="true"
											data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
											data-toggle="popover">
											<span
												title="Delete the entry"
												data-toggle="tooltip"
												data-trigger="hover"
												data-dismiss="click"
												data-placement="top">
												<p class="float-left btn-list-icon mr-2">
													<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
														<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
														<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
													</svg>
												</p>
												<p class="float-left btn-list-text">
													Delete
												</p>
											</span>
										</a>
									</li>
									<?php
								} else {
									?>
									<li class="nav-link">
										<a
											href="#"
											class="float-left mr-4"
											data-original-title="Are you sure?"
											data-trigger="focus"
											data-html="true"
											data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id); ?>?from=<?= urlencode($url); ?>">Yes</a>'
											data-toggle="popover">
											<span
												title="Recover the entry"
												data-toggle="tooltip"
												data-trigger="hover"
												data-dismiss="click"
												data-placement="top">
												<p class="float-left btn-list-icon mr-2">
													<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
														<path d="M8.5 11.5a.5.5 0 0 1-1 0V7.707L6.354 8.854a.5.5 0 1 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 7.707V11.5z"/>
														<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
													</svg>
												</p>
												<p class="float-left btn-list-text">
													Recover
												</p>
											</span>
										</a>
									</li>
									<?php
								}
								?>
							</ul>
						</div>
					</div>
				</div>
				<?php
			}
			?>
		</div>
		<?php
	} else {
		?>
		<div class="card">
            <div class="card-body p-3 pt-0">
                <strong class="h5">No results</strong>
            </div>
        </div>
		<?php
	}
	?>
	</div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
