<?php
/**
 * Personas widget template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */

use Kytschi\Makabe\Controllers\PersonasController;
use Kytschi\Tengu\Helpers\UrlHelper;

$personas = (new PersonasController())->get();
?>
<div class="row">
	<div class="col-12">
        <div class="card mb-3 p-2">
            <div class="card-header">
				<span class="card-title">Available</span>
            </div>
		</div>
	</div>
	<div class="col-12 mb-4">
		<?php
		if ($personas->count()) {
			?>
			<div id="tiles">
				<div class="tile-item">
					<div class="card p-2">
						<div class="card-header">
							<div class="radio switcher">
								<div class="checkbox switcher mt-2">
									<label
										title="Use this persona"
										data-toggle="tooltip"
										data-trigger="hover"
										data-dismiss="click"
										data-placement="bottom">
										<input
											type="radio"
											name="persona_id"
											value=""
											<?= (!empty($data->persona) ? $data->persona->id : '')  == '' ? ' checked="checked"' : ''; ?>>
										<span>
											<small class="switcher-on">
												<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
													<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
												</svg>
											</small>
											<small class="switcher-off">
												<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
													<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
												</svg>
											</small>
										</span>
									</label>
								</div>
							</div>
						</div>
						<div class="card-body pb-0">
							<div class="row m-0">
								<div class="col-12 p-0 pb-3">
									<div class="float-left">
										<p class="h3">No persona selected</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php
				foreach ($personas as $item) {
					?>
					<div class="tile-item">
						<div class="card p-2">
							<div class="card-header">
								<div class="radio switcher">
									<div class="checkbox switcher mt-2">
										<label
											title="Use this persona"
											data-toggle="tooltip"
											data-trigger="hover"
											data-dismiss="click"
											data-placement="bottom">
											<input
												type="radio"
												name="persona_id"
												value="<?= $item->id; ?>"
												<?= $item->id == (!empty($data->persona) ? $data->persona->id : 'none') ? ' checked="checked"' : ''; ?>>
											<span>
												<small class="switcher-on">
													<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
														<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
													</svg>
												</small>
												<small class="switcher-off">
													<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
														<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
													</svg>
												</small>
											</span>
										</label>
									</div>
								</div>
							</div>
							<div class="card-body pb-0">
								<div class="row m-0">
									<div class="col-12 p-0 pb-3">
										<?php
										if ($item->profile_image) {
											?>
											<span class="profile-pic mr-3 float-left">
												<img src="<?= $item->profile_image->url; ?>" alt="<?= $item->full_name; ?>" />
											</span>
											<?php
										}
										?>
										<div class="float-left">
											<p class="h3 mb-0"><?= ($item->title ? $item->title . ' ' : '') . $item->full_name; ?></p>
											<?php
											if ($item->job_title) {
												echo $item->job_title . '<br/>';
											}
											?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<?php
				}
				?>
			</div>
			<?php
		} else {
			?>
			<div class="card">
				<div class="card-body p-3 pt-0">
					<strong class="h5">No results</strong>
				</div>
			</div>
			<?php
		}
		?>
    </div>
</div>
