<?php
/**
 * Projects edit template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->hrs . '/projects';
echo $this->partial("common/form/messages");
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
<div class="row mb-3">
    <div class="col-12">
        <div class="card p-0">
            <div class="card-body">
                <a
                    href="<?= UrlHelper::generate(UrlHelper::backend($url)); ?>"
                    class="btn btn-blank mr-2 text-center"
                    title="Go back to the projects list"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                        <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
                    </svg><br/>
                    back
                </a>
                <button
                    id="btn-save"
                    class="btn btn-blank float-right"
                    type="button"
                    title="Save the project"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg><br/>
                    save
                </button>
                <a
                    href="<?= UrlHelper::backend($url . '/add'); ?>"
                    class="btn btn-blank float-right"
                    title="Add a new project"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                    </svg><br/>
                    new
                </a>
                <?php
                    if ($data->status == 'deleted') {
                        ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Recover the project from the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                                </svg><br/>
                                recover
                            </div>
                        </button>
                        <?php
                    } else {
                    ?>
                        <button
                            class="btn btn-blank float-right"
                            type="button"
                            data-original-title="Are you sure?"
                            data-html="true"
                            data-trigger="focus"
                            data-toggle="popover"
                            data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/delete/' . $data->id); ?>">Yes</a>'>
                            <div
                                data-toggle="tooltip"
                                data-dismiss="hover"
                                data-placement="top"
                                title="Throw the project into the trash">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg><br/>
                                delete
                            </div>
                        </button>
                        <?php
                    }
                    ?>
            </div>
        </div>
    </div>
</div>
<form
    id="form-edit"
    method="post"
    action="<?= UrlHelper::backend($url . '/update/' . $data->id); ?>" enctype="multipart/form-data">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0 pt-4">
                    <div class="d-flex flex-wrap flex-sm-nowrap pl-3 pr-3">
                        <div class="mr-4 mb-4">
                            <?php
                            switch ($data->status) {
                                case 'active':
                                    $label = "I'm live!";
                                    $bg_colour = 'bg-success';
                                    break;
                                case 'inactive':
                                    $label = "I'm inactive";
                                    $bg_colour = 'bg-warning';
                                    break;
                                case 'deleted':
                                    $label = "I'm in a deleted state";
                                    $bg_colour = 'bg-danger';
                                    break;
                                default:
                                    break;
                            }
                            ?>
                            <div
                                class="preview-img"
                                title="<?= $label; ?>"
                                data-toggle="tooltip"
                                data-trigger="hover"
                                data-dismiss="click"
                                data-placement="bottom">
                                <div class="position-relative border">
                                    <img 
                                        src="<?= $this->tengu->theme->getAsset('imgs/edit-item.png'); ?>" 
                                        alt="Edit the entry">
                                </div>
                                <div class="circle border border-white <?= $bg_colour; ?>"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1 mb-4">
                            <div class="form-group mb-4">
                                <label for="name">
                                    Title
                                    <span class="required">*</span>
                                </label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="name"
                                    value="<?= FormController::getFormData('name', $data); ?>"
                                    required>
                            </div>
                            <div class="form-group mb-4">
                                <label for="summary">Description</label>
                                <input
                                    id="summary"
                                    name="summary"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="summary"
                                    value="<?= FormController::getFormData('summary', $data); ?>">
                            </div>
                            <div class="form-group mb-4">
                                <label for="day_rate">
                                    Day rate (<?= NumberHelper::currencySymbol(); ?>)
                                </label>
                                <input
                                    id="day_rate"
                                    name="day_rate"
                                    type="text"
                                    class="form-control mt-2"
                                    aria-describedby="day_rate"
                                    value="<?= FormController::getFormData('day_rate', $data); ?>">
                            </div>
                        </div>
                    </div>
                    <ul class="nav p-0 m-0">
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#overview-tab"
                                aria-controls="overview-tab"
                                aria-selected="<?= UrlHelper::activeTab('overview-tab', 'overview-tab', true); ?>">
                                Extra
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#notes-tab">
                                Notes
                                <?php
								if ($note_count = $data->notes->count()) {
									?>
									<span class="badge badge-primary"><?= $note_count; ?></span>
									&nbsp;
									<?php
								}
								?>
                            </a>
                        </li>
                        <li class="nav-item mt-2">
                            <a
                                class="nav-link <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                                data-toggle="tab"
                                role="tab"
                                href="#activity-tab">
                                Activity
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content mt-5">
                <div
                    class="tab-pane <?= UrlHelper::activeTab('overview-tab', 'overview-tab'); ?>"
                    id="overview-tab"
                    role="tabpanel"
                    aria-labelledby="overview-tab">
                    <div class="row">
                        <div class="col-12">
                            <?= $this->partial("common/tags", ['data' => $data->tags]); ?>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('notes-tab', 'overview-tab'); ?>"
                    id="notes-tab"
                    role="tabpanel"
                    aria-labelledby="notes-tab">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card shadow-none">
                                        <div class="card-header m-0">
                                            <span class="card-title">Notes</span>
                                        </div>
                                        <div class="card-body">
                                            <?= $this->partial(
                                                'common/notes/list',
                                                [
                                                    'notes' => $data->notes,
                                                    'url' => $url . '/edit/' . $data->id . '?clear=true&tab=notes-tab'
                                                ]
                                            ); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="tab-pane <?= UrlHelper::activeTab('activity-tab', 'overview-tab'); ?>"
                    id="activity-tab"
                    role="tabpanel"
                    aria-labelledby="activity-tab">
                    <div class="row">
                        <div class="col-6">
                            <?= $this->partial("common/logs", ['data' => $data->logs]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>