<?php
/**
 * Category widget template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Helpers\UrlHelper;
?>
<div class="card">
    <div class="card-header mb-4">
        <span class="card-title">Categories</span>
    </div>
    <div class="card-body p-0 pb-3">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <tr>
                        <td class="border-0">
                            <select id="widget-categories" class="form-control">
                                <?php
                                if ($categories->count()) {
                                    foreach ($categories as $category) {
                                        ?>
                                        <option value="<?= $category->id; ?>">
                                            <?= $category->name . ' (' . str_replace('-', ' ', $category->type) . ')'; ?>
                                        </option>
                                        <?php
                                    }
                                } else {
                                    ?>
                                    <option value="0" disabled>No categories</option>
                                    <?php
                                }
                                ?>
                            </select>
                        </td>
                        <td width="60px" class="border-0">
                            <button id="widget-category-add" type="button" class="btn btn-blank p-0 m-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                                </svg><br/>
                                add
                            </button>
                        </td>
                    <tr>
                </table>
            </div>
            <div class="col-12">
                <table id="widget-categories-table" class="table table-sorter">
                    <thead>
                        <tr>
                            <th>Belongs to category</th>
                            <th width="120px">Primary</th>
                            <th width="80px">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (!empty($data)) {
                            if ($data->categories->count()) {
                                foreach ($data->categories as $result) {
                                    $edit_url = $url . '/edit/' . $result->id;
                                    if (!empty($back_url)) {
                                        $edit_url .= '?back-url=' . urlencode($back_url);
                                    }
                                    ?>
                                    <tr id="category-<?= $result->id; ?>">
                                        <td class="widget-category-name">
                                            <?= $result->name; ?>
                                        </td>
                                        <td class="widget-category-primary">
                                            <div class="radio switcher">
                                                <div class="checkbox switcher mt-2">
                                                    <label
                                                        title="This is the items primary category"
                                                        data-toggle="tooltip"
                                                        data-trigger="hover"
                                                        data-dismiss="click"
                                                        data-placement="bottom">
                                                        <input
                                                            type="radio"
                                                            name="category_primary"
                                                            value="<?= $result->id; ?>"
                                                            <?= $data->isPrimary($result->id) ? ' checked' : '';?>>
                                                        <span>
                                                            <small class="switcher-on">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                                                </svg>
                                                            </small>
                                                            <small class="switcher-off">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                                </svg>
                                                            </small>
                                                        </span>
                                                    </label>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="widget-category-button">
                                            <button
                                                id="btn-category-<?= $result->id; ?>"
                                                class="btn btn-blank float-right btn-widget-category m-0 p-0"
                                                type="button">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                            </button>
                                            <a
                                                href="<?= UrlHelper::backend($edit_url); ?>"
                                                class="btn btn-blank float-right m-0 p-0 mr-2">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                                </svg>
                                            </a>
                                            <input type="hidden" name="category_id[]" value="<?= $result->id; ?>"/>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            } else {
                                ?>
                                <tr>
                                    <td colspan="2">No categories</td>
                                </tr>
                                <?php
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="2">No categories</td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                    <tfoot class="d-none">
                        <tr>
                            <td class="widget-category-name"></td>
                            <td class="widget-category-primary"></td>
                            <td class="widget-category-button">
                                <button
                                    class="btn btn-blank float-right btn-widget-category"
                                    type="button">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </button>
                                <input type="hidden" name="category_id[]" value=""/>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <?php
            if (
                !empty($data) &&
                in_array(
                    $data->type,
                    [
                        'event-category',
                        'page-category',
                        'blog-post-category',
                        'portfolio-category',
                        'menu-category'
                    ]
                )
            ) {
                ?>
                <div class="col-12">
                    <table id="widget-category-items-table" class="table table-sorter">
                        <thead>
                            <tr>
                                <th>Category items</th>
                                <th width="80px">Sort</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($data->category_items->count()) {
                                foreach ($data->category_items as $key => $result) {
                                    ?>
                                    <tr id="category-<?= $result->id; ?>">
                                        <td class="widget-category-name">
                                            <?= $result->name; ?>
                                        </td>
                                        <td class="widget-category-sort">
                                            <input
                                                class="form-control"
                                                name="category_sort[<?= $result->id; ?>]"
                                                value="<?= $key+1; ?>">
                                        </td>
                                    </tr>
                                    <?php
                                }
                            } else {
                                ?>
                                <tr>
                                    <td colspan="2">No category items</td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
</div>
<script src="<?= $this->tengu->theme->getAsset('js/core/categories.js'); ?>"></script>