<?php
/**
 * Restock products index template.
 *
 * @copyright   2022 Kytschi
 * @version     0.0.1
 *
 * Copyright Kytschi - All Rights Reserved.
 * Unauthorised copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->sales . '/products/restock';
echo $this->partial("common/form/messages");
?>

<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <?php
                    $this->partial('common/lists/search', ['url' => $url]);
                ?>
                <button
                    class="btn btn-blank btn-save float-right"
                    type="button"
                    title="Update the products stock"
                    data-type="full"
                    data-toggle="tooltip"
                    data-trigger="hover"
                    data-dismiss="click"
                    data-placement="top">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg><br/>
                    update
                </button>
            </div>
        </div>
    </div>
</div>
<form id="form-edit" method="post" action="<?= UrlHelper::backend($url . '/update'); ?>">
    <div class="row mb-3">
    <?php
    if ($data->total_items) {
        ?>
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th width="140px">In stock</th>
                                <th width="180px">New stock</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($data->getItems() as $row) {
                            ?>
                            <tr>
                                <td>
                                    <?= $row->name; ?><br/>
                                    <small><?= $row->code; ?></small>
                                </td>
                                <td><?= $row->stock; ?></td>
                                <td>
                                    <input
                                        name="quantity[<?= $row->product->id; ?>]"
                                        type="text"
                                        class="form-control"
                                        value="<?= $row->stock; ?>">
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php
    }  else {
        ?>
        <div class="col-12">
            <div class="card">
                <div class="card-body p-3 pt-0">
                    <strong class="h5">No results</strong>
                </div>
            </div>
        </div>
        <?php
    }
    ?>
    </div>
</form>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url)
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/edit.js'); ?>"></script>
