<?php
/**
 * Dashboard index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh

 */
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\NumberHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = ($this->di->getConfig())->urls->fms . '/dashboard';

$filter_status = $this->tengu->getFilters('status');
$filter_direction = $this->tengu->getFilters('direction');
$filter_year = $this->tengu->getFilters('year');

?>
<div class="row mb-3">
	<div class="col-12">
		<div class="card p-0">
			<div class="card-body">
		        <div class="float-right dropdown mr-3">
		            <a
                        href="#"
                        class="btn btn-default form-control-solid dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-expanded="false">
		                Filter
		            </a>
		            <div class="dropdown-menu p-4">
		                <div class="pb-3">Filter Options</div>
		                <form method="get" action="<?= UrlHelper::backend($url); ?>">
		                    <label class="form-label fw-bold">Status:</label>
		                    <select
		                        name="filters[status]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($statuses as $status) {
                                    ?>
                                    <option value="<?= $status; ?>"<?= $filter_status == $status ? ' selected="selected"' : ''; ?>>
                                        <?= $status; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
                            <label class="form-label fw-bold">Tax year:</label>
		                    <select
		                        name="filters[year]"
		                        class="form-control form-control-solid"
		                        data-placeholder="Please select an option"
		                        tabindex="-1"
		                        aria-hidden="true">
		                        <option value="">No filter</option>
                                <?php
                                foreach ($years as $year) {
                                    ?>
                                    <option value="<?= $year->id; ?>"<?= $filter_year == $year->id ? ' selected="selected"' : ''; ?>>
                                        <?= $year->code; ?>
                                    </option>
                                    <?php
                                }
                                ?>
		                    </select>
		                    <div class="d-flex justify-content-end mt-4">
		                        <a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
		                        <button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
		                    </div>
		                </form>
		            </div>
		        </div>				
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
    <div class="col-3">
        <div class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                </svg>
                <div class="h4 text-white mt-3 mb-1" style="height: 30px">
                    <?php
                        echo DateHelper::pretty($tax_year->tax_year_start, false) . ' to ' . DateHelper::pretty($tax_year->tax_year_end, false) ;
                    ?>
                </div>
                <div class="text-white">
                    Tax year (<?= $tax_year->code; ?>)
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12 pb-3">
        <span class="h3">Gross</span>
    </div>
    <div class="col-3">
        <div class="card bg-warning">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['incoming']); ?>
				</div>
                <div class="text-white">
                    Incoming
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['outgoing']); ?>
				</div>
                <div class="text-white">
					Outgoings
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['turnover']); ?>
				</div>
                <div class="text-white">
					Turnover
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12 pb-3">
        <span class="h3">Taxable</span>
    </div>
    <div class="col-3">
        <div class="card bg-warning">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['incoming_taxable']); ?>
				</div>
                <div class="text-white">
                    Incoming
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-danger">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['outgoing_taxable']); ?>
				</div>
                <div class="text-white">
					Outgoings
				</div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-success">
            <div class="card-body">
				<svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1" style="height: 30px">
					<?= NumberHelper::toCurrency($stats['turnover_taxable']); ?>
				</div>
                <div class="text-white">
					Turnover
				</div>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <span class="card-title">Dividends</span>
            </div>
            <div class="card-body">
            <?php
            if ($users->count()) {
                ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Shareholder</th>
                            <th width="180px">Amount</th>
                            <th width="180px">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($users as $user) {
                            ?>
                            <tr>
                                <td><?= $user->full_name; ?></td>
                                <td><?= NumberHelper::toCurrency($user->dividends_current_year_amount); ?></td>
                                <td>
                                    <a
                                        href="<?= UrlHelper::backend('/users/edit/' . $user->id . '#dividends-tab'); ?>"
                                        class="btn btn-blank float-right"
                                        title="View the user's dividends"
                                        data-toggle="tooltip"
                                        data-trigger="hover"
                                        data-dismiss="click"
                                        data-placement="top">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <?php
            } else {
                ?>
                <span class="h4">No shareholders</span>
                <?php
            }
            ?>
            </div>
        </div>
    </div>
</div>