<?php
/**
 * Messages index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\StringHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/messages';

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-12">
		<div class="card p-0">
            <div class="card-body">
                <div class="nav nav-pills" role="tablist">
                    <a
                        class="nav-item nav-link nav-item-blank btn btn-blank float-left"
                        href="<?= UrlHelper::backend($url . '/inbox'); ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
							<path d="M4.98 4a.5.5 0 0 0-.39.188L1.54 8H6a.5.5 0 0 1 .5.5 1.5 1.5 0 1 0 3 0A.5.5 0 0 1 10 8h4.46l-3.05-3.812A.5.5 0 0 0 11.02 4H4.98zm9.954 5H10.45a2.5 2.5 0 0 1-4.9 0H1.066l.32 2.562a.5.5 0 0 0 .497.438h12.234a.5.5 0 0 0 .496-.438L14.933 9zM3.809 3.563A1.5 1.5 0 0 1 4.981 3h6.038a1.5 1.5 0 0 1 1.172.563l3.7 4.625a.5.5 0 0 1 .105.374l-.39 3.124A1.5 1.5 0 0 1 14.117 13H1.883a1.5 1.5 0 0 1-1.489-1.314l-.39-3.124a.5.5 0 0 1 .106-.374l3.7-4.625z"/>
						</svg><br/>
                        inbox
                    </a>
                    <a
                        class="nav-item nav-link nav-item-blank btn btn-blank float-left"
                        href="<?= UrlHelper::backend($url . '/sent'); ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
							<path d="m11.798 8.271-3.182 1.97c-.27.166-.616-.036-.616-.372V9.1s-2.571-.3-4 2.4c.571-4.8 3.143-4.8 4-4.8v-.769c0-.336.346-.538.616-.371l3.182 1.969c.27.166.27.576 0 .742z"/>
  							<path d="m.5 3 .04.87a1.99 1.99 0 0 0-.342 1.311l.637 7A2 2 0 0 0 2.826 14h10.348a2 2 0 0 0 1.991-1.819l.637-7A2 2 0 0 0 13.81 3H9.828a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 6.172 1H2.5a2 2 0 0 0-2 2zm.694 2.09A1 1 0 0 1 2.19 4h11.62a1 1 0 0 1 .996 1.09l-.636 7a1 1 0 0 1-.996.91H2.826a1 1 0 0 1-.995-.91l-.637-7zM6.172 2a1 1 0 0 1 .707.293L7.586 3H2.19c-.24 0-.47.042-.683.12L1.5 2.98a1 1 0 0 1 1-.98h3.672z"/>
						</svg><br/>
                        sent
                    </a>
					<a
                        class="nav-item nav-link nav-item-blank btn btn-blank float-left active"
                        href="<?= UrlHelper::backend($url . '/trash'); ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 16 16">
							<path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
						</svg><br/>
                        trash
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="tab-content mt-5">
    <div        
        class="tab-pane active"
        role="tabpanel">
		<div class="row mb-3">
			<div class="col-12">
				<div class="card p-0">
					<div class="card-body">
						<?php
							$this->partial('common/lists/search', ['url' => $url . '/trash']);
						?>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<?php
			if ($data->total_items) {
				foreach ($data->getItems() as $row) {
					?>
					<div class="col-12">
						<div class="card mb-5">
							<div class="card-body p-4">
								<p class="h6"><?= StringHelper::decrypt($row->subject); ?></p>
								<p><?= nl2br(StringHelper::decrypt($row->message)); ?></p>
								<p class="p-0 m-0 float-left w-100">
									<span class="float-left">
										<?= StringHelper::decrypt($row->from_name); ?>
										&lt;<?= StringHelper::decrypt($row->from_email); ?>&gt;
										<?= !empty($phone = StringHelper::decrypt($row->from_phone)) ? '| ' . $phone : ''; ?>
									</span>
									<span class="float-right">
										<?php
										switch ($row->type) {
											case 'email':
												?>
												<span
													title="This message is an email"
													data-toggle="tooltip"
													data-trigger="hover"
													data-dismiss="click"
													data-placement="bottom">
													<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
														<path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
													</svg>
												</span>
												<?php
												break;
											default:
												break;
										}
										?>
									</span>
								</p>
								<p class="message-date p-0 m-0 float-left w-100">
									<?= DateHelper::pretty($row->created_at); ?>,
									<button
										class="note-button btn btn-blank p-0 m-0"
										type="button"
										data-original-title="Are you sure?"
										data-html="true"
										data-trigger="focus"
										data-toggle="popover"
										data-content='<span class="btn btn-secondary">No</span>&nbsp;<a class="btn btn-danger" href="<?= UrlHelper::backend($url . '/recover/' . $row->id. '?from=' . urlencode($url . '/trash')); ?>">Yes</a>'>
										<span
											data-toggle="tooltip"
											data-dismiss="hover"
											data-placement="top"
											title="Recover the message">
											recover
										</span>
									</button>
								</p>
							</div>
						</div>
					</div>
					<?php
				}
			} else {
				?>
				<div class="col-12">
					<div class="card">
						<div class="card-body p-3 pt-0">
							<strong class="h5">No messages</strong>
						</div>
					</div>
				</div>
				<?php
			}
			?>
		</div>
	</div>
</div>
<?php
    echo $this->partial(
        'common/lists/pagination',
        [
            'data' => $data,
            'url' => UrlHelper::backend($url . '/trash')
        ]
    );
?>
<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
