<?php
use Kytschi\Tengu\Helpers\DateHelper;

if ($latest_posts = $this->tengu->findSimilarPages(12)) {
    if (!$latest_posts->count()) {
        return;
    }
    ?>
    <div class="col-12">
        <div class="row">
            <div class="col-12 p-0">
                <section class="card">
                    <div class="card-header">
                        <h3>
                            <span>Reviews</span>
                        </h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <span class="sub-heading">
                                    Our latest
                                </span>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <div class="row">
            <?php
            foreach ($latest_posts as $item) {
                $category = null;
                if (!empty($item->categories)) {
                    $category = $item->categories->getFirst();
                }
                ?>
                <div class="col-lg-4 col-md-12">
                    <div class="category-page">
                        <div class="category-image-thumb">
                            <a href="<?= !empty($item->canonical_url) ? $item->canonical_url : $item->url; ?>">
                                <img 
                                    src="<?= !empty($item->cover_image) ? $item->cover_image->thumb_url : $this->tengu->theme->getAsset('imgs/placeholder.jpg'); ?>"
                                    alt="<?= $item->name; ?>">
                            </a>
                        </div>
                        <div class="category-content">
                            <?php
                            if ($category) {
                                ?>
                                <div class="category-name">
                                    <a href="<?= !empty($category->canonical_url) ? $category->canonical_url : $category->url; ?>">
                                        <?= $category->name; ?>
                                    </a>
                                </div>
                                <?php
                            }
                            ?>
                            <div class="category-info">
                                <ul>
                                    <li>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                                            <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                        </svg>
                                        <span class="post-date"><?= DateHelper::prettyFull($item->created_at, false); ?></span>
                                    </li>
                                    <li>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                        </svg>
                                        <span>By <?= !empty($item->persona) ? $item->persona->full_name : $item->created->full_name; ?></span>
                                    </li>
                                </ul>
                            </div>
                            <h4>
                                <a href="<?= !empty($item->canonical_url) ? $item->canonical_url : $item->url; ?>">
                                    <?= $item->name; ?>
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <?php
}
?>