<?php
use Kytschi\Tengu\Controllers\Website\MenuController;
use Kytschi\Tengu\Helpers\UrlHelper;

$menu = $this->tengu->findMenu(['slug' => 'header menu']);
?>
<nav id="menu" class="row m-0">
    <div class="col-12">
        <h1 class="float-left">
            <img src="<?= $this->tengu->theme->getAsset('imgs/logo.png'); ?>" alt="Monkey"/>
            <span><?= $this->tengu->settings->name; ?></span>
        </h1>
        <ul id="menu-nav" class="float-right">
            <?php
            foreach ($menu->category_items as $item) {
                $link = $item->link;
                ?>
                <li class="nav-item">
                    <a
                        href="<?= $link; ?>"
                        class="nav-link<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                        <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                    >
                        <?= $item->name; ?>
                    </a>
                </li>
                <?php
            }
            ?>
        </ul>
        <div id="menu-nav-mini">
            <span class="nav-link" data-toggle="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
                </svg>
            </span>
            <ul class="dropdown-menu dropdown-menu-right">
                <?php
                foreach ($menu->category_items as $item) {
                    $link = $item->link;
                    ?>
                    <li class="nav-item">
                        <a
                            href="<?= $link; ?>"
                            class="nav-link<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                            <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                        >
                            <?= $item->name; ?>
                        </a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</nav>
