<?php
/**
 * Spun content index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

switch ($page->type) {
	case 'blog-post':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/' . $page->id . '/spinner';
		$parent = 'Blog posts';
		$child = 'Blog post';
		break;
	case 'blog-post-category':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/categories/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/categories';
		$parent = 'Blog post categories';
		$child = 'Blog post category';
		break;
	case 'page':
		$url = ($this->di->getConfig())->urls->cms . '/pages/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/pages/' . $page->id . '/spinner';
		$parent = 'Pages';
		$child = 'Page';
		break;
	case 'portfolio':
		$url = ($this->di->getConfig())->urls->cms . '/portfolio/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/portfolio/' . $page->id . '/spinner';
		$parent = 'Portfolio';
		$child = 'Portfolio piece';
		break;
}

$url .= $page->id . '/spinner/' . $spin->id . '/spun';

$filter_status = $this->tengu->getFilters('status');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<a
					href="<?= UrlHelper::backend($parentUrl . '/edit/' . $spin->id); ?>"
					class="btn btn-blank mr-2 text-center"
					title="Go back to the page"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
					</svg><br/>
					back
				</a>
				<a
					href="<?= UrlHelper::backend($parentUrl . '/' . $spin->id . '/export-start'); ?>"
					class="btn btn-blank float-right"
					title="Trigger the export job"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
						<path d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
					</svg><br/>
					start export
				</a>
			</div>
		</div>
	</div>
</div>
<?php
if (!empty($spin->job)) {
	?>
	<div class="row mb-3">
		<div class="col-12 mb-0">
			<div class="alert alert-info d-flex align-items-center mb-0">
				<div class="d-flex flex-column">
					<p>Awaiting export content job to be complete</p>
				</div>
			</div>
		</div>
	</div>
	<?php
} else {
	?>
	<div class="row mb-3">
		<div class="col-12">
			<div class="card">
				<div class="card-body">
					<?php
						$this->partial('common/lists/search', ['url' => $url]);
					?>
					<div class="float-right dropdown mr-3">
						<a
							href="#"
							class="btn btn-default form-control-solid dropdown-toggle"
							data-toggle="dropdown"
							role="button"
							aria-expanded="false">
							Filter
						</a>
						<div class="dropdown-menu p-4">
							<div class="pb-3">Filter Options</div>
							<form method="get" action="<?= UrlHelper::backend($url); ?>">
								<?php
									$this->partial('common/lists/sorting', ['url' => $url]);
								?>
								<label class="form-label fw-bold">Status:</label>
								<select
									name="filters[status]"
									class="form-control form-control-solid"
									data-placeholder="Please select an option"
									tabindex="-1"
									aria-hidden="true">
									<option value="">No filter</option>
									<option value="active"<?= $filter_status == 'active' ? ' selected="selected"' : ''; ?>>Active</option>
									<option value="deleted"<?= $filter_status == 'deleted' ? ' selected="selected"' : ''; ?>>Deleted</option>
								</select>
								<div class="d-flex justify-content-end mt-4">
									<a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
									<button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-12">
		<?php
		if ($data->total_items) {
			?>
			<div id="tiles">
			<?php
			foreach ($data->getItems() as $row) {
				echo $this->partial(
					'common/lists/card',
					[
						'data' => $row,
						'title_var' => 'title',
						'url' => $url,
						'show_live' => false,
						'show_spinner' => false
					]
				);
			}
			?>
			</div>
			<?php
		}  else {
			?>
			<div class="card">
				<div class="card-body p-3 pt-0">
					<strong class="h5">No results</strong>
				</div>
			</div>
			<?php
		}
		?>
		</div>
	</div>
	<?php
		echo $this->partial(
			'common/lists/pagination',
			[
				'data' => $data,
				'url' => UrlHelper::backend($url)
			]
		);
	?>
	<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
	<?php
}
?>
