<?php
/**
 * Spun content index template.
 *
 * @copyright   2023 Mike Welsh <mike@kytschi.com>
 * @version     0.0.1
 *
 * Copyright 2023 Mike Welsh
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;

switch ($page->type) {
	case 'blog-post':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/' . $page->id . '/spinner';
		$parent = 'Blog posts';
		$child = 'Blog post';
		break;
	case 'blog-post-category':
		$url = ($this->di->getConfig())->urls->cms . '/blog-posts/categories/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/blog-posts/categories';
		$parent = 'Blog post categories';
		$child = 'Blog post category';
		break;
	case 'page':
		$url = ($this->di->getConfig())->urls->cms . '/pages/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/pages/' . $page->id . '/spinner';
		$parent = 'Pages';
		$child = 'Page';
		break;
	case 'portfolio':
		$url = ($this->di->getConfig())->urls->cms . '/portfolio/';
		$parentUrl = ($this->di->getConfig())->urls->cms . '/portfolio/' . $page->id . '/spinner';
		$parent = 'Portfolio';
		$child = 'Portfolio piece';
		break;
}

$url .= $page->id . '/spinner/' . $spin->id . '/spun';

$filter_status = $this->tengu->getFilters('status');

echo $this->partial("common/form/messages");
?>
<div class="row mb-3">
    <div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=live'); ?>" class="card bg-primary">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                    <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                    <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $stats['live']; ?></strong> is live
                </div>
                <div class="text-white">
                    Awesome
				</div>
            </div>
        </a>
    </div>
	<div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=pending'); ?>" class="card bg-info">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
  					<path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
  					<path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $stats['pending']; ?></strong> <?= $stats['pending'] == 1 ? 'is' : 'are'; ?> pending
                </div>
                <div class="text-white">
                    Awaiting to be used
				</div>
            </div>
        </a>
    </div>
	<div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[used]=true'); ?>" class="card bg-warning">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
					<path d="M10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 4a4 4 0 0 0-4 4 .5.5 0 0 1-1 0 5 5 0 0 1 5-5 .5.5 0 0 1 0 1zm4.5 3.5a.5.5 0 0 1 .5.5 5 5 0 0 1-5 5 .5.5 0 0 1 0-1 4 4 0 0 0 4-4 .5.5 0 0 1 .5-.5z"/>
				</svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $stats['used']; ?></strong> <?= $stats['used'] == 1 ? 'has' : 'have'; ?> been used
                </div>
                <div class="text-white">
                    Been used
				</div>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a href="<?= UrlHelper::backend($url . '?filters[status]=deleted'); ?>" class="card bg-danger">
            <div class="card-body">
                <svg width="40" height="40" viewBox="0 0 16 16" class="svg-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                </svg>
                <div class="h3 text-white mt-3 mb-1">
                    <strong><?= $stats['deleted']; ?></strong> deleted
                </div>
                <div class="text-white">
                    For the scrap heap
				</div>
            </div>
        </a>
    </div>
</div>
<div class="row mb-3">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<a
					href="<?= UrlHelper::backend($parentUrl . '/edit/' . $spin->id); ?>"
					class="btn btn-blank mr-2 text-center"
					title="Go back to the page"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"/>
					</svg><br/>
					back
				</a>
				<a
					href="<?= UrlHelper::backend($parentUrl . '/spin/' . $spin->id); ?>"
					class="btn btn-blank float-right"
					title="Trigger the spin"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M6.999 2.6A5.5 5.5 0 0 1 15 7.5a.5.5 0 0 0 1 0 6.5 6.5 0 1 0-13 0 5 5 0 0 0 6.001 4.9A5.5 5.5 0 0 1 1 7.5a.5.5 0 0 0-1 0 6.5 6.5 0 1 0 13 0 5 5 0 0 0-6.001-4.9zM10 7.5a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
					</svg><br/>
					spin
				</a>
				<a
					href="<?= UrlHelper::backend($parentUrl . '/' . $spin->id . '/export'); ?>"
					class="btn btn-blank float-right"
					title="Exporting the spun content"
					data-toggle="tooltip"
					data-trigger="hover"
					data-dismiss="click"
					data-placement="bottom">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" viewBox="0 0 16 16">
						<path d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
						<path d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
					</svg><br/>
					exports
				</a>
			</div>
		</div>
	</div>
</div>
<?php
if (!empty($spin->job)) {
	?>
	<div class="row mb-3">
		<div class="col-12 mb-0">
			<div class="alert alert-info d-flex align-items-center mb-0">
				<div class="d-flex flex-column">
					<p>Awaiting spinning content job to be complete</p>
				</div>
			</div>
		</div>
	</div>
	<?php
} else {
	?>
	<div class="row mb-3">
		<div class="col-12">
			<div class="card">
				<div class="card-body">
					<?php
						$this->partial('common/lists/search', ['url' => $url]);
					?>
					<div class="float-right dropdown mr-3">
						<a
							href="#"
							class="btn btn-default form-control-solid dropdown-toggle"
							data-toggle="dropdown"
							role="button"
							aria-expanded="false">
							Filter
						</a>
						<div class="dropdown-menu p-4">
							<div class="pb-3">Filter Options</div>
							<form method="get" action="<?= UrlHelper::backend($url); ?>">
								<?php
									$this->partial('common/lists/sorting', ['url' => $url]);
								?>
								<label class="form-label fw-bold">Status:</label>
								<select
									name="filters[status]"
									class="form-control form-control-solid"
									data-placeholder="Please select an option"
									tabindex="-1"
									aria-hidden="true">
									<option value="">No filter</option>
									<option value="active"<?= $filter_status == 'active' ? ' selected="selected"' : ''; ?>>Active</option>
									<option value="deleted"<?= $filter_status == 'deleted' ? ' selected="selected"' : ''; ?>>Deleted</option>
								</select>
								<div class="d-flex justify-content-end mt-4">
									<a href="<?= UrlHelper::backend($url); ?>" class="btn btn-default btn-sm p-2 pl-3 pr-3 mr-2">Reset</a>
									<button type="submit" class="btn btn-sm btn-primary p-2 pl-3 pr-3" >Apply</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-12">
		<?php
		if ($data->total_items) {
			?>
			<div id="tiles">
			<?php
			foreach ($data->getItems() as $row) {
				echo $this->partial(
					'common/lists/card',
					[
						'data' => $row,
						'title_var' => 'title',
						'url' => $url,
						'show_live' => false,
						'show_spinner' => false
					]
				);
			}
			?>
			</div>
			<?php
		}  else {
			?>
			<div class="card">
				<div class="card-body p-3 pt-0">
					<strong class="h5">No results</strong>
				</div>
			</div>
			<?php
		}
		?>
		</div>
	</div>
	<?php
		echo $this->partial(
			'common/lists/pagination',
			[
				'data' => $data,
				'url' => UrlHelper::backend($url)
			]
		);
	?>
	<script src="<?= $this->tengu->theme->getAsset('js/core/list.js'); ?>"></script>
	<?php
}
?>
